//
// Generated by Bluespec Compiler, version 2013.01.beta5 (build 30325, 2013-01-23)
//
// On Tue Nov 26 08:43:07 EST 2013
//
// Method conflict info:
// Method: s_mAWVALID
// Conflict-free: s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mAWVALID
//
// Method: s_sAWREADY
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: s_mAWADDR
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mAWADDR
//
// Method: s_mAWPROT
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mAWPROT
//
// Method: s_mWVALID
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mWVALID
//
// Method: s_sWREADY
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: s_mWDATA
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mWDATA
//
// Method: s_mWSTRB
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mWSTRB
//
// Method: s_sBVALID
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: s_mBREADY
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mBREADY
//
// Method: s_sBRESP
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: s_mARVALID
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mARVALID
//
// Method: s_sARREADY
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: s_mARADDR
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mARADDR
//
// Method: s_mARPROT
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mARPROT
//
// Method: s_sRVALID
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: s_mRREADY
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
// Conflicts: s_mRREADY
//
// Method: s_sRDATA
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: s_sRRESP
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
// Method: ctl
// Conflict-free: s_mAWVALID,
// 	       s_sAWREADY,
// 	       s_mAWADDR,
// 	       s_mAWPROT,
// 	       s_mWVALID,
// 	       s_sWREADY,
// 	       s_mWDATA,
// 	       s_mWSTRB,
// 	       s_sBVALID,
// 	       s_mBREADY,
// 	       s_sBRESP,
// 	       s_mARVALID,
// 	       s_sARREADY,
// 	       s_mARADDR,
// 	       s_mARPROT,
// 	       s_sRVALID,
// 	       s_mRREADY,
// 	       s_sRDATA,
// 	       s_sRRESP,
// 	       ctl
//
//
// Ports:
// Name                         I/O  size props
// s_awready                      O     1 reg
// s_wready                       O     1 reg
// s_bvalid                       O     1
// s_bresp                        O     2 reg
// s_arready                      O     1 reg
// s_rvalid                       O     1
// s_rdata                        O    32 reg
// s_rresp                        O     2 reg
// ctl                            O    32 reg
// s_axi_aclk                     I     1 clock
// s_axi_aresetn                  I     1 reset
// s_awaddr                       I    32 reg
// s_awprot                       I     3 reg
// s_wdata                        I    32 reg
// s_wstrb                        I     4 reg
// s_araddr                       I    32 reg
// s_arprot                       I     3 reg
// s_awvalid                      I     1
// s_wvalid                       I     1
// s_bready                       I     1
// s_arvalid                      I     1
// s_rready                       I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkA4LSB(s_axi_aclk,
	       s_axi_aresetn,

	       s_awvalid,

	       s_awready,

	       s_awaddr,

	       s_awprot,

	       s_wvalid,

	       s_wready,

	       s_wdata,

	       s_wstrb,

	       s_bvalid,

	       s_bready,

	       s_bresp,

	       s_arvalid,

	       s_arready,

	       s_araddr,

	       s_arprot,

	       s_rvalid,

	       s_rready,

	       s_rdata,

	       s_rresp,

	       ctl);
  input  s_axi_aclk;
  input  s_axi_aresetn;

  // action method s_mAWVALID
  input  s_awvalid;

  // value method s_sAWREADY
  output s_awready;

  // action method s_mAWADDR
  input  [31 : 0] s_awaddr;

  // action method s_mAWPROT
  input  [2 : 0] s_awprot;

  // action method s_mWVALID
  input  s_wvalid;

  // value method s_sWREADY
  output s_wready;

  // action method s_mWDATA
  input  [31 : 0] s_wdata;

  // action method s_mWSTRB
  input  [3 : 0] s_wstrb;

  // value method s_sBVALID
  output s_bvalid;

  // action method s_mBREADY
  input  s_bready;

  // value method s_sBRESP
  output [1 : 0] s_bresp;

  // action method s_mARVALID
  input  s_arvalid;

  // value method s_sARREADY
  output s_arready;

  // action method s_mARADDR
  input  [31 : 0] s_araddr;

  // action method s_mARPROT
  input  [2 : 0] s_arprot;

  // value method s_sRVALID
  output s_rvalid;

  // action method s_mRREADY
  input  s_rready;

  // value method s_sRDATA
  output [31 : 0] s_rdata;

  // value method s_sRRESP
  output [1 : 0] s_rresp;

  // value method ctl
  output [31 : 0] ctl;

  // signals for module outputs
  wire [31 : 0] ctl, s_rdata;
  wire [1 : 0] s_bresp, s_rresp;
  wire s_arready, s_awready, s_bvalid, s_rvalid, s_wready;

  // inlined wires
  wire [35 : 0] a4l_a4wrData_data_wire_wget;
  wire [34 : 0] a4l_a4rdAddr_data_wire_wget, a4l_a4wrAddr_data_wire_wget;

  // register a4l_a4rdResp_fifof_cntr_r
  reg [1 : 0] a4l_a4rdResp_fifof_cntr_r;
  wire [1 : 0] a4l_a4rdResp_fifof_cntr_r_D_IN;
  wire a4l_a4rdResp_fifof_cntr_r_EN;

  // register a4l_a4rdResp_fifof_q_0
  reg [33 : 0] a4l_a4rdResp_fifof_q_0;
  reg [33 : 0] a4l_a4rdResp_fifof_q_0_D_IN;
  wire a4l_a4rdResp_fifof_q_0_EN;

  // register a4l_a4rdResp_fifof_q_1
  reg [33 : 0] a4l_a4rdResp_fifof_q_1;
  reg [33 : 0] a4l_a4rdResp_fifof_q_1_D_IN;
  wire a4l_a4rdResp_fifof_q_1_EN;

  // register a4l_a4wrResp_fifof_cntr_r
  reg [1 : 0] a4l_a4wrResp_fifof_cntr_r;
  wire [1 : 0] a4l_a4wrResp_fifof_cntr_r_D_IN;
  wire a4l_a4wrResp_fifof_cntr_r_EN;

  // register a4l_a4wrResp_fifof_q_0
  reg [1 : 0] a4l_a4wrResp_fifof_q_0;
  reg [1 : 0] a4l_a4wrResp_fifof_q_0_D_IN;
  wire a4l_a4wrResp_fifof_q_0_EN;

  // register a4l_a4wrResp_fifof_q_1
  reg [1 : 0] a4l_a4wrResp_fifof_q_1;
  wire [1 : 0] a4l_a4wrResp_fifof_q_1_D_IN;
  wire a4l_a4wrResp_fifof_q_1_EN;

  // register axiCount
  reg [31 : 0] axiCount;
  wire [31 : 0] axiCount_D_IN;
  wire axiCount_EN;

  // register axiRdCount
  reg [31 : 0] axiRdCount;
  wire [31 : 0] axiRdCount_D_IN;
  wire axiRdCount_EN;

  // register axiWtCount
  reg [31 : 0] axiWtCount;
  wire [31 : 0] axiWtCount_D_IN;
  wire axiWtCount_EN;

  // register b18
  reg [7 : 0] b18;
  wire [7 : 0] b18_D_IN;
  wire b18_EN;

  // register b19
  reg [7 : 0] b19;
  wire [7 : 0] b19_D_IN;
  wire b19_EN;

  // register b1A
  reg [7 : 0] b1A;
  wire [7 : 0] b1A_D_IN;
  wire b1A_EN;

  // register b1B
  reg [7 : 0] b1B;
  wire [7 : 0] b1B_D_IN;
  wire b1B_EN;

  // register lastReadAddr
  reg [31 : 0] lastReadAddr;
  wire [31 : 0] lastReadAddr_D_IN;
  wire lastReadAddr_EN;

  // register lastWriteAddr
  reg [31 : 0] lastWriteAddr;
  wire [31 : 0] lastWriteAddr_D_IN;
  wire lastWriteAddr_EN;

  // register r0
  reg [31 : 0] r0;
  wire [31 : 0] r0_D_IN;
  wire r0_EN;

  // register r4
  reg [31 : 0] r4;
  wire [31 : 0] r4_D_IN;
  wire r4_EN;

  // register r40
  reg [31 : 0] r40;
  wire [31 : 0] r40_D_IN;
  wire r40_EN;

  // register r8
  reg [31 : 0] r8;
  wire [31 : 0] r8_D_IN;
  wire r8_EN;

  // ports of submodule a4l_a4rdAddr_fifof
  wire [34 : 0] a4l_a4rdAddr_fifof_D_IN, a4l_a4rdAddr_fifof_D_OUT;
  wire a4l_a4rdAddr_fifof_CLR,
       a4l_a4rdAddr_fifof_DEQ,
       a4l_a4rdAddr_fifof_EMPTY_N,
       a4l_a4rdAddr_fifof_ENQ,
       a4l_a4rdAddr_fifof_FULL_N;

  // ports of submodule a4l_a4wrAddr_fifof
  wire [34 : 0] a4l_a4wrAddr_fifof_D_IN, a4l_a4wrAddr_fifof_D_OUT;
  wire a4l_a4wrAddr_fifof_CLR,
       a4l_a4wrAddr_fifof_DEQ,
       a4l_a4wrAddr_fifof_EMPTY_N,
       a4l_a4wrAddr_fifof_ENQ,
       a4l_a4wrAddr_fifof_FULL_N;

  // ports of submodule a4l_a4wrData_fifof
  wire [35 : 0] a4l_a4wrData_fifof_D_IN, a4l_a4wrData_fifof_D_OUT;
  wire a4l_a4wrData_fifof_CLR,
       a4l_a4wrData_fifof_DEQ,
       a4l_a4wrData_fifof_EMPTY_N,
       a4l_a4wrData_fifof_ENQ,
       a4l_a4wrData_fifof_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_a4l_a4rdAddr_do_enq,
       CAN_FIRE_RL_a4l_a4rdResp_do_deq,
       CAN_FIRE_RL_a4l_a4rdResp_fifof_both,
       CAN_FIRE_RL_a4l_a4rdResp_fifof_decCtr,
       CAN_FIRE_RL_a4l_a4rdResp_fifof_incCtr,
       CAN_FIRE_RL_a4l_a4wrAddr_do_enq,
       CAN_FIRE_RL_a4l_a4wrData_do_enq,
       CAN_FIRE_RL_a4l_a4wrResp_do_deq,
       CAN_FIRE_RL_a4l_a4wrResp_fifof_both,
       CAN_FIRE_RL_a4l_a4wrResp_fifof_decCtr,
       CAN_FIRE_RL_a4l_a4wrResp_fifof_incCtr,
       CAN_FIRE_RL_a4l_cfrd,
       CAN_FIRE_RL_a4l_cfwr,
       CAN_FIRE_RL_a4ls_doAlways,
       CAN_FIRE_RL_inc_count,
       CAN_FIRE_s_mARADDR,
       CAN_FIRE_s_mARPROT,
       CAN_FIRE_s_mARVALID,
       CAN_FIRE_s_mAWADDR,
       CAN_FIRE_s_mAWPROT,
       CAN_FIRE_s_mAWVALID,
       CAN_FIRE_s_mBREADY,
       CAN_FIRE_s_mRREADY,
       CAN_FIRE_s_mWDATA,
       CAN_FIRE_s_mWSTRB,
       CAN_FIRE_s_mWVALID,
       WILL_FIRE_RL_a4l_a4rdAddr_do_enq,
       WILL_FIRE_RL_a4l_a4rdResp_do_deq,
       WILL_FIRE_RL_a4l_a4rdResp_fifof_both,
       WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr,
       WILL_FIRE_RL_a4l_a4rdResp_fifof_incCtr,
       WILL_FIRE_RL_a4l_a4wrAddr_do_enq,
       WILL_FIRE_RL_a4l_a4wrData_do_enq,
       WILL_FIRE_RL_a4l_a4wrResp_do_deq,
       WILL_FIRE_RL_a4l_a4wrResp_fifof_both,
       WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr,
       WILL_FIRE_RL_a4l_a4wrResp_fifof_incCtr,
       WILL_FIRE_RL_a4l_cfrd,
       WILL_FIRE_RL_a4l_cfwr,
       WILL_FIRE_RL_a4ls_doAlways,
       WILL_FIRE_RL_inc_count,
       WILL_FIRE_s_mARADDR,
       WILL_FIRE_s_mARPROT,
       WILL_FIRE_s_mARVALID,
       WILL_FIRE_s_mAWADDR,
       WILL_FIRE_s_mAWPROT,
       WILL_FIRE_s_mAWVALID,
       WILL_FIRE_s_mBREADY,
       WILL_FIRE_s_mRREADY,
       WILL_FIRE_s_mWDATA,
       WILL_FIRE_s_mWSTRB,
       WILL_FIRE_s_mWVALID;

  // inputs to muxes for submodule ports
  wire [33 : 0] MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1,
		MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_2,
		MUX_a4l_a4rdResp_fifof_q_1_write_1__VAL_2;
  wire [1 : 0] MUX_a4l_a4rdResp_fifof_cntr_r_write_1__VAL_2,
	       MUX_a4l_a4wrResp_fifof_cntr_r_write_1__VAL_2,
	       MUX_a4l_a4wrResp_fifof_q_0_write_1__VAL_2;
  wire MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_1,
       MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_2,
       MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_1,
       MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_2,
       MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_1,
       MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_2;

  // remaining internal signals
  reg [63 : 0] v__h4704, v__h5039, v__h5071;
  reg [31 : 0] _theResult____h4802;
  wire [31 : 0] rdat__h4967;
  wire [1 : 0] a4l_a4rdResp_fifof_cntr_r_2_MINUS_1___d60,
	       a4l_a4wrResp_fifof_cntr_r_9_MINUS_1___d27;
  wire _dfoo1, _dfoo3, _dfoo5, _dfoo7;

  // action method s_mAWVALID
  assign CAN_FIRE_s_mAWVALID = 1'd1 ;
  assign WILL_FIRE_s_mAWVALID = s_awvalid ;

  // value method s_sAWREADY
  assign s_awready = a4l_a4wrAddr_fifof_FULL_N ;

  // action method s_mAWADDR
  assign CAN_FIRE_s_mAWADDR = 1'd1 ;
  assign WILL_FIRE_s_mAWADDR = 1'd1 ;

  // action method s_mAWPROT
  assign CAN_FIRE_s_mAWPROT = 1'd1 ;
  assign WILL_FIRE_s_mAWPROT = 1'd1 ;

  // action method s_mWVALID
  assign CAN_FIRE_s_mWVALID = 1'd1 ;
  assign WILL_FIRE_s_mWVALID = s_wvalid ;

  // value method s_sWREADY
  assign s_wready = a4l_a4wrData_fifof_FULL_N ;

  // action method s_mWDATA
  assign CAN_FIRE_s_mWDATA = 1'd1 ;
  assign WILL_FIRE_s_mWDATA = 1'd1 ;

  // action method s_mWSTRB
  assign CAN_FIRE_s_mWSTRB = 1'd1 ;
  assign WILL_FIRE_s_mWSTRB = 1'd1 ;

  // value method s_sBVALID
  assign s_bvalid = a4l_a4wrResp_fifof_cntr_r != 2'd0 ;

  // action method s_mBREADY
  assign CAN_FIRE_s_mBREADY = 1'd1 ;
  assign WILL_FIRE_s_mBREADY = s_bready ;

  // value method s_sBRESP
  assign s_bresp = a4l_a4wrResp_fifof_q_0 ;

  // action method s_mARVALID
  assign CAN_FIRE_s_mARVALID = 1'd1 ;
  assign WILL_FIRE_s_mARVALID = s_arvalid ;

  // value method s_sARREADY
  assign s_arready = a4l_a4rdAddr_fifof_FULL_N ;

  // action method s_mARADDR
  assign CAN_FIRE_s_mARADDR = 1'd1 ;
  assign WILL_FIRE_s_mARADDR = 1'd1 ;

  // action method s_mARPROT
  assign CAN_FIRE_s_mARPROT = 1'd1 ;
  assign WILL_FIRE_s_mARPROT = 1'd1 ;

  // value method s_sRVALID
  assign s_rvalid = a4l_a4rdResp_fifof_cntr_r != 2'd0 ;

  // action method s_mRREADY
  assign CAN_FIRE_s_mRREADY = 1'd1 ;
  assign WILL_FIRE_s_mRREADY = s_rready ;

  // value method s_sRDATA
  assign s_rdata = a4l_a4rdResp_fifof_q_0[31:0] ;

  // value method s_sRRESP
  assign s_rresp = a4l_a4rdResp_fifof_q_0[33:32] ;

  // value method ctl
  assign ctl = r40 ;

  // submodule a4l_a4rdAddr_fifof
  FIFO2 #(.width(32'd35),
	  .guarded(32'd1)) a4l_a4rdAddr_fifof(.RST(s_axi_aresetn),
					      .CLK(s_axi_aclk),
					      .D_IN(a4l_a4rdAddr_fifof_D_IN),
					      .ENQ(a4l_a4rdAddr_fifof_ENQ),
					      .DEQ(a4l_a4rdAddr_fifof_DEQ),
					      .CLR(a4l_a4rdAddr_fifof_CLR),
					      .D_OUT(a4l_a4rdAddr_fifof_D_OUT),
					      .FULL_N(a4l_a4rdAddr_fifof_FULL_N),
					      .EMPTY_N(a4l_a4rdAddr_fifof_EMPTY_N));

  // submodule a4l_a4wrAddr_fifof
  FIFO2 #(.width(32'd35),
	  .guarded(32'd1)) a4l_a4wrAddr_fifof(.RST(s_axi_aresetn),
					      .CLK(s_axi_aclk),
					      .D_IN(a4l_a4wrAddr_fifof_D_IN),
					      .ENQ(a4l_a4wrAddr_fifof_ENQ),
					      .DEQ(a4l_a4wrAddr_fifof_DEQ),
					      .CLR(a4l_a4wrAddr_fifof_CLR),
					      .D_OUT(a4l_a4wrAddr_fifof_D_OUT),
					      .FULL_N(a4l_a4wrAddr_fifof_FULL_N),
					      .EMPTY_N(a4l_a4wrAddr_fifof_EMPTY_N));

  // submodule a4l_a4wrData_fifof
  FIFO2 #(.width(32'd36),
	  .guarded(32'd1)) a4l_a4wrData_fifof(.RST(s_axi_aresetn),
					      .CLK(s_axi_aclk),
					      .D_IN(a4l_a4wrData_fifof_D_IN),
					      .ENQ(a4l_a4wrData_fifof_ENQ),
					      .DEQ(a4l_a4wrData_fifof_DEQ),
					      .CLR(a4l_a4wrData_fifof_CLR),
					      .D_OUT(a4l_a4wrData_fifof_D_OUT),
					      .FULL_N(a4l_a4wrData_fifof_FULL_N),
					      .EMPTY_N(a4l_a4wrData_fifof_EMPTY_N));

  // rule RL_a4l_cfrd
  assign CAN_FIRE_RL_a4l_cfrd =
	     a4l_a4rdResp_fifof_cntr_r != 2'd2 && a4l_a4rdAddr_fifof_EMPTY_N ;
  assign WILL_FIRE_RL_a4l_cfrd = CAN_FIRE_RL_a4l_cfrd ;

  // rule RL_a4l_cfwr
  assign CAN_FIRE_RL_a4l_cfwr =
	     a4l_a4wrResp_fifof_cntr_r != 2'd2 &&
	     a4l_a4wrAddr_fifof_EMPTY_N &&
	     a4l_a4wrData_fifof_EMPTY_N ;
  assign WILL_FIRE_RL_a4l_cfwr = CAN_FIRE_RL_a4l_cfwr ;

  // rule RL_inc_count
  assign CAN_FIRE_RL_inc_count = 1'd1 ;
  assign WILL_FIRE_RL_inc_count = 1'd1 ;

  // rule RL_a4ls_doAlways
  assign CAN_FIRE_RL_a4ls_doAlways = 1'd1 ;
  assign WILL_FIRE_RL_a4ls_doAlways = 1'd1 ;

  // rule RL_a4l_a4wrAddr_do_enq
  assign CAN_FIRE_RL_a4l_a4wrAddr_do_enq =
	     a4l_a4wrAddr_fifof_FULL_N && s_awvalid ;
  assign WILL_FIRE_RL_a4l_a4wrAddr_do_enq = CAN_FIRE_RL_a4l_a4wrAddr_do_enq ;

  // rule RL_a4l_a4wrData_do_enq
  assign CAN_FIRE_RL_a4l_a4wrData_do_enq =
	     a4l_a4wrData_fifof_FULL_N && s_wvalid ;
  assign WILL_FIRE_RL_a4l_a4wrData_do_enq = CAN_FIRE_RL_a4l_a4wrData_do_enq ;

  // rule RL_a4l_a4wrResp_do_deq
  assign CAN_FIRE_RL_a4l_a4wrResp_do_deq =
	     a4l_a4wrResp_fifof_cntr_r != 2'd0 && s_bready ;
  assign WILL_FIRE_RL_a4l_a4wrResp_do_deq = CAN_FIRE_RL_a4l_a4wrResp_do_deq ;

  // rule RL_a4l_a4wrResp_fifof_incCtr
  assign CAN_FIRE_RL_a4l_a4wrResp_fifof_incCtr =
	     CAN_FIRE_RL_a4l_cfwr && CAN_FIRE_RL_a4l_cfwr &&
	     !CAN_FIRE_RL_a4l_a4wrResp_do_deq ;
  assign WILL_FIRE_RL_a4l_a4wrResp_fifof_incCtr =
	     CAN_FIRE_RL_a4l_a4wrResp_fifof_incCtr ;

  // rule RL_a4l_a4wrResp_fifof_decCtr
  assign CAN_FIRE_RL_a4l_a4wrResp_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4wrResp_do_deq && !CAN_FIRE_RL_a4l_cfwr ;
  assign WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4wrResp_fifof_decCtr ;

  // rule RL_a4l_a4wrResp_fifof_both
  assign CAN_FIRE_RL_a4l_a4wrResp_fifof_both =
	     CAN_FIRE_RL_a4l_cfwr && CAN_FIRE_RL_a4l_a4wrResp_do_deq &&
	     CAN_FIRE_RL_a4l_cfwr ;
  assign WILL_FIRE_RL_a4l_a4wrResp_fifof_both =
	     CAN_FIRE_RL_a4l_a4wrResp_fifof_both ;

  // rule RL_a4l_a4rdAddr_do_enq
  assign CAN_FIRE_RL_a4l_a4rdAddr_do_enq =
	     a4l_a4rdAddr_fifof_FULL_N && s_arvalid ;
  assign WILL_FIRE_RL_a4l_a4rdAddr_do_enq = CAN_FIRE_RL_a4l_a4rdAddr_do_enq ;

  // rule RL_a4l_a4rdResp_do_deq
  assign CAN_FIRE_RL_a4l_a4rdResp_do_deq =
	     a4l_a4rdResp_fifof_cntr_r != 2'd0 && s_rready ;
  assign WILL_FIRE_RL_a4l_a4rdResp_do_deq = CAN_FIRE_RL_a4l_a4rdResp_do_deq ;

  // rule RL_a4l_a4rdResp_fifof_incCtr
  assign CAN_FIRE_RL_a4l_a4rdResp_fifof_incCtr =
	     CAN_FIRE_RL_a4l_cfrd && CAN_FIRE_RL_a4l_cfrd &&
	     !CAN_FIRE_RL_a4l_a4rdResp_do_deq ;
  assign WILL_FIRE_RL_a4l_a4rdResp_fifof_incCtr =
	     CAN_FIRE_RL_a4l_a4rdResp_fifof_incCtr ;

  // rule RL_a4l_a4rdResp_fifof_decCtr
  assign CAN_FIRE_RL_a4l_a4rdResp_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4rdResp_do_deq && !CAN_FIRE_RL_a4l_cfrd ;
  assign WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4rdResp_fifof_decCtr ;

  // rule RL_a4l_a4rdResp_fifof_both
  assign CAN_FIRE_RL_a4l_a4rdResp_fifof_both =
	     CAN_FIRE_RL_a4l_cfrd && CAN_FIRE_RL_a4l_a4rdResp_do_deq &&
	     CAN_FIRE_RL_a4l_cfrd ;
  assign WILL_FIRE_RL_a4l_a4rdResp_fifof_both =
	     CAN_FIRE_RL_a4l_a4rdResp_fifof_both ;

  // inputs to muxes for submodule ports
  assign MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_incCtr &&
	     a4l_a4rdResp_fifof_cntr_r == 2'd0 ;
  assign MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_both && _dfoo7 ;
  assign MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_incCtr &&
	     a4l_a4rdResp_fifof_cntr_r == 2'd1 ;
  assign MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_both && _dfoo5 ;
  assign MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_incCtr &&
	     a4l_a4wrResp_fifof_cntr_r == 2'd0 ;
  assign MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_both && _dfoo3 ;
  assign MUX_a4l_a4rdResp_fifof_cntr_r_write_1__VAL_2 =
	     a4l_a4rdResp_fifof_cntr_r + 2'd1 ;
  assign MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1 =
	     { 2'd0, _theResult____h4802 } ;
  assign MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_2 =
	     (a4l_a4rdResp_fifof_cntr_r == 2'd1) ?
	       MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1 :
	       a4l_a4rdResp_fifof_q_1 ;
  assign MUX_a4l_a4rdResp_fifof_q_1_write_1__VAL_2 =
	     (a4l_a4rdResp_fifof_cntr_r == 2'd2) ?
	       MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1 :
	       34'd0 ;
  assign MUX_a4l_a4wrResp_fifof_cntr_r_write_1__VAL_2 =
	     a4l_a4wrResp_fifof_cntr_r + 2'd1 ;
  assign MUX_a4l_a4wrResp_fifof_q_0_write_1__VAL_2 =
	     (a4l_a4wrResp_fifof_cntr_r == 2'd1) ?
	       2'd0 :
	       a4l_a4wrResp_fifof_q_1 ;

  // inlined wires
  assign a4l_a4wrAddr_data_wire_wget = { s_awprot, s_awaddr } ;
  assign a4l_a4wrData_data_wire_wget = { s_wstrb, s_wdata } ;
  assign a4l_a4rdAddr_data_wire_wget = { s_arprot, s_araddr } ;

  // register a4l_a4rdResp_fifof_cntr_r
  assign a4l_a4rdResp_fifof_cntr_r_D_IN =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr ?
	       a4l_a4rdResp_fifof_cntr_r_2_MINUS_1___d60 :
	       MUX_a4l_a4rdResp_fifof_cntr_r_write_1__VAL_2 ;
  assign a4l_a4rdResp_fifof_cntr_r_EN =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr ||
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_incCtr ;

  // register a4l_a4rdResp_fifof_q_0
  always@(MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_1 or
	  MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1 or
	  MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_2 or
	  MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_2 or
	  WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr or a4l_a4rdResp_fifof_q_1)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_1:
	  a4l_a4rdResp_fifof_q_0_D_IN =
	      MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1;
      MUX_a4l_a4rdResp_fifof_q_0_write_1__SEL_2:
	  a4l_a4rdResp_fifof_q_0_D_IN =
	      MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_2;
      WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr:
	  a4l_a4rdResp_fifof_q_0_D_IN = a4l_a4rdResp_fifof_q_1;
      default: a4l_a4rdResp_fifof_q_0_D_IN =
		   34'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4rdResp_fifof_q_0_EN =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_incCtr &&
	     a4l_a4rdResp_fifof_cntr_r == 2'd0 ||
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_both && _dfoo7 ||
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr ;

  // register a4l_a4rdResp_fifof_q_1
  always@(MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_1 or
	  MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1 or
	  MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_2 or
	  MUX_a4l_a4rdResp_fifof_q_1_write_1__VAL_2 or
	  WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_1:
	  a4l_a4rdResp_fifof_q_1_D_IN =
	      MUX_a4l_a4rdResp_fifof_q_0_write_1__VAL_1;
      MUX_a4l_a4rdResp_fifof_q_1_write_1__SEL_2:
	  a4l_a4rdResp_fifof_q_1_D_IN =
	      MUX_a4l_a4rdResp_fifof_q_1_write_1__VAL_2;
      WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr:
	  a4l_a4rdResp_fifof_q_1_D_IN = 34'd0;
      default: a4l_a4rdResp_fifof_q_1_D_IN =
		   34'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4rdResp_fifof_q_1_EN =
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_incCtr &&
	     a4l_a4rdResp_fifof_cntr_r == 2'd1 ||
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_both && _dfoo5 ||
	     WILL_FIRE_RL_a4l_a4rdResp_fifof_decCtr ;

  // register a4l_a4wrResp_fifof_cntr_r
  assign a4l_a4wrResp_fifof_cntr_r_D_IN =
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr ?
	       a4l_a4wrResp_fifof_cntr_r_9_MINUS_1___d27 :
	       MUX_a4l_a4wrResp_fifof_cntr_r_write_1__VAL_2 ;
  assign a4l_a4wrResp_fifof_cntr_r_EN =
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr ||
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_incCtr ;

  // register a4l_a4wrResp_fifof_q_0
  always@(MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_1 or
	  MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_2 or
	  MUX_a4l_a4wrResp_fifof_q_0_write_1__VAL_2 or
	  WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr or a4l_a4wrResp_fifof_q_1)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_1:
	  a4l_a4wrResp_fifof_q_0_D_IN = 2'd0;
      MUX_a4l_a4wrResp_fifof_q_0_write_1__SEL_2:
	  a4l_a4wrResp_fifof_q_0_D_IN =
	      MUX_a4l_a4wrResp_fifof_q_0_write_1__VAL_2;
      WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr:
	  a4l_a4wrResp_fifof_q_0_D_IN = a4l_a4wrResp_fifof_q_1;
      default: a4l_a4wrResp_fifof_q_0_D_IN = 2'b10 /* unspecified value */ ;
    endcase
  end
  assign a4l_a4wrResp_fifof_q_0_EN =
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_incCtr &&
	     a4l_a4wrResp_fifof_cntr_r == 2'd0 ||
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_both && _dfoo3 ||
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr ;

  // register a4l_a4wrResp_fifof_q_1
  assign a4l_a4wrResp_fifof_q_1_D_IN = 2'd0 ;
  assign a4l_a4wrResp_fifof_q_1_EN =
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_incCtr &&
	     a4l_a4wrResp_fifof_cntr_r == 2'd1 ||
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_both && _dfoo1 ||
	     WILL_FIRE_RL_a4l_a4wrResp_fifof_decCtr ;

  // register axiCount
  assign axiCount_D_IN = axiCount + 32'd1 ;
  assign axiCount_EN = 1'd1 ;

  // register axiRdCount
  assign axiRdCount_D_IN = axiRdCount + 32'd1 ;
  assign axiRdCount_EN = CAN_FIRE_RL_a4l_cfrd ;

  // register axiWtCount
  assign axiWtCount_D_IN = axiWtCount + 32'd1 ;
  assign axiWtCount_EN = CAN_FIRE_RL_a4l_cfwr ;

  // register b18
  assign b18_D_IN = a4l_a4wrData_fifof_D_OUT[7:0] ;
  assign b18_EN =
	     WILL_FIRE_RL_a4l_cfwr &&
	     a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h18 &&
	     a4l_a4wrData_fifof_D_OUT[32] ;

  // register b19
  assign b19_D_IN = a4l_a4wrData_fifof_D_OUT[15:8] ;
  assign b19_EN =
	     WILL_FIRE_RL_a4l_cfwr &&
	     a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h18 &&
	     a4l_a4wrData_fifof_D_OUT[33] ;

  // register b1A
  assign b1A_D_IN = a4l_a4wrData_fifof_D_OUT[23:16] ;
  assign b1A_EN =
	     WILL_FIRE_RL_a4l_cfwr &&
	     a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h18 &&
	     a4l_a4wrData_fifof_D_OUT[34] ;

  // register b1B
  assign b1B_D_IN = a4l_a4wrData_fifof_D_OUT[31:24] ;
  assign b1B_EN =
	     WILL_FIRE_RL_a4l_cfwr &&
	     a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h18 &&
	     a4l_a4wrData_fifof_D_OUT[35] ;

  // register lastReadAddr
  assign lastReadAddr_D_IN = a4l_a4rdAddr_fifof_D_OUT[31:0] ;
  assign lastReadAddr_EN = CAN_FIRE_RL_a4l_cfrd ;

  // register lastWriteAddr
  assign lastWriteAddr_D_IN = a4l_a4wrAddr_fifof_D_OUT[31:0] ;
  assign lastWriteAddr_EN = CAN_FIRE_RL_a4l_cfwr ;

  // register r0
  assign r0_D_IN = a4l_a4wrData_fifof_D_OUT[31:0] ;
  assign r0_EN =
	     WILL_FIRE_RL_a4l_cfwr && a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h0 ;

  // register r4
  assign r4_D_IN = a4l_a4wrData_fifof_D_OUT[31:0] ;
  assign r4_EN =
	     WILL_FIRE_RL_a4l_cfwr && a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h04 ;

  // register r40
  assign r40_D_IN = a4l_a4wrData_fifof_D_OUT[31:0] ;
  assign r40_EN =
	     WILL_FIRE_RL_a4l_cfwr && a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h40 ;

  // register r8
  assign r8_D_IN = a4l_a4wrData_fifof_D_OUT[31:0] ;
  assign r8_EN =
	     WILL_FIRE_RL_a4l_cfwr && a4l_a4wrAddr_fifof_D_OUT[7:0] == 8'h08 ;

  // submodule a4l_a4rdAddr_fifof
  assign a4l_a4rdAddr_fifof_D_IN = a4l_a4rdAddr_data_wire_wget ;
  assign a4l_a4rdAddr_fifof_ENQ = CAN_FIRE_RL_a4l_a4rdAddr_do_enq ;
  assign a4l_a4rdAddr_fifof_DEQ = CAN_FIRE_RL_a4l_cfrd ;
  assign a4l_a4rdAddr_fifof_CLR = 1'b0 ;

  // submodule a4l_a4wrAddr_fifof
  assign a4l_a4wrAddr_fifof_D_IN = a4l_a4wrAddr_data_wire_wget ;
  assign a4l_a4wrAddr_fifof_ENQ = CAN_FIRE_RL_a4l_a4wrAddr_do_enq ;
  assign a4l_a4wrAddr_fifof_DEQ = CAN_FIRE_RL_a4l_cfwr ;
  assign a4l_a4wrAddr_fifof_CLR = 1'b0 ;

  // submodule a4l_a4wrData_fifof
  assign a4l_a4wrData_fifof_D_IN = a4l_a4wrData_data_wire_wget ;
  assign a4l_a4wrData_fifof_ENQ = CAN_FIRE_RL_a4l_a4wrData_do_enq ;
  assign a4l_a4wrData_fifof_DEQ = CAN_FIRE_RL_a4l_cfwr ;
  assign a4l_a4wrData_fifof_CLR = 1'b0 ;

  // remaining internal signals
  assign _dfoo1 =
	     a4l_a4wrResp_fifof_cntr_r != 2'd2 ||
	     a4l_a4wrResp_fifof_cntr_r_9_MINUS_1___d27 == 2'd1 ;
  assign _dfoo3 =
	     a4l_a4wrResp_fifof_cntr_r != 2'd1 ||
	     a4l_a4wrResp_fifof_cntr_r_9_MINUS_1___d27 == 2'd0 ;
  assign _dfoo5 =
	     a4l_a4rdResp_fifof_cntr_r != 2'd2 ||
	     a4l_a4rdResp_fifof_cntr_r_2_MINUS_1___d60 == 2'd1 ;
  assign _dfoo7 =
	     a4l_a4rdResp_fifof_cntr_r != 2'd1 ||
	     a4l_a4rdResp_fifof_cntr_r_2_MINUS_1___d60 == 2'd0 ;
  assign a4l_a4rdResp_fifof_cntr_r_2_MINUS_1___d60 =
	     a4l_a4rdResp_fifof_cntr_r - 2'd1 ;
  assign a4l_a4wrResp_fifof_cntr_r_9_MINUS_1___d27 =
	     a4l_a4wrResp_fifof_cntr_r - 2'd1 ;
  assign rdat__h4967 = { b1B, b1A, b19, b18 } ;
  always@(a4l_a4rdAddr_fifof_D_OUT or
	  r40 or
	  r0 or
	  r4 or
	  r8 or
	  axiCount or
	  rdat__h4967 or
	  lastWriteAddr or lastReadAddr or axiWtCount or axiRdCount)
  begin
    case (a4l_a4rdAddr_fifof_D_OUT[7:0])
      8'h0: _theResult____h4802 = r0;
      8'h04: _theResult____h4802 = r4;
      8'h08: _theResult____h4802 = r8;
      8'h0C: _theResult____h4802 = axiCount;
      8'h10: _theResult____h4802 = 32'hF00DFACE;
      8'h14: _theResult____h4802 = 32'hFEEDC0DE;
      8'h18: _theResult____h4802 = rdat__h4967;
      8'h20: _theResult____h4802 = lastWriteAddr;
      8'h24: _theResult____h4802 = lastReadAddr;
      8'h28: _theResult____h4802 = axiWtCount;
      8'h2C: _theResult____h4802 = axiRdCount;
      default: _theResult____h4802 = r40;
    endcase
  end

  // handling of inlined registers

  always@(posedge s_axi_aclk)
  begin
    if (s_axi_aresetn == `BSV_RESET_VALUE)
      begin
        a4l_a4rdResp_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
	a4l_a4rdResp_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY 34'd0;
	a4l_a4rdResp_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY 34'd0;
	a4l_a4wrResp_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
	a4l_a4wrResp_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY 2'd0;
	a4l_a4wrResp_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY 2'd0;
	axiCount <= `BSV_ASSIGNMENT_DELAY 32'd0;
	axiRdCount <= `BSV_ASSIGNMENT_DELAY 32'd0;
	axiWtCount <= `BSV_ASSIGNMENT_DELAY 32'd0;
	b18 <= `BSV_ASSIGNMENT_DELAY 8'h18;
	b19 <= `BSV_ASSIGNMENT_DELAY 8'h19;
	b1A <= `BSV_ASSIGNMENT_DELAY 8'h1A;
	b1B <= `BSV_ASSIGNMENT_DELAY 8'h1B;
	lastReadAddr <= `BSV_ASSIGNMENT_DELAY 32'd0;
	lastWriteAddr <= `BSV_ASSIGNMENT_DELAY 32'd0;
	r0 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	r4 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	r40 <= `BSV_ASSIGNMENT_DELAY 32'd0;
	r8 <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (a4l_a4rdResp_fifof_cntr_r_EN)
	  a4l_a4rdResp_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4rdResp_fifof_cntr_r_D_IN;
	if (a4l_a4rdResp_fifof_q_0_EN)
	  a4l_a4rdResp_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4rdResp_fifof_q_0_D_IN;
	if (a4l_a4rdResp_fifof_q_1_EN)
	  a4l_a4rdResp_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4rdResp_fifof_q_1_D_IN;
	if (a4l_a4wrResp_fifof_cntr_r_EN)
	  a4l_a4wrResp_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrResp_fifof_cntr_r_D_IN;
	if (a4l_a4wrResp_fifof_q_0_EN)
	  a4l_a4wrResp_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrResp_fifof_q_0_D_IN;
	if (a4l_a4wrResp_fifof_q_1_EN)
	  a4l_a4wrResp_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrResp_fifof_q_1_D_IN;
	if (axiCount_EN) axiCount <= `BSV_ASSIGNMENT_DELAY axiCount_D_IN;
	if (axiRdCount_EN)
	  axiRdCount <= `BSV_ASSIGNMENT_DELAY axiRdCount_D_IN;
	if (axiWtCount_EN)
	  axiWtCount <= `BSV_ASSIGNMENT_DELAY axiWtCount_D_IN;
	if (b18_EN) b18 <= `BSV_ASSIGNMENT_DELAY b18_D_IN;
	if (b19_EN) b19 <= `BSV_ASSIGNMENT_DELAY b19_D_IN;
	if (b1A_EN) b1A <= `BSV_ASSIGNMENT_DELAY b1A_D_IN;
	if (b1B_EN) b1B <= `BSV_ASSIGNMENT_DELAY b1B_D_IN;
	if (lastReadAddr_EN)
	  lastReadAddr <= `BSV_ASSIGNMENT_DELAY lastReadAddr_D_IN;
	if (lastWriteAddr_EN)
	  lastWriteAddr <= `BSV_ASSIGNMENT_DELAY lastWriteAddr_D_IN;
	if (r0_EN) r0 <= `BSV_ASSIGNMENT_DELAY r0_D_IN;
	if (r4_EN) r4 <= `BSV_ASSIGNMENT_DELAY r4_D_IN;
	if (r40_EN) r40 <= `BSV_ASSIGNMENT_DELAY r40_D_IN;
	if (r8_EN) r8 <= `BSV_ASSIGNMENT_DELAY r8_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    a4l_a4rdResp_fifof_cntr_r = 2'h2;
    a4l_a4rdResp_fifof_q_0 = 34'h2AAAAAAAA;
    a4l_a4rdResp_fifof_q_1 = 34'h2AAAAAAAA;
    a4l_a4wrResp_fifof_cntr_r = 2'h2;
    a4l_a4wrResp_fifof_q_0 = 2'h2;
    a4l_a4wrResp_fifof_q_1 = 2'h2;
    axiCount = 32'hAAAAAAAA;
    axiRdCount = 32'hAAAAAAAA;
    axiWtCount = 32'hAAAAAAAA;
    b18 = 8'hAA;
    b19 = 8'hAA;
    b1A = 8'hAA;
    b1B = 8'hAA;
    lastReadAddr = 32'hAAAAAAAA;
    lastWriteAddr = 32'hAAAAAAAA;
    r0 = 32'hAAAAAAAA;
    r4 = 32'hAAAAAAAA;
    r40 = 32'hAAAAAAAA;
    r8 = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge s_axi_aclk)
  begin
    #0;
    if (s_axi_aresetn != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_a4l_cfrd)
	begin
	  v__h5039 = $time;
	  #0;
	end
    if (s_axi_aresetn != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_a4l_cfrd)
	$display("[%0d]: %m: AXI4-LITE CONFIG READ Addr:%0x",
		 v__h5039,
		 a4l_a4rdAddr_fifof_D_OUT[31:0]);
    if (s_axi_aresetn != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_a4l_cfrd)
	begin
	  v__h5071 = $time;
	  #0;
	end
    if (s_axi_aresetn != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_a4l_cfrd)
	$display("[%0d]: %m: AXI4-LITE CONFIG READ RESPOSNE Data:%0x",
		 v__h5071,
		 _theResult____h4802);
    if (s_axi_aresetn != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_a4l_cfwr)
	begin
	  v__h4704 = $time;
	  #0;
	end
    if (s_axi_aresetn != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_a4l_cfwr)
	$display("[%0d]: %m: AXI4-LITE CONFIG WRITE Addr:%0x BE:%0x Data:%0x",
		 v__h4704,
		 a4l_a4wrAddr_fifof_D_OUT[31:0],
		 a4l_a4wrData_fifof_D_OUT[35:32],
		 a4l_a4wrData_fifof_D_OUT[31:0]);
  end
  // synopsys translate_on
endmodule  // mkA4LSB

