//
// Generated by Bluespec Compiler, version 2013.01.beta5 (build 30325, 2013-01-23)
//
// On Tue Nov 26 08:43:16 EST 2013
//
// Method conflict info:
// Method: crtS0_request_put
// Conflict-free: crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: crtS0_request_put
//
// Method: crtS0_response_get
// Conflict-free: crtS0_request_put,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: crtS0_response_get
//
// Method: axiM0_wrAddr_data
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: axiM0_wrAddr_valid
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: axiM0_wrAddr_ready
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: axiM0_wrAddr_ready
//
// Method: axiM0_wrData_data
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: axiM0_wrData_valid
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: axiM0_wrData_ready
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: axiM0_wrData_ready
//
// Method: axiM0_wrResp_data
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: axiM0_wrResp_data
//
// Method: axiM0_wrResp_valid
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: axiM0_wrResp_valid
//
// Method: axiM0_wrResp_ready
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: axiM0_rdAddr_data
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: axiM0_rdAddr_valid
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: axiM0_rdAddr_ready
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: axiM0_rdAddr_ready
//
// Method: axiM0_rdResp_data
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: axiM0_rdResp_data
//
// Method: axiM0_rdResp_valid
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
// Conflicts: axiM0_rdResp_valid
//
// Method: axiM0_rdResp_ready
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: isActive
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
// Method: isFaulted
// Conflict-free: crtS0_request_put,
// 	       crtS0_response_get,
// 	       axiM0_wrAddr_data,
// 	       axiM0_wrAddr_valid,
// 	       axiM0_wrAddr_ready,
// 	       axiM0_wrData_data,
// 	       axiM0_wrData_valid,
// 	       axiM0_wrData_ready,
// 	       axiM0_wrResp_data,
// 	       axiM0_wrResp_valid,
// 	       axiM0_wrResp_ready,
// 	       axiM0_rdAddr_data,
// 	       axiM0_rdAddr_valid,
// 	       axiM0_rdAddr_ready,
// 	       axiM0_rdResp_data,
// 	       axiM0_rdResp_valid,
// 	       axiM0_rdResp_ready,
// 	       isActive,
// 	       isFaulted
//
//
// Ports:
// Name                         I/O  size props
// RDY_crtS0_request_put          O     1 reg
// crtS0_response_get             O    40
// RDY_crtS0_response_get         O     1 reg
// axiM0_wrAddr_data              O    35 reg
// axiM0_wrAddr_valid             O     1
// axiM0_wrData_data              O    36 reg
// axiM0_wrData_valid             O     1
// axiM0_wrResp_ready             O     1 reg
// axiM0_rdAddr_data              O    35 reg
// axiM0_rdAddr_valid             O     1
// axiM0_rdResp_ready             O     1 reg
// isActive                       O     1 reg
// isFaulted                      O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// crtS0_request_put              I    32 reg
// axiM0_wrAddr_ready_value       I     1
// axiM0_wrData_ready_value       I     1
// axiM0_wrResp_data_value        I     2 reg
// axiM0_wrResp_valid_value       I     1
// axiM0_rdAddr_ready_value       I     1
// axiM0_rdResp_data_value        I    34 reg
// axiM0_rdResp_valid_value       I     1
// EN_crtS0_request_put           I     1
// EN_crtS0_response_get          I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkHCrtCompleter2Axi(CLK,
			   RST_N,

			   crtS0_request_put,
			   EN_crtS0_request_put,
			   RDY_crtS0_request_put,

			   EN_crtS0_response_get,
			   crtS0_response_get,
			   RDY_crtS0_response_get,

			   axiM0_wrAddr_data,

			   axiM0_wrAddr_valid,

			   axiM0_wrAddr_ready_value,

			   axiM0_wrData_data,

			   axiM0_wrData_valid,

			   axiM0_wrData_ready_value,

			   axiM0_wrResp_data_value,

			   axiM0_wrResp_valid_value,

			   axiM0_wrResp_ready,

			   axiM0_rdAddr_data,

			   axiM0_rdAddr_valid,

			   axiM0_rdAddr_ready_value,

			   axiM0_rdResp_data_value,

			   axiM0_rdResp_valid_value,

			   axiM0_rdResp_ready,

			   isActive,

			   isFaulted);
  input  CLK;
  input  RST_N;

  // action method crtS0_request_put
  input  [31 : 0] crtS0_request_put;
  input  EN_crtS0_request_put;
  output RDY_crtS0_request_put;

  // actionvalue method crtS0_response_get
  input  EN_crtS0_response_get;
  output [39 : 0] crtS0_response_get;
  output RDY_crtS0_response_get;

  // value method axiM0_wrAddr_data
  output [34 : 0] axiM0_wrAddr_data;

  // value method axiM0_wrAddr_valid
  output axiM0_wrAddr_valid;

  // action method axiM0_wrAddr_ready
  input  axiM0_wrAddr_ready_value;

  // value method axiM0_wrData_data
  output [35 : 0] axiM0_wrData_data;

  // value method axiM0_wrData_valid
  output axiM0_wrData_valid;

  // action method axiM0_wrData_ready
  input  axiM0_wrData_ready_value;

  // action method axiM0_wrResp_data
  input  [1 : 0] axiM0_wrResp_data_value;

  // action method axiM0_wrResp_valid
  input  axiM0_wrResp_valid_value;

  // value method axiM0_wrResp_ready
  output axiM0_wrResp_ready;

  // value method axiM0_rdAddr_data
  output [34 : 0] axiM0_rdAddr_data;

  // value method axiM0_rdAddr_valid
  output axiM0_rdAddr_valid;

  // action method axiM0_rdAddr_ready
  input  axiM0_rdAddr_ready_value;

  // action method axiM0_rdResp_data
  input  [33 : 0] axiM0_rdResp_data_value;

  // action method axiM0_rdResp_valid
  input  axiM0_rdResp_valid_value;

  // value method axiM0_rdResp_ready
  output axiM0_rdResp_ready;

  // value method isActive
  output isActive;

  // value method isFaulted
  output isFaulted;

  // signals for module outputs
  wire [39 : 0] crtS0_response_get;
  wire [35 : 0] axiM0_wrData_data;
  wire [34 : 0] axiM0_rdAddr_data, axiM0_wrAddr_data;
  wire RDY_crtS0_request_put,
       RDY_crtS0_response_get,
       axiM0_rdAddr_valid,
       axiM0_rdResp_ready,
       axiM0_wrAddr_valid,
       axiM0_wrData_valid,
       axiM0_wrResp_ready,
       isActive,
       isFaulted;

  // inlined wires
  wire [39 : 0] respBufF_wDataIn_wget, respBufF_wDataOut_wget;
  wire a4l_a4wrAddr_fifof_enqueueing_whas,
       modActive_1_whas,
       modFaulted_1_whas;

  // register a4l_a4rdAddr_fifof_cntr_r
  reg [1 : 0] a4l_a4rdAddr_fifof_cntr_r;
  wire [1 : 0] a4l_a4rdAddr_fifof_cntr_r_D_IN;
  wire a4l_a4rdAddr_fifof_cntr_r_EN;

  // register a4l_a4rdAddr_fifof_q_0
  reg [34 : 0] a4l_a4rdAddr_fifof_q_0;
  reg [34 : 0] a4l_a4rdAddr_fifof_q_0_D_IN;
  wire a4l_a4rdAddr_fifof_q_0_EN;

  // register a4l_a4rdAddr_fifof_q_1
  reg [34 : 0] a4l_a4rdAddr_fifof_q_1;
  reg [34 : 0] a4l_a4rdAddr_fifof_q_1_D_IN;
  wire a4l_a4rdAddr_fifof_q_1_EN;

  // register a4l_a4wrAddr_fifof_cntr_r
  reg [1 : 0] a4l_a4wrAddr_fifof_cntr_r;
  wire [1 : 0] a4l_a4wrAddr_fifof_cntr_r_D_IN;
  wire a4l_a4wrAddr_fifof_cntr_r_EN;

  // register a4l_a4wrAddr_fifof_q_0
  reg [34 : 0] a4l_a4wrAddr_fifof_q_0;
  reg [34 : 0] a4l_a4wrAddr_fifof_q_0_D_IN;
  wire a4l_a4wrAddr_fifof_q_0_EN;

  // register a4l_a4wrAddr_fifof_q_1
  reg [34 : 0] a4l_a4wrAddr_fifof_q_1;
  reg [34 : 0] a4l_a4wrAddr_fifof_q_1_D_IN;
  wire a4l_a4wrAddr_fifof_q_1_EN;

  // register a4l_a4wrData_fifof_cntr_r
  reg [1 : 0] a4l_a4wrData_fifof_cntr_r;
  wire [1 : 0] a4l_a4wrData_fifof_cntr_r_D_IN;
  wire a4l_a4wrData_fifof_cntr_r_EN;

  // register a4l_a4wrData_fifof_q_0
  reg [35 : 0] a4l_a4wrData_fifof_q_0;
  reg [35 : 0] a4l_a4wrData_fifof_q_0_D_IN;
  wire a4l_a4wrData_fifof_q_0_EN;

  // register a4l_a4wrData_fifof_q_1
  reg [35 : 0] a4l_a4wrData_fifof_q_1;
  reg [35 : 0] a4l_a4wrData_fifof_q_1_D_IN;
  wire a4l_a4wrData_fifof_q_1_EN;

  // register addrAccu
  reg [65 : 0] addrAccu;
  wire [65 : 0] addrAccu_D_IN;
  wire addrAccu_EN;

  // register addrCaptCnt
  reg [1 : 0] addrCaptCnt;
  wire [1 : 0] addrCaptCnt_D_IN;
  wire addrCaptCnt_EN;

  // register addrCaptOK
  reg addrCaptOK;
  wire addrCaptOK_D_IN, addrCaptOK_EN;

  // register addrTmp
  reg [31 : 0] addrTmp;
  wire [31 : 0] addrTmp_D_IN;
  wire addrTmp_EN;

  // register cmdAddrAccu
  reg [31 : 0] cmdAddrAccu;
  wire [31 : 0] cmdAddrAccu_D_IN;
  wire cmdAddrAccu_EN;

  // register cmdAdlRemain
  reg [11 : 0] cmdAdlRemain;
  wire [11 : 0] cmdAdlRemain_D_IN;
  wire cmdAdlRemain_EN;

  // register cmdCRH
  reg [34 : 0] cmdCRH;
  wire [34 : 0] cmdCRH_D_IN;
  wire cmdCRH_EN;

  // register cmdIsAM64
  reg cmdIsAM64;
  wire cmdIsAM64_D_IN, cmdIsAM64_EN;

  // register cmdIsDO
  reg cmdIsDO;
  reg cmdIsDO_D_IN;
  wire cmdIsDO_EN;

  // register cmdIsLast
  reg cmdIsLast;
  wire cmdIsLast_D_IN, cmdIsLast_EN;

  // register cmdIsRW
  reg cmdIsRW;
  wire cmdIsRW_D_IN, cmdIsRW_EN;

  // register cmdRdHead
  reg cmdRdHead;
  wire cmdRdHead_D_IN, cmdRdHead_EN;

  // register crtBusy
  reg crtBusy;
  wire crtBusy_D_IN, crtBusy_EN;

  // register lastTag
  reg [4 : 0] lastTag;
  wire [4 : 0] lastTag_D_IN;
  wire lastTag_EN;

  // register lclRspRemain
  reg [11 : 0] lclRspRemain;
  wire [11 : 0] lclRspRemain_D_IN;
  wire lclRspRemain_EN;

  // register modActive
  reg modActive;
  wire modActive_D_IN, modActive_EN;

  // register modFaulted
  reg modFaulted;
  wire modFaulted_D_IN, modFaulted_EN;

  // register respBufCnt
  reg [11 : 0] respBufCnt;
  wire [11 : 0] respBufCnt_D_IN;
  wire respBufCnt_EN;

  // register respBufF_rCache
  reg [52 : 0] respBufF_rCache;
  wire [52 : 0] respBufF_rCache_D_IN;
  wire respBufF_rCache_EN;

  // register respBufF_rRdPtr
  reg [11 : 0] respBufF_rRdPtr;
  wire [11 : 0] respBufF_rRdPtr_D_IN;
  wire respBufF_rRdPtr_EN;

  // register respBufF_rWrPtr
  reg [11 : 0] respBufF_rWrPtr;
  wire [11 : 0] respBufF_rWrPtr_D_IN;
  wire respBufF_rWrPtr_EN;

  // register respBufTrig
  reg respBufTrig;
  wire respBufTrig_D_IN, respBufTrig_EN;

  // register rspActive
  reg rspActive;
  wire rspActive_D_IN, rspActive_EN;

  // register rspAdlRemain
  reg [11 : 0] rspAdlRemain;
  wire [11 : 0] rspAdlRemain_D_IN;
  wire rspAdlRemain_EN;

  // register rspCRH
  reg [34 : 0] rspCRH;
  reg [34 : 0] rspCRH_D_IN;
  wire rspCRH_EN;

  // register sizInitRespB
  reg [31 : 0] sizInitRespB;
  wire [31 : 0] sizInitRespB_D_IN;
  wire sizInitRespB_EN;

  // ports of submodule a4l_a4rdResp_fifof
  wire [33 : 0] a4l_a4rdResp_fifof_D_IN, a4l_a4rdResp_fifof_D_OUT;
  wire a4l_a4rdResp_fifof_CLR,
       a4l_a4rdResp_fifof_DEQ,
       a4l_a4rdResp_fifof_EMPTY_N,
       a4l_a4rdResp_fifof_ENQ,
       a4l_a4rdResp_fifof_FULL_N;

  // ports of submodule a4l_a4wrResp_fifof
  wire [1 : 0] a4l_a4wrResp_fifof_D_IN;
  wire a4l_a4wrResp_fifof_CLR,
       a4l_a4wrResp_fifof_DEQ,
       a4l_a4wrResp_fifof_EMPTY_N,
       a4l_a4wrResp_fifof_ENQ,
       a4l_a4wrResp_fifof_FULL_N;

  // ports of submodule crtCmdF
  wire [31 : 0] crtCmdF_D_IN, crtCmdF_D_OUT;
  wire crtCmdF_CLR, crtCmdF_DEQ, crtCmdF_EMPTY_N, crtCmdF_ENQ, crtCmdF_FULL_N;

  // ports of submodule crtRespF
  reg [39 : 0] crtRespF_D_IN;
  wire [39 : 0] crtRespF_D_OUT;
  wire crtRespF_CLR,
       crtRespF_DEQ,
       crtRespF_EMPTY_N,
       crtRespF_ENQ,
       crtRespF_FULL_N;

  // ports of submodule respBufF_memory
  wire [39 : 0] respBufF_memory_DIA, respBufF_memory_DIB, respBufF_memory_DOB;
  wire [10 : 0] respBufF_memory_ADDRA, respBufF_memory_ADDRB;
  wire respBufF_memory_ENA,
       respBufF_memory_ENB,
       respBufF_memory_WEA,
       respBufF_memory_WEB;

  // rule scheduling signals
  wire CAN_FIRE_RL_a4l_a4rdAddr_do_deq,
       CAN_FIRE_RL_a4l_a4rdAddr_fifof_both,
       CAN_FIRE_RL_a4l_a4rdAddr_fifof_decCtr,
       CAN_FIRE_RL_a4l_a4rdAddr_fifof_incCtr,
       CAN_FIRE_RL_a4l_a4rdResp_do_enq,
       CAN_FIRE_RL_a4l_a4wrAddr_do_deq,
       CAN_FIRE_RL_a4l_a4wrAddr_fifof_both,
       CAN_FIRE_RL_a4l_a4wrAddr_fifof_decCtr,
       CAN_FIRE_RL_a4l_a4wrAddr_fifof_incCtr,
       CAN_FIRE_RL_a4l_a4wrData_do_deq,
       CAN_FIRE_RL_a4l_a4wrData_fifof_both,
       CAN_FIRE_RL_a4l_a4wrData_fifof_decCtr,
       CAN_FIRE_RL_a4l_a4wrData_fifof_incCtr,
       CAN_FIRE_RL_a4l_a4wrResp_do_enq,
       CAN_FIRE_RL_agg_write,
       CAN_FIRE_RL_cmd_addr,
       CAN_FIRE_RL_cmd_crh,
       CAN_FIRE_RL_cmd_nop,
       CAN_FIRE_RL_cmd_read,
       CAN_FIRE_RL_cmd_write,
       CAN_FIRE_RL_drain_rsp_read,
       CAN_FIRE_RL_modActive__dreg_update,
       CAN_FIRE_RL_modFaulted__dreg_update,
       CAN_FIRE_RL_respBufF_portA,
       CAN_FIRE_RL_respBufF_portB,
       CAN_FIRE_RL_respBufF_portB_read_data,
       CAN_FIRE_RL_rsp_nop,
       CAN_FIRE_RL_rsp_read,
       CAN_FIRE_RL_rsp_write,
       CAN_FIRE_axiM0_rdAddr_ready,
       CAN_FIRE_axiM0_rdResp_data,
       CAN_FIRE_axiM0_rdResp_valid,
       CAN_FIRE_axiM0_wrAddr_ready,
       CAN_FIRE_axiM0_wrData_ready,
       CAN_FIRE_axiM0_wrResp_data,
       CAN_FIRE_axiM0_wrResp_valid,
       CAN_FIRE_crtS0_request_put,
       CAN_FIRE_crtS0_response_get,
       WILL_FIRE_RL_a4l_a4rdAddr_do_deq,
       WILL_FIRE_RL_a4l_a4rdAddr_fifof_both,
       WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr,
       WILL_FIRE_RL_a4l_a4rdAddr_fifof_incCtr,
       WILL_FIRE_RL_a4l_a4rdResp_do_enq,
       WILL_FIRE_RL_a4l_a4wrAddr_do_deq,
       WILL_FIRE_RL_a4l_a4wrAddr_fifof_both,
       WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr,
       WILL_FIRE_RL_a4l_a4wrAddr_fifof_incCtr,
       WILL_FIRE_RL_a4l_a4wrData_do_deq,
       WILL_FIRE_RL_a4l_a4wrData_fifof_both,
       WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr,
       WILL_FIRE_RL_a4l_a4wrData_fifof_incCtr,
       WILL_FIRE_RL_a4l_a4wrResp_do_enq,
       WILL_FIRE_RL_agg_write,
       WILL_FIRE_RL_cmd_addr,
       WILL_FIRE_RL_cmd_crh,
       WILL_FIRE_RL_cmd_nop,
       WILL_FIRE_RL_cmd_read,
       WILL_FIRE_RL_cmd_write,
       WILL_FIRE_RL_drain_rsp_read,
       WILL_FIRE_RL_modActive__dreg_update,
       WILL_FIRE_RL_modFaulted__dreg_update,
       WILL_FIRE_RL_respBufF_portA,
       WILL_FIRE_RL_respBufF_portB,
       WILL_FIRE_RL_respBufF_portB_read_data,
       WILL_FIRE_RL_rsp_nop,
       WILL_FIRE_RL_rsp_read,
       WILL_FIRE_RL_rsp_write,
       WILL_FIRE_axiM0_rdAddr_ready,
       WILL_FIRE_axiM0_rdResp_data,
       WILL_FIRE_axiM0_rdResp_valid,
       WILL_FIRE_axiM0_wrAddr_ready,
       WILL_FIRE_axiM0_wrData_ready,
       WILL_FIRE_axiM0_wrResp_data,
       WILL_FIRE_axiM0_wrResp_valid,
       WILL_FIRE_crtS0_request_put,
       WILL_FIRE_crtS0_response_get;

  // inputs to muxes for submodule ports
  wire [65 : 0] MUX_addrAccu_write_1__VAL_1, MUX_addrAccu_write_1__VAL_2;
  wire [39 : 0] MUX_crtRespF_enq_1__VAL_1,
		MUX_crtRespF_enq_1__VAL_2,
		MUX_crtRespF_enq_1__VAL_3;
  wire [35 : 0] MUX_a4l_a4wrData_fifof_q_0_write_1__VAL_1,
		MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_1,
		MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2;
  wire [34 : 0] MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1,
		MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_2,
		MUX_a4l_a4rdAddr_fifof_q_1_write_1__VAL_2,
		MUX_a4l_a4wrAddr_fifof_q_0_write_1__VAL_1,
		MUX_a4l_a4wrAddr_fifof_q_1_write_1__VAL_1,
		MUX_cmdCRH_write_1__VAL_1,
		MUX_rspCRH_write_1__VAL_1,
		MUX_rspCRH_write_1__VAL_2,
		MUX_rspCRH_write_1__VAL_6;
  wire [11 : 0] MUX_cmdAdlRemain_write_1__VAL_2,
		MUX_lclRspRemain_write_1__VAL_2,
		MUX_respBufCnt_write_1__VAL_1,
		MUX_respBufCnt_write_1__VAL_2;
  wire [4 : 0] MUX_lastTag_write_1__VAL_2;
  wire [1 : 0] MUX_a4l_a4rdAddr_fifof_cntr_r_write_1__VAL_2,
	       MUX_a4l_a4wrAddr_fifof_cntr_r_write_1__VAL_2,
	       MUX_a4l_a4wrData_fifof_cntr_r_write_1__VAL_2,
	       MUX_addrCaptCnt_write_1__VAL_2;
  wire MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_1,
       MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_2,
       MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_1,
       MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_2,
       MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_1,
       MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_2,
       MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_1,
       MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_2,
       MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_1,
       MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_2,
       MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_1,
       MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_2,
       MUX_addrAccu_write_1__SEL_1,
       MUX_addrCaptCnt_write_1__SEL_1,
       MUX_cmdAdlRemain_write_1__SEL_1,
       MUX_cmdIsDO_write_1__SEL_1,
       MUX_cmdIsDO_write_1__SEL_2,
       MUX_cmdIsDO_write_1__SEL_3,
       MUX_cmdIsDO_write_1__SEL_5,
       MUX_cmdIsDO_write_1__SEL_6,
       MUX_cmdIsLast_write_1__PSEL_2,
       MUX_crtBusy_write_1__SEL_2,
       MUX_lastTag_write_1__SEL_1,
       MUX_lclRspRemain_write_1__SEL_1,
       MUX_rspCRH_write_1__SEL_1,
       MUX_rspCRH_write_1__SEL_6;

  // remaining internal signals
  reg [63 : 0] v__h14415,
	       v__h14567,
	       v__h16705,
	       v__h16970,
	       v__h18028,
	       v__h18577,
	       v__h18635,
	       v__h20032;
  reg [3 : 0] IF_rspCRH_18_BITS_11_TO_8_77_EQ_0_78_OR_rspCRH_ETC___d383;
  reg [2 : 0] CASE_crtCmdFD_OUT_BITS_5_TO_4_0_0_1_1_2__q5;
  reg [1 : 0] CASE_crtRespFD_OUT_BITS_19_TO_18_0_crtRespFD_ETC__q3,
	      CASE_crtRespFD_OUT_BITS_29_TO_28_0_crtRespFD_ETC__q2,
	      CASE_crtRespFD_OUT_BITS_39_TO_38_0_crtRespFD_ETC__q1,
	      CASE_crtRespFD_OUT_BITS_9_TO_8_0_crtRespFD_O_ETC__q4,
	      CASE_respBufF_memoryDOB_BITS_19_TO_18_0_respB_ETC__q12,
	      CASE_respBufF_memoryDOB_BITS_29_TO_28_0_respB_ETC__q11,
	      CASE_respBufF_memoryDOB_BITS_39_TO_38_0_respB_ETC__q10,
	      CASE_respBufF_memoryDOB_BITS_9_TO_8_0_respBuf_ETC__q13,
	      CASE_respBufF_rCache_BITS_19_TO_18_0_respBufF__ETC__q8,
	      CASE_respBufF_rCache_BITS_29_TO_28_0_respBufF__ETC__q7,
	      CASE_respBufF_rCache_BITS_39_TO_38_0_respBufF__ETC__q6,
	      CASE_respBufF_rCache_BITS_9_TO_8_0_respBufF_rC_ETC__q9,
	      CASE_respBufF_wDataInwget_BITS_19_TO_18_1_res_ETC__q20,
	      CASE_respBufF_wDataInwget_BITS_29_TO_28_1_res_ETC__q19,
	      CASE_respBufF_wDataInwget_BITS_39_TO_38_1_res_ETC__q18,
	      CASE_respBufF_wDataInwget_BITS_9_TO_8_1_respB_ETC__q21,
	      CASE_respBufF_wDataOutwget_BITS_19_TO_18_0_re_ETC__q16,
	      CASE_respBufF_wDataOutwget_BITS_29_TO_28_0_re_ETC__q15,
	      CASE_respBufF_wDataOutwget_BITS_39_TO_38_0_re_ETC__q14,
	      CASE_respBufF_wDataOutwget_BITS_9_TO_8_0_resp_ETC__q17;
  wire [31 : 0] IF_rspActive_65_THEN_IF_rspAdlRemain_62_EQ_2_7_ETC___d386,
		advert__h14551,
		data__h19060;
  wire [11 : 0] x__h7924, x__h9042;
  wire [9 : 0] IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d123,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d136,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d150,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d163;
  wire [1 : 0] IF_NOT_rspActive_65_73_OR_NOT_rspAdlRemain_62__ETC___d375,
	       a4l_a4rdAddr_fifof_cntr_r_7_MINUS_1___d75,
	       a4l_a4wrAddr_fifof_cntr_r_MINUS_1___d15,
	       a4l_a4wrData_fifof_cntr_r_4_MINUS_1___d42;
  wire NOT_respBufF_rRdPtr_read__72_PLUS_1025_69_EQ_r_ETC___d476,
       _dand2lastTag_EN_write,
       _dfoo1,
       _dfoo11,
       _dfoo3,
       _dfoo5,
       _dfoo7,
       _dfoo9,
       cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415,
       cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d420;

  // action method crtS0_request_put
  assign RDY_crtS0_request_put = crtCmdF_FULL_N ;
  assign CAN_FIRE_crtS0_request_put = crtCmdF_FULL_N ;
  assign WILL_FIRE_crtS0_request_put = EN_crtS0_request_put ;

  // actionvalue method crtS0_response_get
  assign crtS0_response_get =
	     { CASE_crtRespFD_OUT_BITS_39_TO_38_0_crtRespFD_ETC__q1,
	       crtRespF_D_OUT[37:30],
	       CASE_crtRespFD_OUT_BITS_29_TO_28_0_crtRespFD_ETC__q2,
	       crtRespF_D_OUT[27:20],
	       CASE_crtRespFD_OUT_BITS_19_TO_18_0_crtRespFD_ETC__q3,
	       crtRespF_D_OUT[17:10],
	       CASE_crtRespFD_OUT_BITS_9_TO_8_0_crtRespFD_O_ETC__q4,
	       crtRespF_D_OUT[7:0] } ;
  assign RDY_crtS0_response_get = crtRespF_EMPTY_N ;
  assign CAN_FIRE_crtS0_response_get = crtRespF_EMPTY_N ;
  assign WILL_FIRE_crtS0_response_get = EN_crtS0_response_get ;

  // value method axiM0_wrAddr_data
  assign axiM0_wrAddr_data = a4l_a4wrAddr_fifof_q_0 ;

  // value method axiM0_wrAddr_valid
  assign axiM0_wrAddr_valid = a4l_a4wrAddr_fifof_cntr_r != 2'd0 ;

  // action method axiM0_wrAddr_ready
  assign CAN_FIRE_axiM0_wrAddr_ready = 1'd1 ;
  assign WILL_FIRE_axiM0_wrAddr_ready = 1'd1 ;

  // value method axiM0_wrData_data
  assign axiM0_wrData_data = a4l_a4wrData_fifof_q_0 ;

  // value method axiM0_wrData_valid
  assign axiM0_wrData_valid = a4l_a4wrData_fifof_cntr_r != 2'd0 ;

  // action method axiM0_wrData_ready
  assign CAN_FIRE_axiM0_wrData_ready = 1'd1 ;
  assign WILL_FIRE_axiM0_wrData_ready = 1'd1 ;

  // action method axiM0_wrResp_data
  assign CAN_FIRE_axiM0_wrResp_data = 1'd1 ;
  assign WILL_FIRE_axiM0_wrResp_data = 1'd1 ;

  // action method axiM0_wrResp_valid
  assign CAN_FIRE_axiM0_wrResp_valid = 1'd1 ;
  assign WILL_FIRE_axiM0_wrResp_valid = 1'd1 ;

  // value method axiM0_wrResp_ready
  assign axiM0_wrResp_ready = a4l_a4wrResp_fifof_FULL_N ;

  // value method axiM0_rdAddr_data
  assign axiM0_rdAddr_data = a4l_a4rdAddr_fifof_q_0 ;

  // value method axiM0_rdAddr_valid
  assign axiM0_rdAddr_valid = a4l_a4rdAddr_fifof_cntr_r != 2'd0 ;

  // action method axiM0_rdAddr_ready
  assign CAN_FIRE_axiM0_rdAddr_ready = 1'd1 ;
  assign WILL_FIRE_axiM0_rdAddr_ready = 1'd1 ;

  // action method axiM0_rdResp_data
  assign CAN_FIRE_axiM0_rdResp_data = 1'd1 ;
  assign WILL_FIRE_axiM0_rdResp_data = 1'd1 ;

  // action method axiM0_rdResp_valid
  assign CAN_FIRE_axiM0_rdResp_valid = 1'd1 ;
  assign WILL_FIRE_axiM0_rdResp_valid = 1'd1 ;

  // value method axiM0_rdResp_ready
  assign axiM0_rdResp_ready = a4l_a4rdResp_fifof_FULL_N ;

  // value method isActive
  assign isActive = modActive ;

  // value method isFaulted
  assign isFaulted = modFaulted ;

  // submodule a4l_a4rdResp_fifof
  FIFO2 #(.width(32'd34), .guarded(32'd1)) a4l_a4rdResp_fifof(.RST(RST_N),
							      .CLK(CLK),
							      .D_IN(a4l_a4rdResp_fifof_D_IN),
							      .ENQ(a4l_a4rdResp_fifof_ENQ),
							      .DEQ(a4l_a4rdResp_fifof_DEQ),
							      .CLR(a4l_a4rdResp_fifof_CLR),
							      .D_OUT(a4l_a4rdResp_fifof_D_OUT),
							      .FULL_N(a4l_a4rdResp_fifof_FULL_N),
							      .EMPTY_N(a4l_a4rdResp_fifof_EMPTY_N));

  // submodule a4l_a4wrResp_fifof
  FIFO2 #(.width(32'd2), .guarded(32'd1)) a4l_a4wrResp_fifof(.RST(RST_N),
							     .CLK(CLK),
							     .D_IN(a4l_a4wrResp_fifof_D_IN),
							     .ENQ(a4l_a4wrResp_fifof_ENQ),
							     .DEQ(a4l_a4wrResp_fifof_DEQ),
							     .CLR(a4l_a4wrResp_fifof_CLR),
							     .D_OUT(),
							     .FULL_N(a4l_a4wrResp_fifof_FULL_N),
							     .EMPTY_N(a4l_a4wrResp_fifof_EMPTY_N));

  // submodule crtCmdF
  FIFO2 #(.width(32'd32), .guarded(32'd1)) crtCmdF(.RST(RST_N),
						   .CLK(CLK),
						   .D_IN(crtCmdF_D_IN),
						   .ENQ(crtCmdF_ENQ),
						   .DEQ(crtCmdF_DEQ),
						   .CLR(crtCmdF_CLR),
						   .D_OUT(crtCmdF_D_OUT),
						   .FULL_N(crtCmdF_FULL_N),
						   .EMPTY_N(crtCmdF_EMPTY_N));

  // submodule crtRespF
  FIFO2 #(.width(32'd40), .guarded(32'd1)) crtRespF(.RST(RST_N),
						    .CLK(CLK),
						    .D_IN(crtRespF_D_IN),
						    .ENQ(crtRespF_ENQ),
						    .DEQ(crtRespF_DEQ),
						    .CLR(crtRespF_CLR),
						    .D_OUT(crtRespF_D_OUT),
						    .FULL_N(crtRespF_FULL_N),
						    .EMPTY_N(crtRespF_EMPTY_N));

  // submodule respBufF_memory
  BRAM2 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd11),
	  .DATA_WIDTH(32'd40),
	  .MEMSIZE(12'd2048)) respBufF_memory(.CLKA(CLK),
					      .CLKB(CLK),
					      .ADDRA(respBufF_memory_ADDRA),
					      .ADDRB(respBufF_memory_ADDRB),
					      .DIA(respBufF_memory_DIA),
					      .DIB(respBufF_memory_DIB),
					      .WEA(respBufF_memory_WEA),
					      .WEB(respBufF_memory_WEB),
					      .ENA(respBufF_memory_ENA),
					      .ENB(respBufF_memory_ENB),
					      .DOA(),
					      .DOB(respBufF_memory_DOB));

  // rule RL_cmd_crh
  assign CAN_FIRE_RL_cmd_crh =
	     crtCmdF_EMPTY_N && cmdCRH[34:32] != 3'd0 &&
	     cmdCRH[34:32] != 3'd1 &&
	     cmdCRH[34:32] != 3'd2 &&
	     cmdCRH[34:32] != 3'd3 &&
	     cmdCRH[34:32] != 3'd4 &&
	     cmdCRH[34:32] != 3'd5 &&
	     !crtBusy ;
  assign WILL_FIRE_RL_cmd_crh = CAN_FIRE_RL_cmd_crh ;

  // rule RL_cmd_nop
  assign CAN_FIRE_RL_cmd_nop =
	     crtCmdF_EMPTY_N && cmdCRH[34:32] == 3'd0 &&
	     rspCRH[34:32] != 3'd0 &&
	     rspCRH[34:32] != 3'd1 &&
	     rspCRH[34:32] != 3'd2 &&
	     rspCRH[34:32] != 3'd3 &&
	     rspCRH[34:32] != 3'd4 &&
	     rspCRH[34:32] != 3'd5 &&
	     !cmdIsRW ;
  assign WILL_FIRE_RL_cmd_nop = CAN_FIRE_RL_cmd_nop ;

  // rule RL_cmd_addr
  assign CAN_FIRE_RL_cmd_addr =
	     crtCmdF_EMPTY_N && addrAccu[65:64] == 2'd0 && cmdIsRW &&
	     crtBusy &&
	     addrCaptOK ;
  assign WILL_FIRE_RL_cmd_addr = CAN_FIRE_RL_cmd_addr ;

  // rule RL_rsp_nop
  assign CAN_FIRE_RL_rsp_nop =
	     crtRespF_FULL_N && rspCRH[34:32] == 3'd3 && crtBusy ;
  assign WILL_FIRE_RL_rsp_nop = CAN_FIRE_RL_rsp_nop ;

  // rule RL_agg_write
  assign CAN_FIRE_RL_agg_write =
	     a4l_a4wrResp_fifof_EMPTY_N && rspCRH[34:32] == 3'd4 && crtBusy &&
	     lclRspRemain != 12'd0 ;
  assign WILL_FIRE_RL_agg_write = CAN_FIRE_RL_agg_write ;

  // rule RL_rsp_write
  assign CAN_FIRE_RL_rsp_write =
	     crtRespF_FULL_N && rspCRH[34:32] == 3'd4 && crtBusy &&
	     lclRspRemain == 12'd0 ;
  assign WILL_FIRE_RL_rsp_write = CAN_FIRE_RL_rsp_write ;

  // rule RL_rsp_read
  assign CAN_FIRE_RL_rsp_read =
	     NOT_respBufF_rRdPtr_read__72_PLUS_1025_69_EQ_r_ETC___d476 &&
	     rspCRH[34:32] == 3'd5 &&
	     crtBusy ;
  assign WILL_FIRE_RL_rsp_read = CAN_FIRE_RL_rsp_read ;

  // rule RL_cmd_write
  assign CAN_FIRE_RL_cmd_write =
	     crtCmdF_EMPTY_N &&
	     cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d420 &&
	     cmdCRH[34:32] == 3'd1 &&
	     addrAccu[65:64] == 2'd1 ;
  assign WILL_FIRE_RL_cmd_write = CAN_FIRE_RL_cmd_write ;

  // rule RL_cmd_read
  assign CAN_FIRE_RL_cmd_read =
	     (cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 &&
	      lastTag[4] &&
	      !cmdCRH[7] ||
	      a4l_a4rdAddr_fifof_cntr_r != 2'd2) &&
	     cmdCRH[34:32] == 3'd2 &&
	     addrAccu[65:64] == 2'd1 ;
  assign WILL_FIRE_RL_cmd_read = CAN_FIRE_RL_cmd_read ;

  // rule RL_a4l_a4wrAddr_do_deq
  assign CAN_FIRE_RL_a4l_a4wrAddr_do_deq =
	     a4l_a4wrAddr_fifof_cntr_r != 2'd0 && axiM0_wrAddr_ready_value ;
  assign WILL_FIRE_RL_a4l_a4wrAddr_do_deq = CAN_FIRE_RL_a4l_a4wrAddr_do_deq ;

  // rule RL_a4l_a4wrAddr_fifof_incCtr
  assign CAN_FIRE_RL_a4l_a4wrAddr_fifof_incCtr =
	     a4l_a4wrAddr_fifof_enqueueing_whas &&
	     a4l_a4wrAddr_fifof_enqueueing_whas &&
	     !CAN_FIRE_RL_a4l_a4wrAddr_do_deq ;
  assign WILL_FIRE_RL_a4l_a4wrAddr_fifof_incCtr =
	     CAN_FIRE_RL_a4l_a4wrAddr_fifof_incCtr ;

  // rule RL_a4l_a4wrAddr_fifof_decCtr
  assign CAN_FIRE_RL_a4l_a4wrAddr_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4wrAddr_do_deq &&
	     !a4l_a4wrAddr_fifof_enqueueing_whas ;
  assign WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4wrAddr_fifof_decCtr ;

  // rule RL_a4l_a4wrAddr_fifof_both
  assign CAN_FIRE_RL_a4l_a4wrAddr_fifof_both =
	     a4l_a4wrAddr_fifof_enqueueing_whas &&
	     CAN_FIRE_RL_a4l_a4wrAddr_do_deq &&
	     a4l_a4wrAddr_fifof_enqueueing_whas ;
  assign WILL_FIRE_RL_a4l_a4wrAddr_fifof_both =
	     CAN_FIRE_RL_a4l_a4wrAddr_fifof_both ;

  // rule RL_a4l_a4wrData_do_deq
  assign CAN_FIRE_RL_a4l_a4wrData_do_deq =
	     a4l_a4wrData_fifof_cntr_r != 2'd0 && axiM0_wrData_ready_value ;
  assign WILL_FIRE_RL_a4l_a4wrData_do_deq = CAN_FIRE_RL_a4l_a4wrData_do_deq ;

  // rule RL_a4l_a4wrData_fifof_incCtr
  assign CAN_FIRE_RL_a4l_a4wrData_fifof_incCtr =
	     a4l_a4wrAddr_fifof_enqueueing_whas &&
	     a4l_a4wrAddr_fifof_enqueueing_whas &&
	     !CAN_FIRE_RL_a4l_a4wrData_do_deq ;
  assign WILL_FIRE_RL_a4l_a4wrData_fifof_incCtr =
	     CAN_FIRE_RL_a4l_a4wrData_fifof_incCtr ;

  // rule RL_a4l_a4wrData_fifof_decCtr
  assign CAN_FIRE_RL_a4l_a4wrData_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4wrData_do_deq &&
	     !a4l_a4wrAddr_fifof_enqueueing_whas ;
  assign WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4wrData_fifof_decCtr ;

  // rule RL_a4l_a4wrData_fifof_both
  assign CAN_FIRE_RL_a4l_a4wrData_fifof_both =
	     a4l_a4wrAddr_fifof_enqueueing_whas &&
	     CAN_FIRE_RL_a4l_a4wrData_do_deq &&
	     a4l_a4wrAddr_fifof_enqueueing_whas ;
  assign WILL_FIRE_RL_a4l_a4wrData_fifof_both =
	     CAN_FIRE_RL_a4l_a4wrData_fifof_both ;

  // rule RL_a4l_a4wrResp_do_enq
  assign CAN_FIRE_RL_a4l_a4wrResp_do_enq =
	     a4l_a4wrResp_fifof_FULL_N && axiM0_wrResp_valid_value ;
  assign WILL_FIRE_RL_a4l_a4wrResp_do_enq = CAN_FIRE_RL_a4l_a4wrResp_do_enq ;

  // rule RL_a4l_a4rdAddr_do_deq
  assign CAN_FIRE_RL_a4l_a4rdAddr_do_deq =
	     a4l_a4rdAddr_fifof_cntr_r != 2'd0 && axiM0_rdAddr_ready_value ;
  assign WILL_FIRE_RL_a4l_a4rdAddr_do_deq = CAN_FIRE_RL_a4l_a4rdAddr_do_deq ;

  // rule RL_a4l_a4rdAddr_fifof_incCtr
  assign CAN_FIRE_RL_a4l_a4rdAddr_fifof_incCtr =
	     MUX_rspCRH_write_1__SEL_1 && MUX_rspCRH_write_1__SEL_1 &&
	     !CAN_FIRE_RL_a4l_a4rdAddr_do_deq ;
  assign WILL_FIRE_RL_a4l_a4rdAddr_fifof_incCtr =
	     CAN_FIRE_RL_a4l_a4rdAddr_fifof_incCtr ;

  // rule RL_a4l_a4rdAddr_fifof_decCtr
  assign CAN_FIRE_RL_a4l_a4rdAddr_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4rdAddr_do_deq && !MUX_rspCRH_write_1__SEL_1 ;
  assign WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr =
	     CAN_FIRE_RL_a4l_a4rdAddr_fifof_decCtr ;

  // rule RL_a4l_a4rdAddr_fifof_both
  assign CAN_FIRE_RL_a4l_a4rdAddr_fifof_both =
	     MUX_rspCRH_write_1__SEL_1 && CAN_FIRE_RL_a4l_a4rdAddr_do_deq &&
	     MUX_rspCRH_write_1__SEL_1 ;
  assign WILL_FIRE_RL_a4l_a4rdAddr_fifof_both =
	     CAN_FIRE_RL_a4l_a4rdAddr_fifof_both ;

  // rule RL_a4l_a4rdResp_do_enq
  assign CAN_FIRE_RL_a4l_a4rdResp_do_enq =
	     a4l_a4rdResp_fifof_FULL_N && axiM0_rdResp_valid_value ;
  assign WILL_FIRE_RL_a4l_a4rdResp_do_enq = CAN_FIRE_RL_a4l_a4rdResp_do_enq ;

  // rule RL_modActive__dreg_update
  assign CAN_FIRE_RL_modActive__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_modActive__dreg_update = 1'd1 ;

  // rule RL_modFaulted__dreg_update
  assign CAN_FIRE_RL_modFaulted__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_modFaulted__dreg_update = 1'd1 ;

  // rule RL_respBufF_portB_read_data
  assign CAN_FIRE_RL_respBufF_portB_read_data = 1'd1 ;
  assign WILL_FIRE_RL_respBufF_portB_read_data = 1'd1 ;

  // rule RL_drain_rsp_read
  assign CAN_FIRE_RL_drain_rsp_read =
	     respBufF_rRdPtr != respBufF_rWrPtr && crtRespF_FULL_N &&
	     respBufTrig ;
  assign WILL_FIRE_RL_drain_rsp_read =
	     CAN_FIRE_RL_drain_rsp_read && !WILL_FIRE_RL_rsp_read &&
	     !WILL_FIRE_RL_rsp_write &&
	     !WILL_FIRE_RL_rsp_nop ;

  // rule RL_respBufF_portA
  assign CAN_FIRE_RL_respBufF_portA = 1'd1 ;
  assign WILL_FIRE_RL_respBufF_portA = 1'd1 ;

  // rule RL_respBufF_portB
  assign CAN_FIRE_RL_respBufF_portB = 1'd1 ;
  assign WILL_FIRE_RL_respBufF_portB = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_incCtr &&
	     a4l_a4rdAddr_fifof_cntr_r == 2'd0 ;
  assign MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_both && _dfoo11 ;
  assign MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_incCtr &&
	     a4l_a4rdAddr_fifof_cntr_r == 2'd1 ;
  assign MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_both && _dfoo9 ;
  assign MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_both && _dfoo3 ;
  assign MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_incCtr &&
	     a4l_a4wrAddr_fifof_cntr_r == 2'd0 ;
  assign MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_both && _dfoo1 ;
  assign MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_incCtr &&
	     a4l_a4wrAddr_fifof_cntr_r == 2'd1 ;
  assign MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_both && _dfoo7 ;
  assign MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_incCtr &&
	     a4l_a4wrData_fifof_cntr_r == 2'd0 ;
  assign MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_1 =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_both && _dfoo5 ;
  assign MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_2 =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_incCtr &&
	     a4l_a4wrData_fifof_cntr_r == 2'd1 ;
  assign MUX_addrAccu_write_1__SEL_1 =
	     WILL_FIRE_RL_cmd_addr && (addrCaptCnt == 2'd1 || !cmdIsAM64) ;
  assign MUX_addrCaptCnt_write_1__SEL_1 =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ;
  assign MUX_cmdAdlRemain_write_1__SEL_1 =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 &&
	     (crtCmdF_D_OUT[5:4] == 2'd0 || crtCmdF_D_OUT[5:4] == 2'd1 ||
	      crtCmdF_D_OUT[5:4] == 2'd2) ;
  assign MUX_cmdIsDO_write_1__SEL_1 = WILL_FIRE_RL_cmd_read && cmdCRH[7] ;
  assign MUX_cmdIsDO_write_1__SEL_2 = WILL_FIRE_RL_cmd_write && cmdCRH[7] ;
  assign MUX_cmdIsDO_write_1__SEL_3 =
	     WILL_FIRE_RL_rsp_read && rspActive && rspAdlRemain == 12'd1 ;
  assign MUX_cmdIsDO_write_1__SEL_5 =
	     WILL_FIRE_RL_rsp_nop && rspActive && rspAdlRemain == 12'd1 ;
  assign MUX_cmdIsDO_write_1__SEL_6 = WILL_FIRE_RL_cmd_nop && cmdCRH[7] ;
  assign MUX_cmdIsLast_write_1__PSEL_2 =
	     WILL_FIRE_RL_rsp_read || WILL_FIRE_RL_rsp_nop ;
  assign MUX_crtBusy_write_1__SEL_2 =
	     MUX_cmdIsLast_write_1__PSEL_2 && rspActive &&
	     rspAdlRemain == 12'd1 ;
  assign MUX_lastTag_write_1__SEL_1 = WILL_FIRE_RL_cmd_nop && !cmdCRH[7] ;
  assign MUX_lclRspRemain_write_1__SEL_1 =
	     WILL_FIRE_RL_cmd_crh &&
	     (crtCmdF_D_OUT[5:4] == 2'd1 || crtCmdF_D_OUT[5:4] == 2'd2) ;
  assign MUX_rspCRH_write_1__SEL_1 =
	     WILL_FIRE_RL_cmd_read &&
	     (!cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 ||
	      !lastTag[4] ||
	      cmdCRH[7]) ;
  assign MUX_rspCRH_write_1__SEL_6 =
	     WILL_FIRE_RL_cmd_nop && cmdAdlRemain == 12'd1 ;
  assign MUX_a4l_a4rdAddr_fifof_cntr_r_write_1__VAL_2 =
	     a4l_a4rdAddr_fifof_cntr_r + 2'd1 ;
  assign MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 =
	     { 3'd0, addrAccu[31:0] } ;
  assign MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_2 =
	     (a4l_a4rdAddr_fifof_cntr_r == 2'd1) ?
	       MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 :
	       a4l_a4rdAddr_fifof_q_1 ;
  assign MUX_a4l_a4rdAddr_fifof_q_1_write_1__VAL_2 =
	     (a4l_a4rdAddr_fifof_cntr_r == 2'd2) ?
	       MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 :
	       35'd0 ;
  assign MUX_a4l_a4wrAddr_fifof_cntr_r_write_1__VAL_2 =
	     a4l_a4wrAddr_fifof_cntr_r + 2'd1 ;
  assign MUX_a4l_a4wrAddr_fifof_q_0_write_1__VAL_1 =
	     (a4l_a4wrAddr_fifof_cntr_r == 2'd1) ?
	       MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 :
	       a4l_a4wrAddr_fifof_q_1 ;
  assign MUX_a4l_a4wrAddr_fifof_q_1_write_1__VAL_1 =
	     (a4l_a4wrAddr_fifof_cntr_r == 2'd2) ?
	       MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 :
	       35'd0 ;
  assign MUX_a4l_a4wrData_fifof_cntr_r_write_1__VAL_2 =
	     a4l_a4wrData_fifof_cntr_r + 2'd1 ;
  assign MUX_a4l_a4wrData_fifof_q_0_write_1__VAL_1 =
	     (a4l_a4wrData_fifof_cntr_r == 2'd1) ?
	       MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2 :
	       a4l_a4wrData_fifof_q_1 ;
  assign MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_1 =
	     (a4l_a4wrData_fifof_cntr_r == 2'd2) ?
	       MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2 :
	       36'd0 ;
  assign MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2 =
	     { cmdCRH[11:8], crtCmdF_D_OUT } ;
  assign MUX_addrAccu_write_1__VAL_1 =
	     { cmdIsAM64 ? 2'd2 : 2'd1, addrTmp, crtCmdF_D_OUT } ;
  assign MUX_addrAccu_write_1__VAL_2 =
	     { (cmdAdlRemain == 12'd1) ? 2'd0 : 2'd1,
	       32'hAAAAAAAA,
	       addrAccu[31:0] + 32'd4 } ;
  assign MUX_addrCaptCnt_write_1__VAL_2 = addrCaptCnt + 2'd1 ;
  assign MUX_cmdAdlRemain_write_1__VAL_2 =
	     (cmdAdlRemain == 12'd0) ? cmdAdlRemain : cmdAdlRemain - 12'd1 ;
  assign MUX_cmdCRH_write_1__VAL_1 =
	     { CASE_crtCmdFD_OUT_BITS_5_TO_4_0_0_1_1_2__q5, crtCmdF_D_OUT } ;
  assign MUX_crtRespF_enq_1__VAL_1 =
	     { IF_NOT_rspActive_65_73_OR_NOT_rspAdlRemain_62__ETC___d375,
	       IF_rspActive_65_THEN_IF_rspAdlRemain_62_EQ_2_7_ETC___d386[31:24],
	       2'd0,
	       IF_rspActive_65_THEN_IF_rspAdlRemain_62_EQ_2_7_ETC___d386[23:16],
	       2'd0,
	       IF_rspActive_65_THEN_IF_rspAdlRemain_62_EQ_2_7_ETC___d386[15:8],
	       2'd0,
	       IF_rspActive_65_THEN_IF_rspAdlRemain_62_EQ_2_7_ETC___d386[7:0] } ;
  assign MUX_crtRespF_enq_1__VAL_2 =
	     { 2'd1,
	       rspCRH[31:24],
	       2'd0,
	       rspCRH[23:16],
	       2'd0,
	       rspCRH[15:12],
	       IF_rspCRH_18_BITS_11_TO_8_77_EQ_0_78_OR_rspCRH_ETC___d383,
	       2'd0,
	       rspCRH[7:0] } ;
  assign MUX_crtRespF_enq_1__VAL_3 =
	     { CASE_respBufF_wDataOutwget_BITS_39_TO_38_0_re_ETC__q14,
	       respBufF_wDataOut_wget[37:30],
	       CASE_respBufF_wDataOutwget_BITS_29_TO_28_0_re_ETC__q15,
	       respBufF_wDataOut_wget[27:20],
	       CASE_respBufF_wDataOutwget_BITS_19_TO_18_0_re_ETC__q16,
	       respBufF_wDataOut_wget[17:10],
	       CASE_respBufF_wDataOutwget_BITS_9_TO_8_0_resp_ETC__q17,
	       respBufF_wDataOut_wget[7:0] } ;
  assign MUX_lastTag_write_1__VAL_2 = { 1'd1, cmdCRH[3:0] } ;
  assign MUX_lclRspRemain_write_1__VAL_2 = lclRspRemain - 12'd1 ;
  assign MUX_respBufCnt_write_1__VAL_1 = respBufCnt + 12'd1 ;
  assign MUX_respBufCnt_write_1__VAL_2 = respBufCnt - 12'd1 ;
  assign MUX_rspCRH_write_1__VAL_1 =
	     { 7'd88, cmdCRH[27:16], 12'd3, cmdCRH[3:0] } ;
  assign MUX_rspCRH_write_1__VAL_2 = { 31'd1207959555, cmdCRH[3:0] } ;
  assign MUX_rspCRH_write_1__VAL_6 =
	     { 7'd56, cmdCRH[27:16], 8'd0, cmdCRH[7], 3'd3, cmdCRH[3:0] } ;

  // inlined wires
  assign modActive_1_whas =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ||
	     WILL_FIRE_RL_rsp_read ||
	     WILL_FIRE_RL_cmd_read ||
	     WILL_FIRE_RL_rsp_write ||
	     WILL_FIRE_RL_agg_write ||
	     WILL_FIRE_RL_cmd_write ||
	     WILL_FIRE_RL_rsp_nop ||
	     WILL_FIRE_RL_cmd_nop ;
  assign modFaulted_1_whas =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT[5:4] == 2'd3 ;
  assign respBufF_wDataIn_wget =
	     { IF_NOT_rspActive_65_73_OR_NOT_rspAdlRemain_62__ETC___d375,
	       data__h19060[31:24],
	       2'd0,
	       data__h19060[23:16],
	       2'd0,
	       data__h19060[15:8],
	       2'd0,
	       data__h19060[7:0] } ;
  assign respBufF_wDataOut_wget =
	     (respBufF_rCache[52] &&
	      respBufF_rCache[51:40] == respBufF_rRdPtr) ?
	       { CASE_respBufF_rCache_BITS_39_TO_38_0_respBufF__ETC__q6,
		 respBufF_rCache[37:30],
		 CASE_respBufF_rCache_BITS_29_TO_28_0_respBufF__ETC__q7,
		 respBufF_rCache[27:20],
		 CASE_respBufF_rCache_BITS_19_TO_18_0_respBufF__ETC__q8,
		 respBufF_rCache[17:10],
		 CASE_respBufF_rCache_BITS_9_TO_8_0_respBufF_rC_ETC__q9,
		 respBufF_rCache[7:0] } :
	       { CASE_respBufF_memoryDOB_BITS_39_TO_38_0_respB_ETC__q10,
		 respBufF_memory_DOB[37:30],
		 CASE_respBufF_memoryDOB_BITS_29_TO_28_0_respB_ETC__q11,
		 respBufF_memory_DOB[27:20],
		 CASE_respBufF_memoryDOB_BITS_19_TO_18_0_respB_ETC__q12,
		 respBufF_memory_DOB[17:10],
		 CASE_respBufF_memoryDOB_BITS_9_TO_8_0_respBuf_ETC__q13,
		 respBufF_memory_DOB[7:0] } ;
  assign a4l_a4wrAddr_fifof_enqueueing_whas =
	     WILL_FIRE_RL_cmd_write &&
	     (!cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 ||
	      !lastTag[4] ||
	      cmdCRH[7]) ;

  // register a4l_a4rdAddr_fifof_cntr_r
  assign a4l_a4rdAddr_fifof_cntr_r_D_IN =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr ?
	       a4l_a4rdAddr_fifof_cntr_r_7_MINUS_1___d75 :
	       MUX_a4l_a4rdAddr_fifof_cntr_r_write_1__VAL_2 ;
  assign a4l_a4rdAddr_fifof_cntr_r_EN =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr ||
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_incCtr ;

  // register a4l_a4rdAddr_fifof_q_0
  always@(MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_1 or
	  MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 or
	  MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_2 or
	  MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_2 or
	  WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr or a4l_a4rdAddr_fifof_q_1)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_1:
	  a4l_a4rdAddr_fifof_q_0_D_IN =
	      MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1;
      MUX_a4l_a4rdAddr_fifof_q_0_write_1__SEL_2:
	  a4l_a4rdAddr_fifof_q_0_D_IN =
	      MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_2;
      WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr:
	  a4l_a4rdAddr_fifof_q_0_D_IN = a4l_a4rdAddr_fifof_q_1;
      default: a4l_a4rdAddr_fifof_q_0_D_IN =
		   35'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4rdAddr_fifof_q_0_EN =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_incCtr &&
	     a4l_a4rdAddr_fifof_cntr_r == 2'd0 ||
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_both && _dfoo11 ||
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr ;

  // register a4l_a4rdAddr_fifof_q_1
  always@(MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_1 or
	  MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 or
	  MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_2 or
	  MUX_a4l_a4rdAddr_fifof_q_1_write_1__VAL_2 or
	  WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_1:
	  a4l_a4rdAddr_fifof_q_1_D_IN =
	      MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1;
      MUX_a4l_a4rdAddr_fifof_q_1_write_1__SEL_2:
	  a4l_a4rdAddr_fifof_q_1_D_IN =
	      MUX_a4l_a4rdAddr_fifof_q_1_write_1__VAL_2;
      WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr:
	  a4l_a4rdAddr_fifof_q_1_D_IN = 35'd0;
      default: a4l_a4rdAddr_fifof_q_1_D_IN =
		   35'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4rdAddr_fifof_q_1_EN =
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_incCtr &&
	     a4l_a4rdAddr_fifof_cntr_r == 2'd1 ||
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_both && _dfoo9 ||
	     WILL_FIRE_RL_a4l_a4rdAddr_fifof_decCtr ;

  // register a4l_a4wrAddr_fifof_cntr_r
  assign a4l_a4wrAddr_fifof_cntr_r_D_IN =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr ?
	       a4l_a4wrAddr_fifof_cntr_r_MINUS_1___d15 :
	       MUX_a4l_a4wrAddr_fifof_cntr_r_write_1__VAL_2 ;
  assign a4l_a4wrAddr_fifof_cntr_r_EN =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr ||
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_incCtr ;

  // register a4l_a4wrAddr_fifof_q_0
  always@(MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_1 or
	  MUX_a4l_a4wrAddr_fifof_q_0_write_1__VAL_1 or
	  MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_2 or
	  MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 or
	  WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr or a4l_a4wrAddr_fifof_q_1)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_1:
	  a4l_a4wrAddr_fifof_q_0_D_IN =
	      MUX_a4l_a4wrAddr_fifof_q_0_write_1__VAL_1;
      MUX_a4l_a4wrAddr_fifof_q_0_write_1__SEL_2:
	  a4l_a4wrAddr_fifof_q_0_D_IN =
	      MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1;
      WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr:
	  a4l_a4wrAddr_fifof_q_0_D_IN = a4l_a4wrAddr_fifof_q_1;
      default: a4l_a4wrAddr_fifof_q_0_D_IN =
		   35'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4wrAddr_fifof_q_0_EN =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_both && _dfoo3 ||
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_incCtr &&
	     a4l_a4wrAddr_fifof_cntr_r == 2'd0 ||
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr ;

  // register a4l_a4wrAddr_fifof_q_1
  always@(MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_1 or
	  MUX_a4l_a4wrAddr_fifof_q_1_write_1__VAL_1 or
	  MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_2 or
	  MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1 or
	  WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_1:
	  a4l_a4wrAddr_fifof_q_1_D_IN =
	      MUX_a4l_a4wrAddr_fifof_q_1_write_1__VAL_1;
      MUX_a4l_a4wrAddr_fifof_q_1_write_1__SEL_2:
	  a4l_a4wrAddr_fifof_q_1_D_IN =
	      MUX_a4l_a4rdAddr_fifof_q_0_write_1__VAL_1;
      WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr:
	  a4l_a4wrAddr_fifof_q_1_D_IN = 35'd0;
      default: a4l_a4wrAddr_fifof_q_1_D_IN =
		   35'h2AAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4wrAddr_fifof_q_1_EN =
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_both && _dfoo1 ||
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_incCtr &&
	     a4l_a4wrAddr_fifof_cntr_r == 2'd1 ||
	     WILL_FIRE_RL_a4l_a4wrAddr_fifof_decCtr ;

  // register a4l_a4wrData_fifof_cntr_r
  assign a4l_a4wrData_fifof_cntr_r_D_IN =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr ?
	       a4l_a4wrData_fifof_cntr_r_4_MINUS_1___d42 :
	       MUX_a4l_a4wrData_fifof_cntr_r_write_1__VAL_2 ;
  assign a4l_a4wrData_fifof_cntr_r_EN =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr ||
	     WILL_FIRE_RL_a4l_a4wrData_fifof_incCtr ;

  // register a4l_a4wrData_fifof_q_0
  always@(MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_1 or
	  MUX_a4l_a4wrData_fifof_q_0_write_1__VAL_1 or
	  MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_2 or
	  MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2 or
	  WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr or a4l_a4wrData_fifof_q_1)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_1:
	  a4l_a4wrData_fifof_q_0_D_IN =
	      MUX_a4l_a4wrData_fifof_q_0_write_1__VAL_1;
      MUX_a4l_a4wrData_fifof_q_0_write_1__SEL_2:
	  a4l_a4wrData_fifof_q_0_D_IN =
	      MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2;
      WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr:
	  a4l_a4wrData_fifof_q_0_D_IN = a4l_a4wrData_fifof_q_1;
      default: a4l_a4wrData_fifof_q_0_D_IN =
		   36'hAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4wrData_fifof_q_0_EN =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_both && _dfoo7 ||
	     WILL_FIRE_RL_a4l_a4wrData_fifof_incCtr &&
	     a4l_a4wrData_fifof_cntr_r == 2'd0 ||
	     WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr ;

  // register a4l_a4wrData_fifof_q_1
  always@(MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_1 or
	  MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_1 or
	  MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_2 or
	  MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2 or
	  WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_1:
	  a4l_a4wrData_fifof_q_1_D_IN =
	      MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_1;
      MUX_a4l_a4wrData_fifof_q_1_write_1__SEL_2:
	  a4l_a4wrData_fifof_q_1_D_IN =
	      MUX_a4l_a4wrData_fifof_q_1_write_1__VAL_2;
      WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr:
	  a4l_a4wrData_fifof_q_1_D_IN = 36'd0;
      default: a4l_a4wrData_fifof_q_1_D_IN =
		   36'hAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign a4l_a4wrData_fifof_q_1_EN =
	     WILL_FIRE_RL_a4l_a4wrData_fifof_both && _dfoo5 ||
	     WILL_FIRE_RL_a4l_a4wrData_fifof_incCtr &&
	     a4l_a4wrData_fifof_cntr_r == 2'd1 ||
	     WILL_FIRE_RL_a4l_a4wrData_fifof_decCtr ;

  // register addrAccu
  assign addrAccu_D_IN =
	     MUX_addrAccu_write_1__SEL_1 ?
	       MUX_addrAccu_write_1__VAL_1 :
	       MUX_addrAccu_write_1__VAL_2 ;
  assign addrAccu_EN =
	     WILL_FIRE_RL_cmd_addr && (addrCaptCnt == 2'd1 || !cmdIsAM64) ||
	     WILL_FIRE_RL_cmd_read ||
	     WILL_FIRE_RL_cmd_write ;

  // register addrCaptCnt
  assign addrCaptCnt_D_IN =
	     MUX_addrCaptCnt_write_1__SEL_1 ?
	       2'd0 :
	       MUX_addrCaptCnt_write_1__VAL_2 ;
  assign addrCaptCnt_EN =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ||
	     WILL_FIRE_RL_cmd_addr ;

  // register addrCaptOK
  assign addrCaptOK_D_IN = MUX_addrCaptCnt_write_1__SEL_1 ;
  assign addrCaptOK_EN =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ||
	     WILL_FIRE_RL_cmd_addr && (addrCaptCnt == 2'd1 || !cmdIsAM64) ;

  // register addrTmp
  assign addrTmp_D_IN = crtCmdF_D_OUT ;
  assign addrTmp_EN = CAN_FIRE_RL_cmd_addr ;

  // register cmdAddrAccu
  assign cmdAddrAccu_D_IN = 32'h0 ;
  assign cmdAddrAccu_EN = 1'b0 ;

  // register cmdAdlRemain
  assign cmdAdlRemain_D_IN =
	     MUX_cmdAdlRemain_write_1__SEL_1 ?
	       crtCmdF_D_OUT[27:16] :
	       MUX_cmdAdlRemain_write_1__VAL_2 ;
  assign cmdAdlRemain_EN =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 &&
	     (crtCmdF_D_OUT[5:4] == 2'd0 || crtCmdF_D_OUT[5:4] == 2'd1 ||
	      crtCmdF_D_OUT[5:4] == 2'd2) ||
	     WILL_FIRE_RL_cmd_read ||
	     WILL_FIRE_RL_cmd_write ||
	     WILL_FIRE_RL_cmd_nop ;

  // register cmdCRH
  assign cmdCRH_D_IN =
	     MUX_addrCaptCnt_write_1__SEL_1 ?
	       MUX_cmdCRH_write_1__VAL_1 :
	       35'h6AAAAAAAA ;
  assign cmdCRH_EN =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ||
	     (WILL_FIRE_RL_cmd_read || WILL_FIRE_RL_cmd_write ||
	      WILL_FIRE_RL_cmd_nop) &&
	     cmdAdlRemain == 12'd1 ;

  // register cmdIsAM64
  assign cmdIsAM64_D_IN = crtCmdF_D_OUT[6] ;
  assign cmdIsAM64_EN = MUX_addrCaptCnt_write_1__SEL_1 ;

  // register cmdIsDO
  always@(MUX_cmdIsDO_write_1__SEL_1 or
	  MUX_cmdIsDO_write_1__SEL_2 or
	  MUX_cmdIsDO_write_1__SEL_3 or
	  WILL_FIRE_RL_rsp_write or
	  MUX_cmdIsDO_write_1__SEL_5 or
	  MUX_cmdIsDO_write_1__SEL_6 or
	  MUX_addrCaptCnt_write_1__SEL_1 or crtCmdF_D_OUT)
  case (1'b1)
    MUX_cmdIsDO_write_1__SEL_1 || MUX_cmdIsDO_write_1__SEL_2:
	cmdIsDO_D_IN = 1'd1;
    MUX_cmdIsDO_write_1__SEL_3 || WILL_FIRE_RL_rsp_write ||
    MUX_cmdIsDO_write_1__SEL_5:
	cmdIsDO_D_IN = 1'd0;
    MUX_cmdIsDO_write_1__SEL_6: cmdIsDO_D_IN = 1'd1;
    MUX_addrCaptCnt_write_1__SEL_1: cmdIsDO_D_IN = crtCmdF_D_OUT[7];
    default: cmdIsDO_D_IN = 1'b0 /* unspecified value */ ;
  endcase
  assign cmdIsDO_EN =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ||
	     (WILL_FIRE_RL_cmd_read || WILL_FIRE_RL_cmd_write ||
	      WILL_FIRE_RL_cmd_nop) &&
	     cmdCRH[7] ||
	     (WILL_FIRE_RL_rsp_read || WILL_FIRE_RL_rsp_nop) && rspActive &&
	     rspAdlRemain == 12'd1 ||
	     WILL_FIRE_RL_rsp_write ;

  // register cmdIsLast
  assign cmdIsLast_D_IN =
	     MUX_addrCaptCnt_write_1__SEL_1 && crtCmdF_D_OUT[31] ;
  assign cmdIsLast_EN =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ||
	     (WILL_FIRE_RL_rsp_read || WILL_FIRE_RL_rsp_nop) && rspActive &&
	     rspAdlRemain == 12'd1 ||
	     WILL_FIRE_RL_rsp_write ;

  // register cmdIsRW
  assign cmdIsRW_D_IN = 1'd1 ;
  assign cmdIsRW_EN = MUX_lclRspRemain_write_1__SEL_1 ;

  // register cmdRdHead
  assign cmdRdHead_D_IN = 1'b0 ;
  assign cmdRdHead_EN = 1'b0 ;

  // register crtBusy
  assign crtBusy_D_IN =
	     !MUX_crtBusy_write_1__SEL_2 && !WILL_FIRE_RL_rsp_write ;
  assign crtBusy_EN =
	     WILL_FIRE_RL_cmd_crh && crtCmdF_D_OUT != 32'd0 ||
	     (WILL_FIRE_RL_rsp_read || WILL_FIRE_RL_rsp_nop) && rspActive &&
	     rspAdlRemain == 12'd1 ||
	     WILL_FIRE_RL_rsp_write ;

  // register lastTag
  assign lastTag_D_IN =
	     MUX_lastTag_write_1__SEL_1 ? 5'd10 : MUX_lastTag_write_1__VAL_2 ;
  assign lastTag_EN =
	     WILL_FIRE_RL_cmd_nop && !cmdCRH[7] || _dand2lastTag_EN_write ;

  // register lclRspRemain
  assign lclRspRemain_D_IN =
	     MUX_lclRspRemain_write_1__SEL_1 ?
	       crtCmdF_D_OUT[27:16] :
	       MUX_lclRspRemain_write_1__VAL_2 ;
  assign lclRspRemain_EN =
	     WILL_FIRE_RL_cmd_crh &&
	     (crtCmdF_D_OUT[5:4] == 2'd1 || crtCmdF_D_OUT[5:4] == 2'd2) ||
	     WILL_FIRE_RL_agg_write ;

  // register modActive
  assign modActive_D_IN = modActive_1_whas ;
  assign modActive_EN = 1'd1 ;

  // register modFaulted
  assign modFaulted_D_IN = modFaulted_1_whas ;
  assign modFaulted_EN = 1'd1 ;

  // register respBufCnt
  assign respBufCnt_D_IN =
	     WILL_FIRE_RL_rsp_read ?
	       MUX_respBufCnt_write_1__VAL_1 :
	       MUX_respBufCnt_write_1__VAL_2 ;
  assign respBufCnt_EN =
	     WILL_FIRE_RL_rsp_read || WILL_FIRE_RL_drain_rsp_read ;

  // register respBufF_rCache
  assign respBufF_rCache_D_IN =
	     { 1'd1,
	       respBufF_rWrPtr,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d123,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d136,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d150,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d163 } ;
  assign respBufF_rCache_EN = CAN_FIRE_RL_rsp_read ;

  // register respBufF_rRdPtr
  assign respBufF_rRdPtr_D_IN = x__h9042 ;
  assign respBufF_rRdPtr_EN = WILL_FIRE_RL_drain_rsp_read ;

  // register respBufF_rWrPtr
  assign respBufF_rWrPtr_D_IN = x__h7924 ;
  assign respBufF_rWrPtr_EN = CAN_FIRE_RL_rsp_read ;

  // register respBufTrig
  assign respBufTrig_D_IN =
	     MUX_cmdIsDO_write_1__SEL_3 || respBufCnt != 12'd1 ;
  assign respBufTrig_EN =
	     WILL_FIRE_RL_rsp_read && rspActive && rspAdlRemain == 12'd1 ||
	     WILL_FIRE_RL_drain_rsp_read ;

  // register rspActive
  assign rspActive_D_IN = rspAdlRemain != 12'd1 ;
  assign rspActive_EN = MUX_cmdIsLast_write_1__PSEL_2 ;

  // register rspAdlRemain
  assign rspAdlRemain_D_IN =
	     rspActive ? rspAdlRemain - 12'd1 : rspCRH[27:16] ;
  assign rspAdlRemain_EN = MUX_cmdIsLast_write_1__PSEL_2 ;

  // register rspCRH
  always@(MUX_rspCRH_write_1__SEL_1 or
	  MUX_rspCRH_write_1__VAL_1 or
	  WILL_FIRE_RL_cmd_write or
	  MUX_rspCRH_write_1__VAL_2 or
	  MUX_cmdIsDO_write_1__SEL_3 or
	  WILL_FIRE_RL_rsp_write or
	  MUX_cmdIsDO_write_1__SEL_5 or
	  MUX_rspCRH_write_1__SEL_6 or MUX_rspCRH_write_1__VAL_6)
  case (1'b1)
    MUX_rspCRH_write_1__SEL_1: rspCRH_D_IN = MUX_rspCRH_write_1__VAL_1;
    WILL_FIRE_RL_cmd_write: rspCRH_D_IN = MUX_rspCRH_write_1__VAL_2;
    MUX_cmdIsDO_write_1__SEL_3 || WILL_FIRE_RL_rsp_write ||
    MUX_cmdIsDO_write_1__SEL_5:
	rspCRH_D_IN = 35'h6AAAAAAAA;
    MUX_rspCRH_write_1__SEL_6: rspCRH_D_IN = MUX_rspCRH_write_1__VAL_6;
    default: rspCRH_D_IN = 35'h2AAAAAAAA /* unspecified value */ ;
  endcase
  assign rspCRH_EN =
	     WILL_FIRE_RL_cmd_nop && cmdAdlRemain == 12'd1 ||
	     WILL_FIRE_RL_cmd_read &&
	     (!cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 ||
	      !lastTag[4] ||
	      cmdCRH[7]) ||
	     (WILL_FIRE_RL_rsp_read || WILL_FIRE_RL_rsp_nop) && rspActive &&
	     rspAdlRemain == 12'd1 ||
	     WILL_FIRE_RL_rsp_write ||
	     WILL_FIRE_RL_cmd_write ;

  // register sizInitRespB
  assign sizInitRespB_D_IN = crtCmdF_D_OUT ;
  assign sizInitRespB_EN = WILL_FIRE_RL_cmd_nop && cmdAdlRemain == 12'd2 ;

  // submodule a4l_a4rdResp_fifof
  assign a4l_a4rdResp_fifof_D_IN = axiM0_rdResp_data_value ;
  assign a4l_a4rdResp_fifof_ENQ = CAN_FIRE_RL_a4l_a4rdResp_do_enq ;
  assign a4l_a4rdResp_fifof_DEQ = WILL_FIRE_RL_rsp_read && rspActive ;
  assign a4l_a4rdResp_fifof_CLR = 1'b0 ;

  // submodule a4l_a4wrResp_fifof
  assign a4l_a4wrResp_fifof_D_IN = axiM0_wrResp_data_value ;
  assign a4l_a4wrResp_fifof_ENQ = CAN_FIRE_RL_a4l_a4wrResp_do_enq ;
  assign a4l_a4wrResp_fifof_DEQ = CAN_FIRE_RL_agg_write ;
  assign a4l_a4wrResp_fifof_CLR = 1'b0 ;

  // submodule crtCmdF
  assign crtCmdF_D_IN = crtS0_request_put ;
  assign crtCmdF_ENQ = EN_crtS0_request_put ;
  assign crtCmdF_DEQ =
	     WILL_FIRE_RL_cmd_write || WILL_FIRE_RL_cmd_addr ||
	     WILL_FIRE_RL_cmd_nop ||
	     WILL_FIRE_RL_cmd_crh ;
  assign crtCmdF_CLR = 1'b0 ;

  // submodule crtRespF
  always@(WILL_FIRE_RL_rsp_nop or
	  MUX_crtRespF_enq_1__VAL_1 or
	  WILL_FIRE_RL_rsp_write or
	  MUX_crtRespF_enq_1__VAL_2 or
	  WILL_FIRE_RL_drain_rsp_read or MUX_crtRespF_enq_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_rsp_nop: crtRespF_D_IN = MUX_crtRespF_enq_1__VAL_1;
      WILL_FIRE_RL_rsp_write: crtRespF_D_IN = MUX_crtRespF_enq_1__VAL_2;
      WILL_FIRE_RL_drain_rsp_read: crtRespF_D_IN = MUX_crtRespF_enq_1__VAL_3;
      default: crtRespF_D_IN = 40'hAAAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign crtRespF_ENQ =
	     WILL_FIRE_RL_rsp_nop || WILL_FIRE_RL_rsp_write ||
	     WILL_FIRE_RL_drain_rsp_read ;
  assign crtRespF_DEQ = EN_crtS0_response_get ;
  assign crtRespF_CLR = 1'b0 ;

  // submodule respBufF_memory
  assign respBufF_memory_ADDRA = respBufF_rWrPtr[10:0] ;
  assign respBufF_memory_ADDRB =
	     WILL_FIRE_RL_drain_rsp_read ?
	       x__h9042[10:0] :
	       respBufF_rRdPtr[10:0] ;
  assign respBufF_memory_DIA =
	     { IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d123,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d136,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d150,
	       IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d163 } ;
  assign respBufF_memory_DIB = 40'hAAAAAAAAAA /* unspecified value */  ;
  assign respBufF_memory_WEA = CAN_FIRE_RL_rsp_read ;
  assign respBufF_memory_WEB = 1'd0 ;
  assign respBufF_memory_ENA = 1'b1 ;
  assign respBufF_memory_ENB = 1'b1 ;

  // remaining internal signals
  assign IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d123 =
	     (!CAN_FIRE_RL_rsp_read || respBufF_wDataIn_wget[39:38] == 2'd0) ?
	       { 2'd0,
		 CAN_FIRE_RL_rsp_read ?
		   respBufF_wDataIn_wget[37:30] :
		   8'd0 } :
	       { CASE_respBufF_wDataInwget_BITS_39_TO_38_1_res_ETC__q18,
		 respBufF_wDataIn_wget[37:30] } ;
  assign IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d136 =
	     (!CAN_FIRE_RL_rsp_read || respBufF_wDataIn_wget[29:28] == 2'd0) ?
	       { 2'd0,
		 CAN_FIRE_RL_rsp_read ?
		   respBufF_wDataIn_wget[27:20] :
		   8'd0 } :
	       { CASE_respBufF_wDataInwget_BITS_29_TO_28_1_res_ETC__q19,
		 respBufF_wDataIn_wget[27:20] } ;
  assign IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d150 =
	     (!CAN_FIRE_RL_rsp_read || respBufF_wDataIn_wget[19:18] == 2'd0) ?
	       { 2'd0,
		 CAN_FIRE_RL_rsp_read ?
		   respBufF_wDataIn_wget[17:10] :
		   8'd0 } :
	       { CASE_respBufF_wDataInwget_BITS_19_TO_18_1_res_ETC__q20,
		 respBufF_wDataIn_wget[17:10] } ;
  assign IF_NOT_respBufF_wDataIn_whas__08_09_OR_respBuf_ETC___d163 =
	     (!CAN_FIRE_RL_rsp_read || respBufF_wDataIn_wget[9:8] == 2'd0) ?
	       { 2'd0,
		 CAN_FIRE_RL_rsp_read ? respBufF_wDataIn_wget[7:0] : 8'd0 } :
	       { CASE_respBufF_wDataInwget_BITS_9_TO_8_1_respB_ETC__q21,
		 respBufF_wDataIn_wget[7:0] } ;
  assign IF_NOT_rspActive_65_73_OR_NOT_rspAdlRemain_62__ETC___d375 =
	     (!rspActive || rspAdlRemain != 12'd1) ? 2'd0 : 2'd1 ;
  assign IF_rspActive_65_THEN_IF_rspAdlRemain_62_EQ_2_7_ETC___d386 =
	     rspActive ?
	       advert__h14551 :
	       { rspCRH[31:12],
		 IF_rspCRH_18_BITS_11_TO_8_77_EQ_0_78_OR_rspCRH_ETC___d383,
		 rspCRH[7:0] } ;
  assign NOT_respBufF_rRdPtr_read__72_PLUS_1025_69_EQ_r_ETC___d476 =
	     respBufF_rRdPtr + 12'd1025 != respBufF_rWrPtr &&
	     (!rspActive || a4l_a4rdResp_fifof_EMPTY_N) ;
  assign _dand2lastTag_EN_write =
	     (WILL_FIRE_RL_cmd_read || WILL_FIRE_RL_cmd_write) &&
	     (!cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 ||
	      !lastTag[4]) &&
	     !cmdCRH[7] ;
  assign _dfoo1 =
	     a4l_a4wrAddr_fifof_cntr_r != 2'd2 ||
	     a4l_a4wrAddr_fifof_cntr_r_MINUS_1___d15 == 2'd1 ;
  assign _dfoo11 =
	     a4l_a4rdAddr_fifof_cntr_r != 2'd1 ||
	     a4l_a4rdAddr_fifof_cntr_r_7_MINUS_1___d75 == 2'd0 ;
  assign _dfoo3 =
	     a4l_a4wrAddr_fifof_cntr_r != 2'd1 ||
	     a4l_a4wrAddr_fifof_cntr_r_MINUS_1___d15 == 2'd0 ;
  assign _dfoo5 =
	     a4l_a4wrData_fifof_cntr_r != 2'd2 ||
	     a4l_a4wrData_fifof_cntr_r_4_MINUS_1___d42 == 2'd1 ;
  assign _dfoo7 =
	     a4l_a4wrData_fifof_cntr_r != 2'd1 ||
	     a4l_a4wrData_fifof_cntr_r_4_MINUS_1___d42 == 2'd0 ;
  assign _dfoo9 =
	     a4l_a4rdAddr_fifof_cntr_r != 2'd2 ||
	     a4l_a4rdAddr_fifof_cntr_r_7_MINUS_1___d75 == 2'd1 ;
  assign a4l_a4rdAddr_fifof_cntr_r_7_MINUS_1___d75 =
	     a4l_a4rdAddr_fifof_cntr_r - 2'd1 ;
  assign a4l_a4wrAddr_fifof_cntr_r_MINUS_1___d15 =
	     a4l_a4wrAddr_fifof_cntr_r - 2'd1 ;
  assign a4l_a4wrData_fifof_cntr_r_4_MINUS_1___d42 =
	     a4l_a4wrData_fifof_cntr_r - 2'd1 ;
  assign advert__h14551 = (rspAdlRemain == 12'd2) ? 32'h00000052 : 32'd0 ;
  assign cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 =
	     cmdCRH[3:0] == lastTag[3:0] ;
  assign cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d420 =
	     cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 &&
	     lastTag[4] &&
	     !cmdCRH[7] ||
	     a4l_a4wrAddr_fifof_cntr_r != 2'd2 &&
	     a4l_a4wrData_fifof_cntr_r != 2'd2 ;
  assign data__h19060 =
	     rspActive ?
	       a4l_a4rdResp_fifof_D_OUT[31:0] :
	       { rspCRH[31:12],
		 IF_rspCRH_18_BITS_11_TO_8_77_EQ_0_78_OR_rspCRH_ETC___d383,
		 rspCRH[7:0] } ;
  assign x__h7924 = respBufF_rWrPtr + 12'd1 ;
  assign x__h9042 = respBufF_rRdPtr + 12'd1 ;
  always@(crtRespF_D_OUT)
  begin
    case (crtRespF_D_OUT[39:38])
      2'd0, 2'd1, 2'd2:
	  CASE_crtRespFD_OUT_BITS_39_TO_38_0_crtRespFD_ETC__q1 =
	      crtRespF_D_OUT[39:38];
      2'd3: CASE_crtRespFD_OUT_BITS_39_TO_38_0_crtRespFD_ETC__q1 = 2'd3;
    endcase
  end
  always@(crtRespF_D_OUT)
  begin
    case (crtRespF_D_OUT[29:28])
      2'd0, 2'd1, 2'd2:
	  CASE_crtRespFD_OUT_BITS_29_TO_28_0_crtRespFD_ETC__q2 =
	      crtRespF_D_OUT[29:28];
      2'd3: CASE_crtRespFD_OUT_BITS_29_TO_28_0_crtRespFD_ETC__q2 = 2'd3;
    endcase
  end
  always@(crtRespF_D_OUT)
  begin
    case (crtRespF_D_OUT[19:18])
      2'd0, 2'd1, 2'd2:
	  CASE_crtRespFD_OUT_BITS_19_TO_18_0_crtRespFD_ETC__q3 =
	      crtRespF_D_OUT[19:18];
      2'd3: CASE_crtRespFD_OUT_BITS_19_TO_18_0_crtRespFD_ETC__q3 = 2'd3;
    endcase
  end
  always@(crtRespF_D_OUT)
  begin
    case (crtRespF_D_OUT[9:8])
      2'd0, 2'd1, 2'd2:
	  CASE_crtRespFD_OUT_BITS_9_TO_8_0_crtRespFD_O_ETC__q4 =
	      crtRespF_D_OUT[9:8];
      2'd3: CASE_crtRespFD_OUT_BITS_9_TO_8_0_crtRespFD_O_ETC__q4 = 2'd3;
    endcase
  end
  always@(rspCRH)
  begin
    case (rspCRH[11:8])
      4'd0, 4'd1, 4'd2:
	  IF_rspCRH_18_BITS_11_TO_8_77_EQ_0_78_OR_rspCRH_ETC___d383 =
	      rspCRH[11:8];
      default: IF_rspCRH_18_BITS_11_TO_8_77_EQ_0_78_OR_rspCRH_ETC___d383 =
		   4'd15;
    endcase
  end
  always@(crtCmdF_D_OUT)
  begin
    case (crtCmdF_D_OUT[5:4])
      2'd0: CASE_crtCmdFD_OUT_BITS_5_TO_4_0_0_1_1_2__q5 = 3'd0;
      2'd1: CASE_crtCmdFD_OUT_BITS_5_TO_4_0_0_1_1_2__q5 = 3'd1;
      default: CASE_crtCmdFD_OUT_BITS_5_TO_4_0_0_1_1_2__q5 = 3'd2;
    endcase
  end
  always@(respBufF_rCache)
  begin
    case (respBufF_rCache[39:38])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_rCache_BITS_39_TO_38_0_respBufF__ETC__q6 =
	      respBufF_rCache[39:38];
      2'd3: CASE_respBufF_rCache_BITS_39_TO_38_0_respBufF__ETC__q6 = 2'd3;
    endcase
  end
  always@(respBufF_rCache)
  begin
    case (respBufF_rCache[29:28])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_rCache_BITS_29_TO_28_0_respBufF__ETC__q7 =
	      respBufF_rCache[29:28];
      2'd3: CASE_respBufF_rCache_BITS_29_TO_28_0_respBufF__ETC__q7 = 2'd3;
    endcase
  end
  always@(respBufF_rCache)
  begin
    case (respBufF_rCache[19:18])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_rCache_BITS_19_TO_18_0_respBufF__ETC__q8 =
	      respBufF_rCache[19:18];
      2'd3: CASE_respBufF_rCache_BITS_19_TO_18_0_respBufF__ETC__q8 = 2'd3;
    endcase
  end
  always@(respBufF_rCache)
  begin
    case (respBufF_rCache[9:8])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_rCache_BITS_9_TO_8_0_respBufF_rC_ETC__q9 =
	      respBufF_rCache[9:8];
      2'd3: CASE_respBufF_rCache_BITS_9_TO_8_0_respBufF_rC_ETC__q9 = 2'd3;
    endcase
  end
  always@(respBufF_memory_DOB)
  begin
    case (respBufF_memory_DOB[39:38])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_memoryDOB_BITS_39_TO_38_0_respB_ETC__q10 =
	      respBufF_memory_DOB[39:38];
      2'd3: CASE_respBufF_memoryDOB_BITS_39_TO_38_0_respB_ETC__q10 = 2'd3;
    endcase
  end
  always@(respBufF_memory_DOB)
  begin
    case (respBufF_memory_DOB[29:28])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_memoryDOB_BITS_29_TO_28_0_respB_ETC__q11 =
	      respBufF_memory_DOB[29:28];
      2'd3: CASE_respBufF_memoryDOB_BITS_29_TO_28_0_respB_ETC__q11 = 2'd3;
    endcase
  end
  always@(respBufF_memory_DOB)
  begin
    case (respBufF_memory_DOB[19:18])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_memoryDOB_BITS_19_TO_18_0_respB_ETC__q12 =
	      respBufF_memory_DOB[19:18];
      2'd3: CASE_respBufF_memoryDOB_BITS_19_TO_18_0_respB_ETC__q12 = 2'd3;
    endcase
  end
  always@(respBufF_memory_DOB)
  begin
    case (respBufF_memory_DOB[9:8])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_memoryDOB_BITS_9_TO_8_0_respBuf_ETC__q13 =
	      respBufF_memory_DOB[9:8];
      2'd3: CASE_respBufF_memoryDOB_BITS_9_TO_8_0_respBuf_ETC__q13 = 2'd3;
    endcase
  end
  always@(respBufF_wDataOut_wget)
  begin
    case (respBufF_wDataOut_wget[39:38])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_wDataOutwget_BITS_39_TO_38_0_re_ETC__q14 =
	      respBufF_wDataOut_wget[39:38];
      2'd3: CASE_respBufF_wDataOutwget_BITS_39_TO_38_0_re_ETC__q14 = 2'd3;
    endcase
  end
  always@(respBufF_wDataOut_wget)
  begin
    case (respBufF_wDataOut_wget[29:28])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_wDataOutwget_BITS_29_TO_28_0_re_ETC__q15 =
	      respBufF_wDataOut_wget[29:28];
      2'd3: CASE_respBufF_wDataOutwget_BITS_29_TO_28_0_re_ETC__q15 = 2'd3;
    endcase
  end
  always@(respBufF_wDataOut_wget)
  begin
    case (respBufF_wDataOut_wget[19:18])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_wDataOutwget_BITS_19_TO_18_0_re_ETC__q16 =
	      respBufF_wDataOut_wget[19:18];
      2'd3: CASE_respBufF_wDataOutwget_BITS_19_TO_18_0_re_ETC__q16 = 2'd3;
    endcase
  end
  always@(respBufF_wDataOut_wget)
  begin
    case (respBufF_wDataOut_wget[9:8])
      2'd0, 2'd1, 2'd2:
	  CASE_respBufF_wDataOutwget_BITS_9_TO_8_0_resp_ETC__q17 =
	      respBufF_wDataOut_wget[9:8];
      2'd3: CASE_respBufF_wDataOutwget_BITS_9_TO_8_0_resp_ETC__q17 = 2'd3;
    endcase
  end
  always@(respBufF_wDataIn_wget)
  begin
    case (respBufF_wDataIn_wget[39:38])
      2'd1, 2'd2:
	  CASE_respBufF_wDataInwget_BITS_39_TO_38_1_res_ETC__q18 =
	      respBufF_wDataIn_wget[39:38];
      default: CASE_respBufF_wDataInwget_BITS_39_TO_38_1_res_ETC__q18 = 2'd3;
    endcase
  end
  always@(respBufF_wDataIn_wget)
  begin
    case (respBufF_wDataIn_wget[29:28])
      2'd1, 2'd2:
	  CASE_respBufF_wDataInwget_BITS_29_TO_28_1_res_ETC__q19 =
	      respBufF_wDataIn_wget[29:28];
      default: CASE_respBufF_wDataInwget_BITS_29_TO_28_1_res_ETC__q19 = 2'd3;
    endcase
  end
  always@(respBufF_wDataIn_wget)
  begin
    case (respBufF_wDataIn_wget[19:18])
      2'd1, 2'd2:
	  CASE_respBufF_wDataInwget_BITS_19_TO_18_1_res_ETC__q20 =
	      respBufF_wDataIn_wget[19:18];
      default: CASE_respBufF_wDataInwget_BITS_19_TO_18_1_res_ETC__q20 = 2'd3;
    endcase
  end
  always@(respBufF_wDataIn_wget)
  begin
    case (respBufF_wDataIn_wget[9:8])
      2'd1, 2'd2:
	  CASE_respBufF_wDataInwget_BITS_9_TO_8_1_respB_ETC__q21 =
	      respBufF_wDataIn_wget[9:8];
      default: CASE_respBufF_wDataInwget_BITS_9_TO_8_1_respB_ETC__q21 = 2'd3;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        a4l_a4rdAddr_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
	a4l_a4rdAddr_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY 35'd0;
	a4l_a4rdAddr_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY 35'd0;
	a4l_a4wrAddr_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
	a4l_a4wrAddr_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY 35'd0;
	a4l_a4wrAddr_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY 35'd0;
	a4l_a4wrData_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
	a4l_a4wrData_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY 36'd0;
	a4l_a4wrData_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY 36'd0;
	addrAccu <= `BSV_ASSIGNMENT_DELAY 66'h0AAAAAAAAAAAAAAAA;
	addrCaptOK <= `BSV_ASSIGNMENT_DELAY 1'd0;
	cmdAdlRemain <= `BSV_ASSIGNMENT_DELAY 12'd0;
	cmdCRH <= `BSV_ASSIGNMENT_DELAY 35'h6AAAAAAAA;
	cmdIsAM64 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	cmdIsDO <= `BSV_ASSIGNMENT_DELAY 1'd0;
	cmdIsLast <= `BSV_ASSIGNMENT_DELAY 1'd0;
	cmdIsRW <= `BSV_ASSIGNMENT_DELAY 1'd0;
	cmdRdHead <= `BSV_ASSIGNMENT_DELAY 1'd1;
	crtBusy <= `BSV_ASSIGNMENT_DELAY 1'd0;
	lastTag <= `BSV_ASSIGNMENT_DELAY 5'd10;
	lclRspRemain <= `BSV_ASSIGNMENT_DELAY 12'd0;
	modActive <= `BSV_ASSIGNMENT_DELAY 1'd0;
	modFaulted <= `BSV_ASSIGNMENT_DELAY 1'd0;
	respBufCnt <= `BSV_ASSIGNMENT_DELAY 12'd0;
	respBufF_rCache <= `BSV_ASSIGNMENT_DELAY 53'h0AAAAAAAAAAAAA;
	respBufF_rRdPtr <= `BSV_ASSIGNMENT_DELAY 12'd0;
	respBufF_rWrPtr <= `BSV_ASSIGNMENT_DELAY 12'd0;
	respBufTrig <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rspActive <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rspAdlRemain <= `BSV_ASSIGNMENT_DELAY 12'd0;
	rspCRH <= `BSV_ASSIGNMENT_DELAY 35'h6AAAAAAAA;
	sizInitRespB <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (a4l_a4rdAddr_fifof_cntr_r_EN)
	  a4l_a4rdAddr_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4rdAddr_fifof_cntr_r_D_IN;
	if (a4l_a4rdAddr_fifof_q_0_EN)
	  a4l_a4rdAddr_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4rdAddr_fifof_q_0_D_IN;
	if (a4l_a4rdAddr_fifof_q_1_EN)
	  a4l_a4rdAddr_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4rdAddr_fifof_q_1_D_IN;
	if (a4l_a4wrAddr_fifof_cntr_r_EN)
	  a4l_a4wrAddr_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrAddr_fifof_cntr_r_D_IN;
	if (a4l_a4wrAddr_fifof_q_0_EN)
	  a4l_a4wrAddr_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrAddr_fifof_q_0_D_IN;
	if (a4l_a4wrAddr_fifof_q_1_EN)
	  a4l_a4wrAddr_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrAddr_fifof_q_1_D_IN;
	if (a4l_a4wrData_fifof_cntr_r_EN)
	  a4l_a4wrData_fifof_cntr_r <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrData_fifof_cntr_r_D_IN;
	if (a4l_a4wrData_fifof_q_0_EN)
	  a4l_a4wrData_fifof_q_0 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrData_fifof_q_0_D_IN;
	if (a4l_a4wrData_fifof_q_1_EN)
	  a4l_a4wrData_fifof_q_1 <= `BSV_ASSIGNMENT_DELAY
	      a4l_a4wrData_fifof_q_1_D_IN;
	if (addrAccu_EN) addrAccu <= `BSV_ASSIGNMENT_DELAY addrAccu_D_IN;
	if (addrCaptOK_EN)
	  addrCaptOK <= `BSV_ASSIGNMENT_DELAY addrCaptOK_D_IN;
	if (cmdAdlRemain_EN)
	  cmdAdlRemain <= `BSV_ASSIGNMENT_DELAY cmdAdlRemain_D_IN;
	if (cmdCRH_EN) cmdCRH <= `BSV_ASSIGNMENT_DELAY cmdCRH_D_IN;
	if (cmdIsAM64_EN) cmdIsAM64 <= `BSV_ASSIGNMENT_DELAY cmdIsAM64_D_IN;
	if (cmdIsDO_EN) cmdIsDO <= `BSV_ASSIGNMENT_DELAY cmdIsDO_D_IN;
	if (cmdIsLast_EN) cmdIsLast <= `BSV_ASSIGNMENT_DELAY cmdIsLast_D_IN;
	if (cmdIsRW_EN) cmdIsRW <= `BSV_ASSIGNMENT_DELAY cmdIsRW_D_IN;
	if (cmdRdHead_EN) cmdRdHead <= `BSV_ASSIGNMENT_DELAY cmdRdHead_D_IN;
	if (crtBusy_EN) crtBusy <= `BSV_ASSIGNMENT_DELAY crtBusy_D_IN;
	if (lastTag_EN) lastTag <= `BSV_ASSIGNMENT_DELAY lastTag_D_IN;
	if (lclRspRemain_EN)
	  lclRspRemain <= `BSV_ASSIGNMENT_DELAY lclRspRemain_D_IN;
	if (modActive_EN) modActive <= `BSV_ASSIGNMENT_DELAY modActive_D_IN;
	if (modFaulted_EN)
	  modFaulted <= `BSV_ASSIGNMENT_DELAY modFaulted_D_IN;
	if (respBufCnt_EN)
	  respBufCnt <= `BSV_ASSIGNMENT_DELAY respBufCnt_D_IN;
	if (respBufF_rCache_EN)
	  respBufF_rCache <= `BSV_ASSIGNMENT_DELAY respBufF_rCache_D_IN;
	if (respBufF_rRdPtr_EN)
	  respBufF_rRdPtr <= `BSV_ASSIGNMENT_DELAY respBufF_rRdPtr_D_IN;
	if (respBufF_rWrPtr_EN)
	  respBufF_rWrPtr <= `BSV_ASSIGNMENT_DELAY respBufF_rWrPtr_D_IN;
	if (respBufTrig_EN)
	  respBufTrig <= `BSV_ASSIGNMENT_DELAY respBufTrig_D_IN;
	if (rspActive_EN) rspActive <= `BSV_ASSIGNMENT_DELAY rspActive_D_IN;
	if (rspAdlRemain_EN)
	  rspAdlRemain <= `BSV_ASSIGNMENT_DELAY rspAdlRemain_D_IN;
	if (rspCRH_EN) rspCRH <= `BSV_ASSIGNMENT_DELAY rspCRH_D_IN;
	if (sizInitRespB_EN)
	  sizInitRespB <= `BSV_ASSIGNMENT_DELAY sizInitRespB_D_IN;
      end
    if (addrCaptCnt_EN) addrCaptCnt <= `BSV_ASSIGNMENT_DELAY addrCaptCnt_D_IN;
    if (addrTmp_EN) addrTmp <= `BSV_ASSIGNMENT_DELAY addrTmp_D_IN;
    if (cmdAddrAccu_EN) cmdAddrAccu <= `BSV_ASSIGNMENT_DELAY cmdAddrAccu_D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    a4l_a4rdAddr_fifof_cntr_r = 2'h2;
    a4l_a4rdAddr_fifof_q_0 = 35'h2AAAAAAAA;
    a4l_a4rdAddr_fifof_q_1 = 35'h2AAAAAAAA;
    a4l_a4wrAddr_fifof_cntr_r = 2'h2;
    a4l_a4wrAddr_fifof_q_0 = 35'h2AAAAAAAA;
    a4l_a4wrAddr_fifof_q_1 = 35'h2AAAAAAAA;
    a4l_a4wrData_fifof_cntr_r = 2'h2;
    a4l_a4wrData_fifof_q_0 = 36'hAAAAAAAAA;
    a4l_a4wrData_fifof_q_1 = 36'hAAAAAAAAA;
    addrAccu = 66'h2AAAAAAAAAAAAAAAA;
    addrCaptCnt = 2'h2;
    addrCaptOK = 1'h0;
    addrTmp = 32'hAAAAAAAA;
    cmdAddrAccu = 32'hAAAAAAAA;
    cmdAdlRemain = 12'hAAA;
    cmdCRH = 35'h2AAAAAAAA;
    cmdIsAM64 = 1'h0;
    cmdIsDO = 1'h0;
    cmdIsLast = 1'h0;
    cmdIsRW = 1'h0;
    cmdRdHead = 1'h0;
    crtBusy = 1'h0;
    lastTag = 5'h0A;
    lclRspRemain = 12'hAAA;
    modActive = 1'h0;
    modFaulted = 1'h0;
    respBufCnt = 12'hAAA;
    respBufF_rCache = 53'h0AAAAAAAAAAAAA;
    respBufF_rRdPtr = 12'hAAA;
    respBufF_rWrPtr = 12'hAAA;
    respBufTrig = 1'h0;
    rspActive = 1'h0;
    rspAdlRemain = 12'hAAA;
    rspCRH = 35'h2AAAAAAAA;
    sizInitRespB = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_nop)
	begin
	  v__h14415 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_nop)
	$display("[%0d]: %m: Hcrt cmd_nop cmdAdlRemain:%0d data:%0x",
		 v__h14415,
		 $unsigned(cmdAdlRemain),
		 crtCmdF_D_OUT);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rsp_nop)
	begin
	  v__h14567 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rsp_nop)
	$display("[%0d]: %m: Hcrt rsp_nop rspAdlRemain:%0d advert:%0x",
		 v__h14567,
		 $unsigned(rspAdlRemain),
		 advert__h14551);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_agg_write)
	begin
	  v__h16970 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_agg_write)
	$display("[%0d]: %m: Hcrt agg_write, lclRspRemain:%0d",
		 v__h16970,
		 $unsigned(lclRspRemain));
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rsp_write)
	begin
	  v__h18028 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rsp_write)
	$display("[%0d]: %m: Hcrt rsp_write sending aggregated write response",
		 v__h18028);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rsp_read && rspActive && rspAdlRemain == 12'd1)
	begin
	  v__h20032 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rsp_read && rspActive && rspAdlRemain == 12'd1)
	$display("[%0d]: %m: Hcrt rsp_read got data:%0x",
		 v__h20032,
		 data__h19060);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_write)
	begin
	  v__h16705 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_write)
	$display("[%0d]: %m: Hcrt cmd_write address:%0x data:%0x",
		 v__h16705,
		 $unsigned(addrAccu[31:0]),
		 crtCmdF_D_OUT);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_read &&
	  (!cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 ||
	   !lastTag[4] ||
	   cmdCRH[7]))
	begin
	  v__h18577 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_read &&
	  (!cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 ||
	   !lastTag[4] ||
	   cmdCRH[7]))
	$display("[%0d]: %m: Hcrt cmd_read address:%0x",
		 v__h18577,
		 $unsigned(addrAccu[31:0]));
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_read &&
	  cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 &&
	  lastTag[4] &&
	  !cmdCRH[7])
	begin
	  v__h18635 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_cmd_read &&
	  cmdCRH_72_BITS_3_TO_0_51_EQ_lastTag_13_BITS_3__ETC___d415 &&
	  lastTag[4] &&
	  !cmdCRH[7])
	$display("[%0d]: %m: Hcrt cmd_read *TAGS MATCH *address:%0x",
		 v__h18635,
		 $unsigned(addrAccu[31:0]));
  end
  // synopsys translate_on
endmodule  // mkHCrtCompleter2Axi

