/*
 * Generated by Bluespec Compiler, version 2013.01.beta5 (build 30325, 2013-01-23)
 * 
 * On Mon Feb 11 09:57:09 EST 2013
 * 
 */
#include "bluesim_primitives.h"
#include "mkHCrt_TB1.h"


/* String declarations */
static std::string const __str_literal_1("[%0d]: %m: Consumed %0d Byte with value %0x in cycle:%0d",
					 56u);
static std::string const __str_literal_2("[%0d]: %m: Terminate rule fired in cycle:%0d", 44u);


/* Constructor */
MOD_mkHCrt_TB1::MOD_mkHCrt_TB1(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_a4lm_rdAddrRdy_w(simHdl, "a4lm_rdAddrRdy_w", this, 1u, (tUInt8)0u),
    INST_a4lm_rdData_w(simHdl, "a4lm_rdData_w", this, 32u, (tUInt8)0u),
    INST_a4lm_rdRespVal_w(simHdl, "a4lm_rdRespVal_w", this, 1u, (tUInt8)0u),
    INST_a4lm_rdResp_w(simHdl, "a4lm_rdResp_w", this, 2u, (tUInt8)0u),
    INST_a4lm_wrAddrRdy_w(simHdl, "a4lm_wrAddrRdy_w", this, 1u, (tUInt8)0u),
    INST_a4lm_wrDataRdy_w(simHdl, "a4lm_wrDataRdy_w", this, 1u, (tUInt8)0u),
    INST_a4lm_wrRespVal_w(simHdl, "a4lm_wrRespVal_w", this, 1u, (tUInt8)0u),
    INST_a4lm_wrResp_w(simHdl, "a4lm_wrResp_w", this, 2u, (tUInt8)0u),
    INST_a4ls(simHdl, "a4ls", this, (tUInt8)1u),
    INST_consumeCnt(simHdl, "consumeCnt", this, 16u, 0u, (tUInt8)0u),
    INST_crt2axi(simHdl, "crt2axi", this),
    INST_cycleCount(simHdl, "cycleCount", this, 16u, 0u, (tUInt8)0u),
    INST_gpDA(simHdl, "gpDA", this, 48u),
    INST_gpL2Hdr(simHdl, "gpL2Hdr", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_gpPDU(simHdl, "gpPDU", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_gpPtr(simHdl, "gpPtr", this, 4u, (tUInt8)0u, (tUInt8)0u),
    INST_gpSA(simHdl, "gpSA", this, 48u),
    INST_gqPtr(simHdl, "gqPtr", this, 4u, (tUInt8)0u, (tUInt8)0u),
    INST_l2ConsumeF(simHdl, "l2ConsumeF", this, 10u, 2u, 1u, 0u),
    INST_l2GenF(simHdl, "l2GenF", this, 10u, 2u, 1u, 0u),
    INST_l2P(simHdl, "l2P", this),
    INST_l2qc_inF(simHdl, "l2qc_inF", this, 10u, 2u, 1u, 0u),
    INST_l2qc_outF(simHdl, "l2qc_outF", this, 40u, 2u, 1u, 0u),
    INST_l2qc_ptr(simHdl, "l2qc_ptr", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_l2qc_sr(simHdl, "l2qc_sr", this, 30u),
    INST_qcF(simHdl, "qcF", this, 32u, 2u, 1u, 0u),
    INST_qcl2_inF(simHdl, "qcl2_inF", this, 40u, 2u, 1u, 0u),
    INST_qcl2_outF(simHdl, "qcl2_outF", this, 10u, 2u, 1u, 0u),
    INST_qcl2_ptr(simHdl, "qcl2_ptr", this, 2u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h16417(12297829382473034410llu),
    DEF_v__h15109(12297829382473034410llu)
{
  symbol_count = 81u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkHCrt_TB1::init_symbols_0()
{
  init_symbol(&symbols[0u], "a4lm_rdAddrRdy_w", SYM_MODULE, &INST_a4lm_rdAddrRdy_w);
  init_symbol(&symbols[1u], "a4lm_rdData_w", SYM_MODULE, &INST_a4lm_rdData_w);
  init_symbol(&symbols[2u], "a4lm_rdResp_w", SYM_MODULE, &INST_a4lm_rdResp_w);
  init_symbol(&symbols[3u], "a4lm_rdRespVal_w", SYM_MODULE, &INST_a4lm_rdRespVal_w);
  init_symbol(&symbols[4u], "a4lm_wrAddrRdy_w", SYM_MODULE, &INST_a4lm_wrAddrRdy_w);
  init_symbol(&symbols[5u], "a4lm_wrDataRdy_w", SYM_MODULE, &INST_a4lm_wrDataRdy_w);
  init_symbol(&symbols[6u], "a4lm_wrResp_w", SYM_MODULE, &INST_a4lm_wrResp_w);
  init_symbol(&symbols[7u], "a4lm_wrRespVal_w", SYM_MODULE, &INST_a4lm_wrRespVal_w);
  init_symbol(&symbols[8u], "a4ls", SYM_MODULE, &INST_a4ls);
  init_symbol(&symbols[9u], "b__h15206", SYM_DEF, &DEF_b__h15206, 16u);
  init_symbol(&symbols[10u], "b__h7397", SYM_DEF, &DEF_b__h7397, 4u);
  init_symbol(&symbols[11u], "b__h9394", SYM_DEF, &DEF_b__h9394, 2u);
  init_symbol(&symbols[12u],
	      "CAN_FIRE_RL_a4lm_doAlways",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_a4lm_doAlways,
	      1u);
  init_symbol(&symbols[13u],
	      "CAN_FIRE_RL_advance_cycleCount",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_advance_cycleCount,
	      1u);
  init_symbol(&symbols[14u], "CAN_FIRE_RL_chomp_l2", SYM_DEF, &DEF_CAN_FIRE_RL_chomp_l2, 1u);
  init_symbol(&symbols[15u], "CAN_FIRE_RL_doAlways", SYM_DEF, &DEF_CAN_FIRE_RL_doAlways, 1u);
  init_symbol(&symbols[16u],
	      "CAN_FIRE_RL_feed_hcrt_req",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_feed_hcrt_req,
	      1u);
  init_symbol(&symbols[17u],
	      "CAN_FIRE_RL_l2_gen_header",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2_gen_header,
	      1u);
  init_symbol(&symbols[18u],
	      "CAN_FIRE_RL_l2_gen_payload",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2_gen_payload,
	      1u);
  init_symbol(&symbols[19u],
	      "CAN_FIRE_RL_l2qc_unfunnel",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2qc_unfunnel,
	      1u);
  init_symbol(&symbols[20u],
	      "CAN_FIRE_RL_mkConnectionGetPut",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_mkConnectionGetPut,
	      1u);
  init_symbol(&symbols[21u],
	      "CAN_FIRE_RL_mkConnectionGetPut_1",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_mkConnectionGetPut_1,
	      1u);
  init_symbol(&symbols[22u],
	      "CAN_FIRE_RL_mkConnectionGetPut_2",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_mkConnectionGetPut_2,
	      1u);
  init_symbol(&symbols[23u],
	      "CAN_FIRE_RL_mkConnectionGetPut_3",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_mkConnectionGetPut_3,
	      1u);
  init_symbol(&symbols[24u],
	      "CAN_FIRE_RL_mkConnectionGetPut_4",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_mkConnectionGetPut_4,
	      1u);
  init_symbol(&symbols[25u],
	      "CAN_FIRE_RL_mkConnectionGetPut_5",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_mkConnectionGetPut_5,
	      1u);
  init_symbol(&symbols[26u], "CAN_FIRE_RL_qcl2_funnel", SYM_DEF, &DEF_CAN_FIRE_RL_qcl2_funnel, 1u);
  init_symbol(&symbols[27u], "CAN_FIRE_RL_terminate", SYM_DEF, &DEF_CAN_FIRE_RL_terminate, 1u);
  init_symbol(&symbols[28u], "consumeCnt", SYM_MODULE, &INST_consumeCnt);
  init_symbol(&symbols[29u], "crt2axi", SYM_MODULE, &INST_crt2axi);
  init_symbol(&symbols[30u], "cycleCount", SYM_MODULE, &INST_cycleCount);
  init_symbol(&symbols[31u], "gpDA", SYM_MODULE, &INST_gpDA);
  init_symbol(&symbols[32u], "gpL2Hdr", SYM_MODULE, &INST_gpL2Hdr);
  init_symbol(&symbols[33u], "gpPDU", SYM_MODULE, &INST_gpPDU);
  init_symbol(&symbols[34u], "gpPtr", SYM_MODULE, &INST_gpPtr);
  init_symbol(&symbols[35u], "gpPtr__h2001", SYM_DEF, &DEF_gpPtr__h2001, 4u);
  init_symbol(&symbols[36u], "gpSA", SYM_MODULE, &INST_gpSA);
  init_symbol(&symbols[37u], "gqPtr", SYM_MODULE, &INST_gqPtr);
  init_symbol(&symbols[38u], "l2ConsumeF", SYM_MODULE, &INST_l2ConsumeF);
  init_symbol(&symbols[39u], "l2GenF", SYM_MODULE, &INST_l2GenF);
  init_symbol(&symbols[40u], "l2P", SYM_MODULE, &INST_l2P);
  init_symbol(&symbols[41u], "l2qc_inF", SYM_MODULE, &INST_l2qc_inF);
  init_symbol(&symbols[42u], "l2qc_outF", SYM_MODULE, &INST_l2qc_outF);
  init_symbol(&symbols[43u], "l2qc_ptr", SYM_MODULE, &INST_l2qc_ptr);
  init_symbol(&symbols[44u], "l2qc_sr", SYM_MODULE, &INST_l2qc_sr);
  init_symbol(&symbols[45u], "qcF", SYM_MODULE, &INST_qcF);
  init_symbol(&symbols[46u], "qcl2_inF", SYM_MODULE, &INST_qcl2_inF);
  init_symbol(&symbols[47u], "qcl2_outF", SYM_MODULE, &INST_qcl2_outF);
  init_symbol(&symbols[48u], "qcl2_ptr", SYM_MODULE, &INST_qcl2_ptr);
  init_symbol(&symbols[49u], "RL_a4lm_doAlways", SYM_RULE);
  init_symbol(&symbols[50u], "RL_advance_cycleCount", SYM_RULE);
  init_symbol(&symbols[51u], "RL_chomp_l2", SYM_RULE);
  init_symbol(&symbols[52u], "RL_doAlways", SYM_RULE);
  init_symbol(&symbols[53u], "RL_feed_hcrt_req", SYM_RULE);
  init_symbol(&symbols[54u], "RL_l2_gen_header", SYM_RULE);
  init_symbol(&symbols[55u], "RL_l2_gen_payload", SYM_RULE);
  init_symbol(&symbols[56u], "RL_l2qc_unfunnel", SYM_RULE);
  init_symbol(&symbols[57u], "RL_mkConnectionGetPut", SYM_RULE);
  init_symbol(&symbols[58u], "RL_mkConnectionGetPut_1", SYM_RULE);
  init_symbol(&symbols[59u], "RL_mkConnectionGetPut_2", SYM_RULE);
  init_symbol(&symbols[60u], "RL_mkConnectionGetPut_3", SYM_RULE);
  init_symbol(&symbols[61u], "RL_mkConnectionGetPut_4", SYM_RULE);
  init_symbol(&symbols[62u], "RL_mkConnectionGetPut_5", SYM_RULE);
  init_symbol(&symbols[63u], "RL_qcl2_funnel", SYM_RULE);
  init_symbol(&symbols[64u], "RL_terminate", SYM_RULE);
  init_symbol(&symbols[65u],
	      "WILL_FIRE_RL_a4lm_doAlways",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_a4lm_doAlways,
	      1u);
  init_symbol(&symbols[66u],
	      "WILL_FIRE_RL_advance_cycleCount",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_advance_cycleCount,
	      1u);
  init_symbol(&symbols[67u], "WILL_FIRE_RL_chomp_l2", SYM_DEF, &DEF_WILL_FIRE_RL_chomp_l2, 1u);
  init_symbol(&symbols[68u], "WILL_FIRE_RL_doAlways", SYM_DEF, &DEF_WILL_FIRE_RL_doAlways, 1u);
  init_symbol(&symbols[69u],
	      "WILL_FIRE_RL_feed_hcrt_req",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_feed_hcrt_req,
	      1u);
  init_symbol(&symbols[70u],
	      "WILL_FIRE_RL_l2_gen_header",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2_gen_header,
	      1u);
  init_symbol(&symbols[71u],
	      "WILL_FIRE_RL_l2_gen_payload",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2_gen_payload,
	      1u);
  init_symbol(&symbols[72u],
	      "WILL_FIRE_RL_l2qc_unfunnel",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2qc_unfunnel,
	      1u);
  init_symbol(&symbols[73u],
	      "WILL_FIRE_RL_mkConnectionGetPut",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_mkConnectionGetPut,
	      1u);
  init_symbol(&symbols[74u],
	      "WILL_FIRE_RL_mkConnectionGetPut_1",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_mkConnectionGetPut_1,
	      1u);
  init_symbol(&symbols[75u],
	      "WILL_FIRE_RL_mkConnectionGetPut_2",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_mkConnectionGetPut_2,
	      1u);
  init_symbol(&symbols[76u],
	      "WILL_FIRE_RL_mkConnectionGetPut_3",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_mkConnectionGetPut_3,
	      1u);
  init_symbol(&symbols[77u],
	      "WILL_FIRE_RL_mkConnectionGetPut_4",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_mkConnectionGetPut_4,
	      1u);
  init_symbol(&symbols[78u],
	      "WILL_FIRE_RL_mkConnectionGetPut_5",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_mkConnectionGetPut_5,
	      1u);
  init_symbol(&symbols[79u], "WILL_FIRE_RL_qcl2_funnel", SYM_DEF, &DEF_WILL_FIRE_RL_qcl2_funnel, 1u);
  init_symbol(&symbols[80u], "WILL_FIRE_RL_terminate", SYM_DEF, &DEF_WILL_FIRE_RL_terminate, 1u);
}


/* Rule actions */

void MOD_mkHCrt_TB1::RL_a4lm_doAlways()
{
  tUInt64 DEF_IF_a4lm_rdResp_w_whas__9_THEN_a4lm_rdResp_w_wg_ETC___d25;
  tUInt8 DEF_a4lm_wrDataRdy_w_whas_AND_a4lm_wrDataRdy_w_wget___d6;
  tUInt8 DEF_a4lm_wrAddrRdy_w_whas_AND_a4lm_wrAddrRdy_w_wget___d3;
  tUInt8 DEF_a4lm_wrRespVal_w_whas_AND_a4lm_wrRespVal_w_wget___d9;
  tUInt8 DEF_a4lm_rdAddrRdy_w_whas__0_AND_a4lm_rdAddrRdy_w__ETC___d12;
  tUInt8 DEF_a4lm_rdRespVal_w_whas__3_AND_a4lm_rdRespVal_w__ETC___d15;
  tUInt8 DEF_IF_a4lm_wrResp_w_whas__6_THEN_a4lm_wrResp_w_wg_ETC___d18;
  tUInt32 DEF_value_data__h1140;
  tUInt32 DEF_x_wget__h746;
  DEF_x_wget__h746 = INST_a4lm_rdData_w.METH_wget();
  DEF_value_data__h1140 = INST_a4lm_rdData_w.METH_whas() ? DEF_x_wget__h746 : 0u;
  DEF_IF_a4lm_wrResp_w_whas__6_THEN_a4lm_wrResp_w_wg_ETC___d18 = INST_a4lm_wrResp_w.METH_whas() ? INST_a4lm_wrResp_w.METH_wget() : (tUInt8)0u;
  DEF_a4lm_rdRespVal_w_whas__3_AND_a4lm_rdRespVal_w__ETC___d15 = INST_a4lm_rdRespVal_w.METH_whas() && INST_a4lm_rdRespVal_w.METH_wget();
  DEF_a4lm_rdAddrRdy_w_whas__0_AND_a4lm_rdAddrRdy_w__ETC___d12 = INST_a4lm_rdAddrRdy_w.METH_whas() && INST_a4lm_rdAddrRdy_w.METH_wget();
  DEF_a4lm_wrRespVal_w_whas_AND_a4lm_wrRespVal_w_wget___d9 = INST_a4lm_wrRespVal_w.METH_whas() && INST_a4lm_wrRespVal_w.METH_wget();
  DEF_a4lm_wrAddrRdy_w_whas_AND_a4lm_wrAddrRdy_w_wget___d3 = INST_a4lm_wrAddrRdy_w.METH_whas() && INST_a4lm_wrAddrRdy_w.METH_wget();
  DEF_a4lm_wrDataRdy_w_whas_AND_a4lm_wrDataRdy_w_wget___d6 = INST_a4lm_wrDataRdy_w.METH_whas() && INST_a4lm_wrDataRdy_w.METH_wget();
  DEF_IF_a4lm_rdResp_w_whas__9_THEN_a4lm_rdResp_w_wg_ETC___d25 = 17179869183llu & ((((tUInt64)(INST_a4lm_rdResp_w.METH_whas() ? INST_a4lm_rdResp_w.METH_wget() : (tUInt8)0u)) << 32u) | (tUInt64)(DEF_value_data__h1140));
  INST_crt2axi.METH_axiM0_wrAddr_ready(DEF_a4lm_wrAddrRdy_w_whas_AND_a4lm_wrAddrRdy_w_wget___d3);
  INST_crt2axi.METH_axiM0_wrData_ready(DEF_a4lm_wrDataRdy_w_whas_AND_a4lm_wrDataRdy_w_wget___d6);
  INST_crt2axi.METH_axiM0_wrResp_valid(DEF_a4lm_wrRespVal_w_whas_AND_a4lm_wrRespVal_w_wget___d9);
  INST_crt2axi.METH_axiM0_rdAddr_ready(DEF_a4lm_rdAddrRdy_w_whas__0_AND_a4lm_rdAddrRdy_w__ETC___d12);
  INST_crt2axi.METH_axiM0_rdResp_valid(DEF_a4lm_rdRespVal_w_whas__3_AND_a4lm_rdRespVal_w__ETC___d15);
  INST_crt2axi.METH_axiM0_wrResp_data(DEF_IF_a4lm_wrResp_w_whas__6_THEN_a4lm_wrResp_w_wg_ETC___d18);
  INST_crt2axi.METH_axiM0_rdResp_data(DEF_IF_a4lm_rdResp_w_whas__9_THEN_a4lm_rdResp_w_wg_ETC___d25);
}

void MOD_mkHCrt_TB1::RL_l2_gen_header()
{
  tUInt8 DEF_gpPtr_6_PLUS_1___d68;
  tUInt8 DEF_NOT_gpPtr_6_EQ_0_7_3_AND_gpPtr_6_EQ_1_2_OR_gpP_ETC___d97;
  tUInt8 DEF_gpPtr_6_EQ_1___d32;
  tUInt8 DEF_gpPtr_6_EQ_2___d33;
  tUInt8 DEF_gpPtr_6_EQ_3___d35;
  tUInt8 DEF_gpPtr_6_EQ_4___d37;
  tUInt8 DEF_gpPtr_6_EQ_5___d39;
  tUInt8 DEF_gpPtr_6_EQ_6___d41;
  tUInt32 DEF__0_CONCAT_gpDA_0_BITS_47_TO_40_2___d98;
  tUInt32 DEF_IF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_ETC___d102;
  tUInt32 DEF__0_CONCAT_gpSA_8_BITS_47_TO_40_0___d99;
  tUInt64 DEF_IF_gpPtr_6_EQ_0_7_THEN_43839021184_ELSE_gpDA_0_ETC___d74;
  tUInt64 DEF_IF_gpPtr_6_EQ_0_7_THEN_176157985423013_ELSE_gp_ETC___d92;
  tUInt8 DEF_gpSA_BITS_47_TO_40___h3994;
  tUInt8 DEF_gpDA_BITS_47_TO_40___h3642;
  tUInt64 DEF_gpDA__h6157;
  tUInt64 DEF_gpSA__h7298;
  tUInt8 DEF_gpPtr_6_EQ_0_7_OR_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_ETC___d69;
  tUInt8 DEF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_6__ETC___d42;
  tUInt8 DEF_gpPtr_6_EQ_7_3_OR_gpPtr_6_EQ_8_4_5_OR_gpPtr_6__ETC___d53;
  tUInt8 DEF_gpPtr_6_EQ_0_7_OR_NOT_gpPtr_6_EQ_1_2_5_AND_NOT_ETC___d87;
  DEF_gpSA__h7298 = INST_gpSA.METH_read();
  DEF_gpDA__h6157 = INST_gpDA.METH_read();
  DEF_gpPtr__h2001 = INST_gpPtr.METH_read();
  DEF_gpPtr_6_EQ_7_3_OR_gpPtr_6_EQ_8_4_5_OR_gpPtr_6__ETC___d53 = ((((DEF_gpPtr__h2001 == (tUInt8)7u || DEF_gpPtr__h2001 == (tUInt8)8u) || DEF_gpPtr__h2001 == (tUInt8)9u) || DEF_gpPtr__h2001 == (tUInt8)10u) || DEF_gpPtr__h2001 == (tUInt8)11u) || DEF_gpPtr__h2001 == (tUInt8)12u;
  DEF_gpDA_BITS_47_TO_40___h3642 = (tUInt8)(DEF_gpDA__h6157 >> 40u);
  DEF_gpSA_BITS_47_TO_40___h3994 = (tUInt8)(DEF_gpSA__h7298 >> 40u);
  DEF_gpPtr_6_EQ_0___d27 = DEF_gpPtr__h2001 == (tUInt8)0u;
  DEF_IF_gpPtr_6_EQ_0_7_THEN_176157985423013_ELSE_gp_ETC___d92 = DEF_gpPtr_6_EQ_0___d27 ? 176157985423013llu : 281474976710655llu & ((((tUInt64)(1099511627775llu & DEF_gpSA__h7298)) << 8u) | (tUInt64)(DEF_gpSA_BITS_47_TO_40___h3994));
  DEF_IF_gpPtr_6_EQ_0_7_THEN_43839021184_ELSE_gpDA_0_ETC___d74 = DEF_gpPtr_6_EQ_0___d27 ? 43839021184llu : 281474976710655llu & ((((tUInt64)(1099511627775llu & DEF_gpDA__h6157)) << 8u) | (tUInt64)(DEF_gpDA_BITS_47_TO_40___h3642));
  DEF__0_CONCAT_gpSA_8_BITS_47_TO_40_0___d99 = 1023u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_gpSA_BITS_47_TO_40___h3994));
  DEF__0_CONCAT_gpDA_0_BITS_47_TO_40_2___d98 = 1023u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_gpDA_BITS_47_TO_40___h3642));
  switch (DEF_gpPtr__h2001) {
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
    DEF_IF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_ETC___d102 = DEF__0_CONCAT_gpDA_0_BITS_47_TO_40_2___d98;
    break;
  case (tUInt8)7u:
  case (tUInt8)8u:
  case (tUInt8)9u:
  case (tUInt8)10u:
  case (tUInt8)11u:
  case (tUInt8)12u:
    DEF_IF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_ETC___d102 = DEF__0_CONCAT_gpSA_8_BITS_47_TO_40_0___d99;
    break;
  case (tUInt8)13u:
    DEF_IF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_ETC___d102 = 240u;
    break;
  default:
    DEF_IF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_ETC___d102 = 82u;
  }
  DEF_gpPtr_6_EQ_13___d28 = DEF_gpPtr__h2001 == (tUInt8)13u;
  DEF_gpPtr_6_EQ_14___d55 = DEF_gpPtr__h2001 == (tUInt8)14u;
  DEF_gpPtr_6_EQ_6___d41 = DEF_gpPtr__h2001 == (tUInt8)6u;
  DEF_gpPtr_6_EQ_5___d39 = DEF_gpPtr__h2001 == (tUInt8)5u;
  DEF_gpPtr_6_EQ_4___d37 = DEF_gpPtr__h2001 == (tUInt8)4u;
  DEF_gpPtr_6_EQ_3___d35 = DEF_gpPtr__h2001 == (tUInt8)3u;
  DEF_gpPtr_6_EQ_2___d33 = DEF_gpPtr__h2001 == (tUInt8)2u;
  DEF_gpPtr_6_EQ_1___d32 = DEF_gpPtr__h2001 == (tUInt8)1u;
  DEF_gpPtr_6_EQ_0_7_OR_NOT_gpPtr_6_EQ_1_2_5_AND_NOT_ETC___d87 = DEF_gpPtr_6_EQ_0___d27 || ((((((!DEF_gpPtr_6_EQ_1___d32 && !DEF_gpPtr_6_EQ_2___d33) && !DEF_gpPtr_6_EQ_3___d35) && !DEF_gpPtr_6_EQ_4___d37) && !DEF_gpPtr_6_EQ_5___d39) && !DEF_gpPtr_6_EQ_6___d41) && DEF_gpPtr_6_EQ_7_3_OR_gpPtr_6_EQ_8_4_5_OR_gpPtr_6__ETC___d53);
  DEF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_6__ETC___d42 = ((((DEF_gpPtr_6_EQ_1___d32 || DEF_gpPtr_6_EQ_2___d33) || DEF_gpPtr_6_EQ_3___d35) || DEF_gpPtr_6_EQ_4___d37) || DEF_gpPtr_6_EQ_5___d39) || DEF_gpPtr_6_EQ_6___d41;
  DEF_gpPtr_6_EQ_0_7_OR_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_ETC___d69 = DEF_gpPtr_6_EQ_0___d27 || DEF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_6__ETC___d42;
  DEF_NOT_gpPtr_6_EQ_0_7_3_AND_gpPtr_6_EQ_1_2_OR_gpP_ETC___d97 = !DEF_gpPtr_6_EQ_0___d27 && (DEF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_6__ETC___d42 || (DEF_gpPtr_6_EQ_7_3_OR_gpPtr_6_EQ_8_4_5_OR_gpPtr_6__ETC___d53 || (DEF_gpPtr_6_EQ_13___d28 || DEF_gpPtr_6_EQ_14___d55)));
  DEF_gpPtr_6_PLUS_1___d68 = (tUInt8)15u & (DEF_gpPtr__h2001 + (tUInt8)1u);
  INST_gpPtr.METH_write(DEF_gpPtr_6_PLUS_1___d68);
  if (DEF_gpPtr_6_EQ_0_7_OR_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_ETC___d69)
    INST_gpDA.METH_write(DEF_IF_gpPtr_6_EQ_0_7_THEN_43839021184_ELSE_gpDA_0_ETC___d74);
  if (DEF_gpPtr_6_EQ_0_7_OR_NOT_gpPtr_6_EQ_1_2_5_AND_NOT_ETC___d87)
    INST_gpSA.METH_write(DEF_IF_gpPtr_6_EQ_0_7_THEN_176157985423013_ELSE_gp_ETC___d92);
  if (DEF_gpPtr_6_EQ_14___d55)
    INST_gpPDU.METH_write((tUInt8)1u);
  if (DEF_NOT_gpPtr_6_EQ_0_7_3_AND_gpPtr_6_EQ_1_2_OR_gpP_ETC___d97)
    INST_l2GenF.METH_enq(DEF_IF_gpPtr_6_EQ_1_2_OR_gpPtr_6_EQ_2_3_4_OR_gpPtr_ETC___d102);
}

void MOD_mkHCrt_TB1::RL_l2_gen_payload()
{
  tUInt8 DEF_gqPtr_03_EQ_0_04_OR_gqPtr_03_EQ_1_05_OR_gqPtr__ETC___d140;
  tUInt8 DEF_IF_gqPtr_03_EQ_15_32_THEN_gqPtr_03_ELSE_gqPtr__ETC___d134;
  tUInt32 DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146;
  DEF_b__h7397 = INST_gqPtr.METH_read();
  switch (DEF_b__h7397) {
  case (tUInt8)0u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
  case (tUInt8)8u:
  case (tUInt8)9u:
  case (tUInt8)10u:
    DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146 = 0u;
    break;
  case (tUInt8)1u:
    DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146 = 255u;
    break;
  case (tUInt8)2u:
    DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146 = 2u;
    break;
  case (tUInt8)3u:
    DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146 = 128u;
    break;
  case (tUInt8)4u:
    DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146 = 66u;
    break;
  default:
    DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146 = 256u;
  }
  DEF_IF_gqPtr_03_EQ_15_32_THEN_gqPtr_03_ELSE_gqPtr__ETC___d134 = DEF_b__h7397 == (tUInt8)15u ? DEF_b__h7397 : (tUInt8)15u & (DEF_b__h7397 + (tUInt8)1u);
  DEF_gqPtr_03_EQ_11___d125 = DEF_b__h7397 == (tUInt8)11u;
  DEF_gqPtr_03_EQ_0_04_OR_gqPtr_03_EQ_1_05_OR_gqPtr__ETC___d140 = DEF_b__h7397 == (tUInt8)0u || (DEF_b__h7397 == (tUInt8)1u || (DEF_b__h7397 == (tUInt8)2u || (DEF_b__h7397 == (tUInt8)3u || (DEF_b__h7397 == (tUInt8)4u || ((DEF_b__h7397 == (tUInt8)5u || (DEF_b__h7397 == (tUInt8)6u || (DEF_b__h7397 == (tUInt8)7u || (DEF_b__h7397 == (tUInt8)8u || (DEF_b__h7397 == (tUInt8)9u || DEF_b__h7397 == (tUInt8)10u))))) || DEF_gqPtr_03_EQ_11___d125)))));
  INST_gqPtr.METH_write(DEF_IF_gqPtr_03_EQ_15_32_THEN_gqPtr_03_ELSE_gqPtr__ETC___d134);
  if (DEF_gqPtr_03_EQ_0_04_OR_gqPtr_03_EQ_1_05_OR_gqPtr__ETC___d140)
    INST_l2GenF.METH_enq(DEF_IF_gqPtr_03_EQ_0_04_THEN_0_ELSE_IF_gqPtr_03_EQ_ETC___d146);
}

void MOD_mkHCrt_TB1::RL_mkConnectionGetPut()
{
  tUInt32 DEF_IF_l2GenF_first__50_BITS_9_TO_8_51_EQ_0_52_OR__ETC___d161;
  tUInt8 DEF_IF_l2GenF_first__50_BITS_9_TO_8_51_EQ_0_52_OR__ETC___d157;
  tUInt8 DEF_l2GenF_first__50_BITS_9_TO_8___d151;
  tUInt8 DEF_l2GenF_first__50_BITS_7_TO_0___d159;
  tUInt32 DEF_l2GenF_first____d150;
  DEF_l2GenF_first____d150 = INST_l2GenF.METH_first();
  DEF_l2GenF_first__50_BITS_7_TO_0___d159 = (tUInt8)((tUInt8)255u & DEF_l2GenF_first____d150);
  DEF_l2GenF_first__50_BITS_9_TO_8___d151 = (tUInt8)(DEF_l2GenF_first____d150 >> 8u);
  switch (DEF_l2GenF_first__50_BITS_9_TO_8___d151) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2GenF_first__50_BITS_9_TO_8_51_EQ_0_52_OR__ETC___d157 = DEF_l2GenF_first__50_BITS_9_TO_8___d151;
    break;
  default:
    DEF_IF_l2GenF_first__50_BITS_9_TO_8_51_EQ_0_52_OR__ETC___d157 = (tUInt8)3u;
  }
  DEF_IF_l2GenF_first__50_BITS_9_TO_8_51_EQ_0_52_OR__ETC___d161 = 1023u & ((((tUInt32)(DEF_IF_l2GenF_first__50_BITS_9_TO_8_51_EQ_0_52_OR__ETC___d157)) << 8u) | (tUInt32)(DEF_l2GenF_first__50_BITS_9_TO_8___d151 == (tUInt8)0u || DEF_l2GenF_first__50_BITS_9_TO_8___d151 == (tUInt8)1u ? DEF_l2GenF_first__50_BITS_7_TO_0___d159 : DEF_l2GenF_first__50_BITS_7_TO_0___d159));
  INST_l2GenF.METH_deq();
  INST_l2P.METH_server_request_put(DEF_IF_l2GenF_first__50_BITS_9_TO_8_51_EQ_0_52_OR__ETC___d161);
}

void MOD_mkHCrt_TB1::RL_l2qc_unfunnel()
{
  tUInt32 DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d204;
  tUInt32 DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d195;
  tUInt32 DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d205;
  tUInt32 DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d184;
  tUInt64 DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d221;
  tUInt8 DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_T_ETC___d207;
  tUInt8 DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d180;
  tUInt8 DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d191;
  tUInt8 DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d200;
  tUInt8 DEF_IF_l2qc_sr_73_BITS_29_TO_28_11_EQ_0_12_OR_l2qc_ETC___d217;
  tUInt8 DEF_l2qc_sr_73_BITS_9_TO_8___d185;
  tUInt8 DEF_l2qc_sr_73_BITS_19_TO_18___d174;
  tUInt8 DEF_l2qc_sr_73_BITS_29_TO_28___d211;
  tUInt8 DEF_l2qc_inF_first__66_BITS_7_TO_0___d202;
  tUInt8 DEF_l2qc_sr_BITS_7_TO_0___h9121;
  tUInt8 DEF_l2qc_sr_BITS_17_TO_10___h8922;
  tUInt8 DEF_l2qc_sr_BITS_27_TO_20___h10364;
  tUInt32 DEF_l2qc_sr__h10323;
  tUInt8 DEF_l2qc_ptr_63_EQ_3_64_OR_NOT_l2qc_inF_first__66__ETC___d209;
  DEF_b__h9394 = INST_l2qc_ptr.METH_read();
  DEF_l2qc_sr__h10323 = INST_l2qc_sr.METH_read();
  DEF_l2qc_inF_first____d166 = INST_l2qc_inF.METH_first();
  DEF_l2qc_inF_first__66_BITS_9_TO_8___d167 = (tUInt8)(DEF_l2qc_inF_first____d166 >> 8u);
  DEF_l2qc_sr_BITS_27_TO_20___h10364 = (tUInt8)((tUInt8)255u & (DEF_l2qc_sr__h10323 >> 20u));
  DEF_l2qc_sr_BITS_17_TO_10___h8922 = (tUInt8)((tUInt8)255u & (DEF_l2qc_sr__h10323 >> 10u));
  DEF_l2qc_sr_BITS_7_TO_0___h9121 = (tUInt8)((tUInt8)255u & DEF_l2qc_sr__h10323);
  DEF_l2qc_inF_first__66_BITS_7_TO_0___d202 = (tUInt8)((tUInt8)255u & DEF_l2qc_inF_first____d166);
  DEF_l2qc_sr_73_BITS_29_TO_28___d211 = (tUInt8)(DEF_l2qc_sr__h10323 >> 28u);
  DEF_l2qc_sr_73_BITS_19_TO_18___d174 = (tUInt8)((tUInt8)3u & (DEF_l2qc_sr__h10323 >> 18u));
  DEF_l2qc_sr_73_BITS_9_TO_8___d185 = (tUInt8)((tUInt8)3u & (DEF_l2qc_sr__h10323 >> 8u));
  switch (DEF_l2qc_inF_first__66_BITS_9_TO_8___d167) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d200 = DEF_l2qc_inF_first__66_BITS_9_TO_8___d167;
    break;
  default:
    DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d200 = (tUInt8)3u;
  }
  switch (DEF_l2qc_sr_73_BITS_29_TO_28___d211) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2qc_sr_73_BITS_29_TO_28_11_EQ_0_12_OR_l2qc_ETC___d217 = DEF_l2qc_sr_73_BITS_29_TO_28___d211;
    break;
  default:
    DEF_IF_l2qc_sr_73_BITS_29_TO_28_11_EQ_0_12_OR_l2qc_ETC___d217 = (tUInt8)3u;
  }
  switch (DEF_l2qc_sr_73_BITS_9_TO_8___d185) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d191 = DEF_l2qc_sr_73_BITS_9_TO_8___d185;
    break;
  default:
    DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d191 = (tUInt8)3u;
  }
  DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168 = DEF_l2qc_inF_first__66_BITS_9_TO_8___d167 == (tUInt8)0u;
  switch (DEF_l2qc_sr_73_BITS_19_TO_18___d174) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d180 = DEF_l2qc_sr_73_BITS_19_TO_18___d174;
    break;
  default:
    DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d180 = (tUInt8)3u;
  }
  DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_T_ETC___d207 = DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168 ? (tUInt8)3u & (DEF_b__h9394 + (tUInt8)1u) : (tUInt8)0u;
  DEF_l2qc_ptr_63_EQ_3___d164 = DEF_b__h9394 == (tUInt8)3u;
  DEF_l2qc_ptr_63_EQ_3_64_OR_NOT_l2qc_inF_first__66__ETC___d209 = DEF_l2qc_ptr_63_EQ_3___d164 || !DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168;
  DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d184 = 1023u & ((((tUInt32)(DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d180)) << 8u) | (tUInt32)(DEF_l2qc_sr_73_BITS_19_TO_18___d174 == (tUInt8)0u || DEF_l2qc_sr_73_BITS_19_TO_18___d174 == (tUInt8)1u ? DEF_l2qc_sr_BITS_17_TO_10___h8922 : DEF_l2qc_sr_BITS_17_TO_10___h8922));
  DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d195 = 1023u & ((((tUInt32)(DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d191)) << 8u) | (tUInt32)(DEF_l2qc_sr_73_BITS_9_TO_8___d185 == (tUInt8)0u || DEF_l2qc_sr_73_BITS_9_TO_8___d185 == (tUInt8)1u ? DEF_l2qc_sr_BITS_7_TO_0___h9121 : DEF_l2qc_sr_BITS_7_TO_0___h9121));
  DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d204 = 1023u & ((((tUInt32)(DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d200)) << 8u) | (tUInt32)(DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168 || DEF_l2qc_inF_first__66_BITS_9_TO_8___d167 == (tUInt8)1u ? DEF_l2qc_inF_first__66_BITS_7_TO_0___d202 : DEF_l2qc_inF_first__66_BITS_7_TO_0___d202));
  DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d221 = 1099511627775llu & (((((((tUInt64)(DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d204)) << 30u) | (((tUInt64)(DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d195)) << 20u)) | (((tUInt64)(DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d184)) << 10u)) | (((tUInt64)(DEF_IF_l2qc_sr_73_BITS_29_TO_28_11_EQ_0_12_OR_l2qc_ETC___d217)) << 8u)) | (tUInt64)(DEF_l2qc_sr_73_BITS_29_TO_28___d211 == (tUInt8)0u || DEF_l2qc_sr_73_BITS_29_TO_28___d211 == (tUInt8)1u ? DEF_l2qc_sr_BITS_27_TO_20___h10364 : DEF_l2qc_sr_BITS_27_TO_20___h10364));
  DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d205 = 1073741823u & (((DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d184 << 20u) | (DEF_IF_l2qc_sr_73_BITS_9_TO_8_85_EQ_0_86_OR_l2qc_s_ETC___d195 << 10u)) | DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d204);
  INST_l2qc_inF.METH_deq();
  INST_l2qc_sr.METH_write(DEF_IF_l2qc_sr_73_BITS_19_TO_18_74_EQ_0_75_OR_l2qc_ETC___d205);
  INST_l2qc_ptr.METH_write(DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_T_ETC___d207);
  if (DEF_l2qc_ptr_63_EQ_3_64_OR_NOT_l2qc_inF_first__66__ETC___d209)
    INST_l2qc_outF.METH_enq(DEF_IF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0_68_O_ETC___d221);
}

void MOD_mkHCrt_TB1::RL_mkConnectionGetPut_1()
{
  tUInt32 DEF_IF_l2P_client_request_get_25_BITS_9_TO_8_26_EQ_ETC___d236;
  tUInt8 DEF_IF_l2P_client_request_get_25_BITS_9_TO_8_26_EQ_ETC___d232;
  tUInt8 DEF_l2P_client_request_get_25_BITS_9_TO_8___d226;
  tUInt8 DEF_l2P_client_request_get_25_BITS_7_TO_0___d234;
  tUInt32 DEF_l2P_client_request_get___d225;
  tUInt32 DEF_AVMeth_l2P_client_request_get;
  DEF_AVMeth_l2P_client_request_get = INST_l2P.METH_client_request_get();
  DEF_l2P_client_request_get___d225 = DEF_AVMeth_l2P_client_request_get;
  DEF_l2P_client_request_get_25_BITS_7_TO_0___d234 = (tUInt8)((tUInt8)255u & DEF_l2P_client_request_get___d225);
  DEF_l2P_client_request_get_25_BITS_9_TO_8___d226 = (tUInt8)(DEF_l2P_client_request_get___d225 >> 8u);
  switch (DEF_l2P_client_request_get_25_BITS_9_TO_8___d226) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2P_client_request_get_25_BITS_9_TO_8_26_EQ_ETC___d232 = DEF_l2P_client_request_get_25_BITS_9_TO_8___d226;
    break;
  default:
    DEF_IF_l2P_client_request_get_25_BITS_9_TO_8_26_EQ_ETC___d232 = (tUInt8)3u;
  }
  DEF_IF_l2P_client_request_get_25_BITS_9_TO_8_26_EQ_ETC___d236 = 1023u & ((((tUInt32)(DEF_IF_l2P_client_request_get_25_BITS_9_TO_8_26_EQ_ETC___d232)) << 8u) | (tUInt32)(DEF_l2P_client_request_get_25_BITS_9_TO_8___d226 == (tUInt8)0u || DEF_l2P_client_request_get_25_BITS_9_TO_8___d226 == (tUInt8)1u ? DEF_l2P_client_request_get_25_BITS_7_TO_0___d234 : DEF_l2P_client_request_get_25_BITS_7_TO_0___d234));
  INST_l2qc_inF.METH_enq(DEF_IF_l2P_client_request_get_25_BITS_9_TO_8_26_EQ_ETC___d236);
}

void MOD_mkHCrt_TB1::RL_feed_hcrt_req()
{
  tUInt32 DEF_dw__h10794;
  tUInt8 DEF_l2qc_outF_first__40_BITS_9_TO_8___d260;
  tUInt8 DEF_l2qc_outF_first__40_BITS_19_TO_18___d254;
  tUInt8 DEF_l2qc_outF_first__40_BITS_29_TO_28___d247;
  tUInt8 DEF_l2qc_outF_first__40_BITS_39_TO_38___d241;
  tUInt8 DEF_l2qc_outF_first__40_BITS_7_TO_0___d264;
  tUInt8 DEF_l2qc_outF_first__40_BITS_17_TO_10___d258;
  tUInt8 DEF_l2qc_outF_first__40_BITS_27_TO_20___d251;
  tUInt8 DEF_l2qc_outF_first__40_BITS_37_TO_30___d245;
  tUInt64 DEF_l2qc_outF_first____d240;
  DEF_l2qc_outF_first____d240 = INST_l2qc_outF.METH_first();
  DEF_l2qc_outF_first__40_BITS_37_TO_30___d245 = (tUInt8)((tUInt8)255u & (DEF_l2qc_outF_first____d240 >> 30u));
  DEF_l2qc_outF_first__40_BITS_27_TO_20___d251 = (tUInt8)((tUInt8)255u & (DEF_l2qc_outF_first____d240 >> 20u));
  DEF_l2qc_outF_first__40_BITS_17_TO_10___d258 = (tUInt8)((tUInt8)255u & (DEF_l2qc_outF_first____d240 >> 10u));
  DEF_l2qc_outF_first__40_BITS_39_TO_38___d241 = (tUInt8)(DEF_l2qc_outF_first____d240 >> 38u);
  DEF_l2qc_outF_first__40_BITS_7_TO_0___d264 = (tUInt8)((tUInt8)255u & DEF_l2qc_outF_first____d240);
  DEF_l2qc_outF_first__40_BITS_29_TO_28___d247 = (tUInt8)((tUInt8)3u & (DEF_l2qc_outF_first____d240 >> 28u));
  DEF_l2qc_outF_first__40_BITS_19_TO_18___d254 = (tUInt8)((tUInt8)3u & (DEF_l2qc_outF_first____d240 >> 18u));
  DEF_l2qc_outF_first__40_BITS_9_TO_8___d260 = (tUInt8)((tUInt8)3u & (DEF_l2qc_outF_first____d240 >> 8u));
  DEF_dw__h10794 = (((((tUInt32)(DEF_l2qc_outF_first__40_BITS_39_TO_38___d241 == (tUInt8)0u || DEF_l2qc_outF_first__40_BITS_39_TO_38___d241 == (tUInt8)1u ? DEF_l2qc_outF_first__40_BITS_37_TO_30___d245 : DEF_l2qc_outF_first__40_BITS_37_TO_30___d245)) << 24u) | (((tUInt32)(DEF_l2qc_outF_first__40_BITS_29_TO_28___d247 == (tUInt8)0u || DEF_l2qc_outF_first__40_BITS_29_TO_28___d247 == (tUInt8)1u ? DEF_l2qc_outF_first__40_BITS_27_TO_20___d251 : DEF_l2qc_outF_first__40_BITS_27_TO_20___d251)) << 16u)) | (((tUInt32)(DEF_l2qc_outF_first__40_BITS_19_TO_18___d254 == (tUInt8)0u || DEF_l2qc_outF_first__40_BITS_19_TO_18___d254 == (tUInt8)1u ? DEF_l2qc_outF_first__40_BITS_17_TO_10___d258 : DEF_l2qc_outF_first__40_BITS_17_TO_10___d258)) << 8u)) | (tUInt32)(DEF_l2qc_outF_first__40_BITS_9_TO_8___d260 == (tUInt8)0u || DEF_l2qc_outF_first__40_BITS_9_TO_8___d260 == (tUInt8)1u ? DEF_l2qc_outF_first__40_BITS_7_TO_0___d264 : DEF_l2qc_outF_first__40_BITS_7_TO_0___d264);
  INST_l2qc_outF.METH_deq();
  INST_qcF.METH_enq(DEF_dw__h10794);
}

void MOD_mkHCrt_TB1::RL_mkConnectionGetPut_2()
{
  tUInt32 DEF_v__h12175;
  DEF_v__h12175 = INST_qcF.METH_first();
  INST_qcF.METH_deq();
  INST_crt2axi.METH_crtS0_request_put(DEF_v__h12175);
}

void MOD_mkHCrt_TB1::RL_qcl2_funnel()
{
  tUInt8 DEF_qcl2_ptr_84_EQ_3_12_OR_NOT_SEL_ARR_qcl2_inF_fi_ETC___d314;
  tUInt8 DEF_IF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_E_ETC___d287;
  tUInt32 DEF_IF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_E_ETC___d311;
  tUInt8 DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285;
  tUInt8 DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_1_ETC___d300;
  tUInt8 DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_2_ETC___d307;
  tUInt8 DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293;
  tUInt8 DEF_qcl2_inF_first__74_BITS_9_TO_8___d275;
  tUInt8 DEF_qcl2_inF_first__74_BITS_19_TO_18___d277;
  tUInt8 DEF_qcl2_inF_first__74_BITS_29_TO_28___d279;
  tUInt8 DEF_qcl2_inF_first__74_BITS_39_TO_38___d281;
  tUInt8 DEF_x__h13181;
  tUInt8 DEF_x__h13182;
  tUInt8 DEF_x__h13183;
  tUInt8 DEF_x__h13184;
  tUInt64 DEF_qcl2_inF_first____d274;
  tUInt8 DEF_x__h13273;
  DEF_x__h13273 = INST_qcl2_ptr.METH_read();
  DEF_qcl2_inF_first____d274 = INST_qcl2_inF.METH_first();
  DEF_x__h13184 = (tUInt8)((tUInt8)255u & (DEF_qcl2_inF_first____d274 >> 30u));
  DEF_x__h13183 = (tUInt8)((tUInt8)255u & (DEF_qcl2_inF_first____d274 >> 20u));
  DEF_x__h13182 = (tUInt8)((tUInt8)255u & (DEF_qcl2_inF_first____d274 >> 10u));
  DEF_x__h13181 = (tUInt8)((tUInt8)255u & DEF_qcl2_inF_first____d274);
  DEF_qcl2_inF_first__74_BITS_39_TO_38___d281 = (tUInt8)(DEF_qcl2_inF_first____d274 >> 38u);
  DEF_qcl2_inF_first__74_BITS_29_TO_28___d279 = (tUInt8)((tUInt8)3u & (DEF_qcl2_inF_first____d274 >> 28u));
  DEF_qcl2_inF_first__74_BITS_19_TO_18___d277 = (tUInt8)((tUInt8)3u & (DEF_qcl2_inF_first____d274 >> 18u));
  DEF_qcl2_inF_first__74_BITS_9_TO_8___d275 = (tUInt8)((tUInt8)3u & (DEF_qcl2_inF_first____d274 >> 8u));
  switch (DEF_x__h13273) {
  case (tUInt8)0u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293 = DEF_x__h13181;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293 = DEF_x__h13182;
    break;
  case (tUInt8)2u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293 = DEF_x__h13183;
    break;
  case (tUInt8)3u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293 = DEF_x__h13184;
    break;
  default:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293 = (tUInt8)170u;
  }
  switch (DEF_x__h13273) {
  case (tUInt8)0u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_2_ETC___d307 = DEF_qcl2_inF_first__74_BITS_9_TO_8___d275 == (tUInt8)2u;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_2_ETC___d307 = DEF_qcl2_inF_first__74_BITS_19_TO_18___d277 == (tUInt8)2u;
    break;
  case (tUInt8)2u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_2_ETC___d307 = DEF_qcl2_inF_first__74_BITS_29_TO_28___d279 == (tUInt8)2u;
    break;
  case (tUInt8)3u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_2_ETC___d307 = DEF_qcl2_inF_first__74_BITS_39_TO_38___d281 == (tUInt8)2u;
    break;
  default:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_2_ETC___d307 = (tUInt8)0u;
  }
  switch (DEF_x__h13273) {
  case (tUInt8)0u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_1_ETC___d300 = DEF_qcl2_inF_first__74_BITS_9_TO_8___d275 == (tUInt8)1u;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_1_ETC___d300 = DEF_qcl2_inF_first__74_BITS_19_TO_18___d277 == (tUInt8)1u;
    break;
  case (tUInt8)2u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_1_ETC___d300 = DEF_qcl2_inF_first__74_BITS_29_TO_28___d279 == (tUInt8)1u;
    break;
  case (tUInt8)3u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_1_ETC___d300 = DEF_qcl2_inF_first__74_BITS_39_TO_38___d281 == (tUInt8)1u;
    break;
  default:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_1_ETC___d300 = (tUInt8)0u;
  }
  switch (DEF_x__h13273) {
  case (tUInt8)0u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285 = DEF_qcl2_inF_first__74_BITS_9_TO_8___d275 == (tUInt8)0u;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285 = DEF_qcl2_inF_first__74_BITS_19_TO_18___d277 == (tUInt8)0u;
    break;
  case (tUInt8)2u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285 = DEF_qcl2_inF_first__74_BITS_29_TO_28___d279 == (tUInt8)0u;
    break;
  case (tUInt8)3u:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285 = DEF_qcl2_inF_first__74_BITS_39_TO_38___d281 == (tUInt8)0u;
    break;
  default:
    DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285 = (tUInt8)0u;
  }
  DEF_IF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_E_ETC___d311 = DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285 ? 1023u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293)) : (DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_1_ETC___d300 ? 1023u & ((((tUInt32)((tUInt8)1u)) << 8u) | (tUInt32)(DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293)) : 1023u & ((((tUInt32)(DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_2_ETC___d307 ? (tUInt8)2u : (tUInt8)3u)) << 8u) | (tUInt32)(DEF_SEL_ARR_qcl2_inF_first__74_BITS_7_TO_0_88_qcl2_ETC___d293)));
  DEF_IF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_E_ETC___d287 = DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285 ? (tUInt8)3u & (DEF_x__h13273 + (tUInt8)1u) : (tUInt8)0u;
  DEF_qcl2_ptr_84_EQ_3_12_OR_NOT_SEL_ARR_qcl2_inF_fi_ETC___d314 = DEF_x__h13273 == (tUInt8)3u || !DEF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_EQ_0_ETC___d285;
  INST_qcl2_ptr.METH_write(DEF_IF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_E_ETC___d287);
  INST_qcl2_outF.METH_enq(DEF_IF_SEL_ARR_qcl2_inF_first__74_BITS_9_TO_8_75_E_ETC___d311);
  if (DEF_qcl2_ptr_84_EQ_3_12_OR_NOT_SEL_ARR_qcl2_inF_fi_ETC___d314)
    INST_qcl2_inF.METH_deq();
}

void MOD_mkHCrt_TB1::RL_mkConnectionGetPut_3()
{
  tUInt64 DEF_IF_crt2axi_crtS0_response_get_18_BITS_39_TO_38_ETC___d361;
  tUInt8 DEF_IF_crt2axi_crtS0_response_get_18_BITS_39_TO_38_ETC___d325;
  tUInt8 DEF_IF_crt2axi_crtS0_response_get_18_BITS_29_TO_28_ETC___d335;
  tUInt8 DEF_IF_crt2axi_crtS0_response_get_18_BITS_19_TO_18_ETC___d346;
  tUInt8 DEF_IF_crt2axi_crtS0_response_get_18_BITS_9_TO_8_5_ETC___d357;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_9_TO_8___d351;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_19_TO_18___d340;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_29_TO_28___d329;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_39_TO_38___d319;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_7_TO_0___d359;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_17_TO_10___d348;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_27_TO_20___d337;
  tUInt8 DEF_crt2axi_crtS0_response_get_18_BITS_37_TO_30___d327;
  tUInt64 DEF_crt2axi_crtS0_response_get___d318;
  tUInt64 DEF_AVMeth_crt2axi_crtS0_response_get;
  DEF_AVMeth_crt2axi_crtS0_response_get = INST_crt2axi.METH_crtS0_response_get();
  DEF_crt2axi_crtS0_response_get___d318 = DEF_AVMeth_crt2axi_crtS0_response_get;
  DEF_crt2axi_crtS0_response_get_18_BITS_37_TO_30___d327 = (tUInt8)((tUInt8)255u & (DEF_crt2axi_crtS0_response_get___d318 >> 30u));
  DEF_crt2axi_crtS0_response_get_18_BITS_27_TO_20___d337 = (tUInt8)((tUInt8)255u & (DEF_crt2axi_crtS0_response_get___d318 >> 20u));
  DEF_crt2axi_crtS0_response_get_18_BITS_17_TO_10___d348 = (tUInt8)((tUInt8)255u & (DEF_crt2axi_crtS0_response_get___d318 >> 10u));
  DEF_crt2axi_crtS0_response_get_18_BITS_7_TO_0___d359 = (tUInt8)((tUInt8)255u & DEF_crt2axi_crtS0_response_get___d318);
  DEF_crt2axi_crtS0_response_get_18_BITS_39_TO_38___d319 = (tUInt8)(DEF_crt2axi_crtS0_response_get___d318 >> 38u);
  DEF_crt2axi_crtS0_response_get_18_BITS_29_TO_28___d329 = (tUInt8)((tUInt8)3u & (DEF_crt2axi_crtS0_response_get___d318 >> 28u));
  DEF_crt2axi_crtS0_response_get_18_BITS_19_TO_18___d340 = (tUInt8)((tUInt8)3u & (DEF_crt2axi_crtS0_response_get___d318 >> 18u));
  DEF_crt2axi_crtS0_response_get_18_BITS_9_TO_8___d351 = (tUInt8)((tUInt8)3u & (DEF_crt2axi_crtS0_response_get___d318 >> 8u));
  switch (DEF_crt2axi_crtS0_response_get_18_BITS_9_TO_8___d351) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_9_TO_8_5_ETC___d357 = DEF_crt2axi_crtS0_response_get_18_BITS_9_TO_8___d351;
    break;
  default:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_9_TO_8_5_ETC___d357 = (tUInt8)3u;
  }
  switch (DEF_crt2axi_crtS0_response_get_18_BITS_19_TO_18___d340) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_19_TO_18_ETC___d346 = DEF_crt2axi_crtS0_response_get_18_BITS_19_TO_18___d340;
    break;
  default:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_19_TO_18_ETC___d346 = (tUInt8)3u;
  }
  switch (DEF_crt2axi_crtS0_response_get_18_BITS_29_TO_28___d329) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_29_TO_28_ETC___d335 = DEF_crt2axi_crtS0_response_get_18_BITS_29_TO_28___d329;
    break;
  default:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_29_TO_28_ETC___d335 = (tUInt8)3u;
  }
  switch (DEF_crt2axi_crtS0_response_get_18_BITS_39_TO_38___d319) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_39_TO_38_ETC___d325 = DEF_crt2axi_crtS0_response_get_18_BITS_39_TO_38___d319;
    break;
  default:
    DEF_IF_crt2axi_crtS0_response_get_18_BITS_39_TO_38_ETC___d325 = (tUInt8)3u;
  }
  DEF_IF_crt2axi_crtS0_response_get_18_BITS_39_TO_38_ETC___d361 = 1099511627775llu & ((((((((((tUInt64)(DEF_IF_crt2axi_crtS0_response_get_18_BITS_39_TO_38_ETC___d325)) << 38u) | (((tUInt64)(DEF_crt2axi_crtS0_response_get_18_BITS_39_TO_38___d319 == (tUInt8)0u || DEF_crt2axi_crtS0_response_get_18_BITS_39_TO_38___d319 == (tUInt8)1u ? DEF_crt2axi_crtS0_response_get_18_BITS_37_TO_30___d327 : DEF_crt2axi_crtS0_response_get_18_BITS_37_TO_30___d327)) << 30u)) | (((tUInt64)(DEF_IF_crt2axi_crtS0_response_get_18_BITS_29_TO_28_ETC___d335)) << 28u)) | (((tUInt64)(DEF_crt2axi_crtS0_response_get_18_BITS_29_TO_28___d329 == (tUInt8)0u || DEF_crt2axi_crtS0_response_get_18_BITS_29_TO_28___d329 == (tUInt8)1u ? DEF_crt2axi_crtS0_response_get_18_BITS_27_TO_20___d337 : DEF_crt2axi_crtS0_response_get_18_BITS_27_TO_20___d337)) << 20u)) | (((tUInt64)(DEF_IF_crt2axi_crtS0_response_get_18_BITS_19_TO_18_ETC___d346)) << 18u)) | (((tUInt64)(DEF_crt2axi_crtS0_response_get_18_BITS_19_TO_18___d340 == (tUInt8)0u || DEF_crt2axi_crtS0_response_get_18_BITS_19_TO_18___d340 == (tUInt8)1u ? DEF_crt2axi_crtS0_response_get_18_BITS_17_TO_10___d348 : DEF_crt2axi_crtS0_response_get_18_BITS_17_TO_10___d348)) << 10u)) | (((tUInt64)(DEF_IF_crt2axi_crtS0_response_get_18_BITS_9_TO_8_5_ETC___d357)) << 8u)) | (tUInt64)(DEF_crt2axi_crtS0_response_get_18_BITS_9_TO_8___d351 == (tUInt8)0u || DEF_crt2axi_crtS0_response_get_18_BITS_9_TO_8___d351 == (tUInt8)1u ? DEF_crt2axi_crtS0_response_get_18_BITS_7_TO_0___d359 : DEF_crt2axi_crtS0_response_get_18_BITS_7_TO_0___d359));
  INST_qcl2_inF.METH_enq(DEF_IF_crt2axi_crtS0_response_get_18_BITS_39_TO_38_ETC___d361);
}

void MOD_mkHCrt_TB1::RL_mkConnectionGetPut_4()
{
  tUInt32 DEF_IF_qcl2_outF_first__65_BITS_9_TO_8_66_EQ_0_67__ETC___d376;
  tUInt8 DEF_IF_qcl2_outF_first__65_BITS_9_TO_8_66_EQ_0_67__ETC___d372;
  tUInt8 DEF_qcl2_outF_first__65_BITS_9_TO_8___d366;
  tUInt8 DEF_qcl2_outF_first__65_BITS_7_TO_0___d374;
  tUInt32 DEF_qcl2_outF_first____d365;
  DEF_qcl2_outF_first____d365 = INST_qcl2_outF.METH_first();
  DEF_qcl2_outF_first__65_BITS_7_TO_0___d374 = (tUInt8)((tUInt8)255u & DEF_qcl2_outF_first____d365);
  DEF_qcl2_outF_first__65_BITS_9_TO_8___d366 = (tUInt8)(DEF_qcl2_outF_first____d365 >> 8u);
  switch (DEF_qcl2_outF_first__65_BITS_9_TO_8___d366) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_qcl2_outF_first__65_BITS_9_TO_8_66_EQ_0_67__ETC___d372 = DEF_qcl2_outF_first__65_BITS_9_TO_8___d366;
    break;
  default:
    DEF_IF_qcl2_outF_first__65_BITS_9_TO_8_66_EQ_0_67__ETC___d372 = (tUInt8)3u;
  }
  DEF_IF_qcl2_outF_first__65_BITS_9_TO_8_66_EQ_0_67__ETC___d376 = 1023u & ((((tUInt32)(DEF_IF_qcl2_outF_first__65_BITS_9_TO_8_66_EQ_0_67__ETC___d372)) << 8u) | (tUInt32)(DEF_qcl2_outF_first__65_BITS_9_TO_8___d366 == (tUInt8)0u || DEF_qcl2_outF_first__65_BITS_9_TO_8___d366 == (tUInt8)1u ? DEF_qcl2_outF_first__65_BITS_7_TO_0___d374 : DEF_qcl2_outF_first__65_BITS_7_TO_0___d374));
  INST_qcl2_outF.METH_deq();
  INST_l2P.METH_client_response_put(DEF_IF_qcl2_outF_first__65_BITS_9_TO_8_66_EQ_0_67__ETC___d376);
}

void MOD_mkHCrt_TB1::RL_mkConnectionGetPut_5()
{
  tUInt32 DEF_IF_l2P_server_response_get_80_BITS_9_TO_8_81_E_ETC___d391;
  tUInt8 DEF_IF_l2P_server_response_get_80_BITS_9_TO_8_81_E_ETC___d387;
  tUInt8 DEF_l2P_server_response_get_80_BITS_9_TO_8___d381;
  tUInt8 DEF_l2P_server_response_get_80_BITS_7_TO_0___d389;
  tUInt32 DEF_l2P_server_response_get___d380;
  tUInt32 DEF_AVMeth_l2P_server_response_get;
  DEF_AVMeth_l2P_server_response_get = INST_l2P.METH_server_response_get();
  DEF_l2P_server_response_get___d380 = DEF_AVMeth_l2P_server_response_get;
  DEF_l2P_server_response_get_80_BITS_7_TO_0___d389 = (tUInt8)((tUInt8)255u & DEF_l2P_server_response_get___d380);
  DEF_l2P_server_response_get_80_BITS_9_TO_8___d381 = (tUInt8)(DEF_l2P_server_response_get___d380 >> 8u);
  switch (DEF_l2P_server_response_get_80_BITS_9_TO_8___d381) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2P_server_response_get_80_BITS_9_TO_8_81_E_ETC___d387 = DEF_l2P_server_response_get_80_BITS_9_TO_8___d381;
    break;
  default:
    DEF_IF_l2P_server_response_get_80_BITS_9_TO_8_81_E_ETC___d387 = (tUInt8)3u;
  }
  DEF_IF_l2P_server_response_get_80_BITS_9_TO_8_81_E_ETC___d391 = 1023u & ((((tUInt32)(DEF_IF_l2P_server_response_get_80_BITS_9_TO_8_81_E_ETC___d387)) << 8u) | (tUInt32)(DEF_l2P_server_response_get_80_BITS_9_TO_8___d381 == (tUInt8)0u || DEF_l2P_server_response_get_80_BITS_9_TO_8___d381 == (tUInt8)1u ? DEF_l2P_server_response_get_80_BITS_7_TO_0___d389 : DEF_l2P_server_response_get_80_BITS_7_TO_0___d389));
  INST_l2ConsumeF.METH_enq(DEF_IF_l2P_server_response_get_80_BITS_9_TO_8_81_E_ETC___d391);
}

void MOD_mkHCrt_TB1::RL_chomp_l2()
{
  tUInt32 DEF_consumeCnt_93_PLUS_1___d394;
  tUInt8 DEF_IF_l2ConsumeF_first__97_BITS_9_TO_8_98_EQ_0_99_ETC___d403;
  tUInt8 DEF_l2ConsumeF_first__97_BITS_9_TO_8___d398;
  tUInt8 DEF_l2ConsumeF_first__97_BITS_7_TO_0___d402;
  tUInt32 DEF_l2ConsumeF_first____d397;
  tUInt32 DEF_b__h15100;
  tUInt32 DEF_unsigned_consumeCnt_93___d396;
  DEF_b__h15100 = INST_consumeCnt.METH_read();
  DEF_unsigned_consumeCnt_93___d396 = DEF_b__h15100;
  DEF_b__h15206 = INST_cycleCount.METH_read();
  DEF_unsigned_cycleCount_04___d405 = DEF_b__h15206;
  DEF_l2ConsumeF_first____d397 = INST_l2ConsumeF.METH_first();
  DEF_l2ConsumeF_first__97_BITS_7_TO_0___d402 = (tUInt8)((tUInt8)255u & DEF_l2ConsumeF_first____d397);
  DEF_l2ConsumeF_first__97_BITS_9_TO_8___d398 = (tUInt8)(DEF_l2ConsumeF_first____d397 >> 8u);
  DEF_IF_l2ConsumeF_first__97_BITS_9_TO_8_98_EQ_0_99_ETC___d403 = DEF_l2ConsumeF_first__97_BITS_9_TO_8___d398 == (tUInt8)0u || DEF_l2ConsumeF_first__97_BITS_9_TO_8___d398 == (tUInt8)1u ? DEF_l2ConsumeF_first__97_BITS_7_TO_0___d402 : DEF_l2ConsumeF_first__97_BITS_7_TO_0___d402;
  DEF_consumeCnt_93_PLUS_1___d394 = 65535u & (DEF_b__h15100 + 1u);
  INST_l2ConsumeF.METH_deq();
  INST_consumeCnt.METH_write(DEF_consumeCnt_93_PLUS_1___d394);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h15109 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl,
		   this,
		   "s,64,16,8,16",
		   &__str_literal_1,
		   DEF_v__h15109,
		   DEF_unsigned_consumeCnt_93___d396,
		   DEF_IF_l2ConsumeF_first__97_BITS_9_TO_8_98_EQ_0_99_ETC___d403,
		   DEF_unsigned_cycleCount_04___d405);
}

void MOD_mkHCrt_TB1::RL_doAlways()
{
  tUInt8 DEF_ARPROT__h16112;
  tUInt8 DEF_AWPROT__h15459;
  tUInt8 DEF_WSTRB__h15701;
  tUInt32 DEF_ARADDR__h16068;
  tUInt32 DEF_AWADDR__h15415;
  tUInt32 DEF_WDATA__h15657;
  tUInt8 DEF_crt2axi_axiM0_rdResp_ready____d425;
  tUInt8 DEF_crt2axi_axiM0_rdAddr_valid____d419;
  tUInt8 DEF_crt2axi_axiM0_wrResp_ready____d417;
  tUInt8 DEF_crt2axi_axiM0_wrData_valid____d411;
  tUInt8 DEF_crt2axi_axiM0_wrAddr_valid____d406;
  tUInt8 DEF_a4ls_sAWREADY____d407;
  tUInt8 DEF_a4ls_sWREADY____d412;
  tUInt8 DEF_a4ls_sBVALID____d416;
  tUInt8 DEF_a4ls_sARREADY____d420;
  tUInt8 DEF_a4ls_sRVALID____d424;
  tUInt8 DEF_arg_wresp__h15882;
  tUInt8 DEF_arg_rresp__h16332;
  tUInt32 DEF_arg_rdata__h16308;
  tUInt64 DEF_crt2axi_axiM0_rdAddr_data____d421;
  tUInt64 DEF_crt2axi_axiM0_wrAddr_data____d408;
  tUInt64 DEF_crt2axi_axiM0_wrData_data____d413;
  DEF_crt2axi_axiM0_wrData_data____d413 = INST_crt2axi.METH_axiM0_wrData_data();
  DEF_crt2axi_axiM0_wrAddr_data____d408 = INST_crt2axi.METH_axiM0_wrAddr_data();
  DEF_crt2axi_axiM0_rdAddr_data____d421 = INST_crt2axi.METH_axiM0_rdAddr_data();
  DEF_arg_rdata__h16308 = INST_a4ls.METH_sRDATA();
  DEF_arg_wresp__h15882 = INST_a4ls.METH_sBRESP();
  DEF_arg_rresp__h16332 = INST_a4ls.METH_sRRESP();
  DEF_a4ls_sRVALID____d424 = INST_a4ls.METH_sRVALID();
  DEF_a4ls_sARREADY____d420 = INST_a4ls.METH_sARREADY();
  DEF_a4ls_sBVALID____d416 = INST_a4ls.METH_sBVALID();
  DEF_a4ls_sWREADY____d412 = INST_a4ls.METH_sWREADY();
  DEF_a4ls_sAWREADY____d407 = INST_a4ls.METH_sAWREADY();
  DEF_crt2axi_axiM0_wrAddr_valid____d406 = INST_crt2axi.METH_axiM0_wrAddr_valid();
  DEF_crt2axi_axiM0_wrResp_ready____d417 = INST_crt2axi.METH_axiM0_wrResp_ready();
  DEF_crt2axi_axiM0_wrData_valid____d411 = INST_crt2axi.METH_axiM0_wrData_valid();
  DEF_crt2axi_axiM0_rdAddr_valid____d419 = INST_crt2axi.METH_axiM0_rdAddr_valid();
  DEF_crt2axi_axiM0_rdResp_ready____d425 = INST_crt2axi.METH_axiM0_rdResp_ready();
  DEF_WDATA__h15657 = (tUInt32)(DEF_crt2axi_axiM0_wrData_data____d413);
  DEF_ARADDR__h16068 = (tUInt32)(DEF_crt2axi_axiM0_rdAddr_data____d421);
  DEF_AWADDR__h15415 = (tUInt32)(DEF_crt2axi_axiM0_wrAddr_data____d408);
  DEF_WSTRB__h15701 = (tUInt8)(DEF_crt2axi_axiM0_wrData_data____d413 >> 32u);
  DEF_AWPROT__h15459 = (tUInt8)(DEF_crt2axi_axiM0_wrAddr_data____d408 >> 32u);
  DEF_ARPROT__h16112 = (tUInt8)(DEF_crt2axi_axiM0_rdAddr_data____d421 >> 32u);
  if (DEF_crt2axi_axiM0_wrAddr_valid____d406)
    INST_a4ls.METH_mAWVALID();
  if (DEF_a4ls_sAWREADY____d407)
    INST_a4lm_wrAddrRdy_w.METH_wset((tUInt8)1u);
  INST_a4ls.METH_mAWADDR(DEF_AWADDR__h15415);
  INST_a4ls.METH_mAWPROT(DEF_AWPROT__h15459);
  if (DEF_crt2axi_axiM0_wrData_valid____d411)
    INST_a4ls.METH_mWVALID();
  if (DEF_a4ls_sWREADY____d412)
    INST_a4lm_wrDataRdy_w.METH_wset((tUInt8)1u);
  INST_a4ls.METH_mWDATA(DEF_WDATA__h15657);
  INST_a4ls.METH_mWSTRB(DEF_WSTRB__h15701);
  if (DEF_a4ls_sBVALID____d416)
    INST_a4lm_wrRespVal_w.METH_wset((tUInt8)1u);
  if (DEF_crt2axi_axiM0_wrResp_ready____d417)
    INST_a4ls.METH_mBREADY();
  if (DEF_crt2axi_axiM0_rdAddr_valid____d419)
    INST_a4ls.METH_mARVALID();
  INST_a4lm_wrResp_w.METH_wset(DEF_arg_wresp__h15882);
  if (DEF_a4ls_sARREADY____d420)
    INST_a4lm_rdAddrRdy_w.METH_wset((tUInt8)1u);
  INST_a4ls.METH_mARADDR(DEF_ARADDR__h16068);
  INST_a4ls.METH_mARPROT(DEF_ARPROT__h16112);
  if (DEF_a4ls_sRVALID____d424)
    INST_a4lm_rdRespVal_w.METH_wset((tUInt8)1u);
  if (DEF_crt2axi_axiM0_rdResp_ready____d425)
    INST_a4ls.METH_mRREADY();
  INST_a4lm_rdData_w.METH_wset(DEF_arg_rdata__h16308);
  INST_a4lm_rdResp_w.METH_wset(DEF_arg_rresp__h16332);
}

void MOD_mkHCrt_TB1::RL_advance_cycleCount()
{
  tUInt32 DEF_cycleCount_04_PLUS_1___d428;
  DEF_b__h15206 = INST_cycleCount.METH_read();
  DEF_cycleCount_04_PLUS_1___d428 = 65535u & (DEF_b__h15206 + 1u);
  INST_cycleCount.METH_write(DEF_cycleCount_04_PLUS_1___d428);
}

void MOD_mkHCrt_TB1::RL_terminate()
{
  DEF_b__h15206 = INST_cycleCount.METH_read();
  DEF_unsigned_cycleCount_04___d405 = DEF_b__h15206;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h16417 = dollar_time(sim_hdl);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl,
		   this,
		   "s,64,16",
		   &__str_literal_2,
		   DEF_v__h16417,
		   DEF_unsigned_cycleCount_04___d405);
    dollar_finish(sim_hdl, "32", 1u);
  }
}


/* Methods */


/* Reset routines */

void MOD_mkHCrt_TB1::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_qcl2_ptr.reset_RST(ARG_rst_in);
  INST_qcl2_outF.reset_RST(ARG_rst_in);
  INST_qcl2_inF.reset_RST(ARG_rst_in);
  INST_qcF.reset_RST(ARG_rst_in);
  INST_l2qc_ptr.reset_RST(ARG_rst_in);
  INST_l2qc_outF.reset_RST(ARG_rst_in);
  INST_l2qc_inF.reset_RST(ARG_rst_in);
  INST_l2P.reset_RST_N(ARG_rst_in);
  INST_l2GenF.reset_RST(ARG_rst_in);
  INST_l2ConsumeF.reset_RST(ARG_rst_in);
  INST_gqPtr.reset_RST(ARG_rst_in);
  INST_gpPtr.reset_RST(ARG_rst_in);
  INST_gpPDU.reset_RST(ARG_rst_in);
  INST_gpL2Hdr.reset_RST(ARG_rst_in);
  INST_cycleCount.reset_RST(ARG_rst_in);
  INST_crt2axi.reset_RST_N(ARG_rst_in);
  INST_consumeCnt.reset_RST(ARG_rst_in);
  INST_a4ls.reset_ARESETN(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkHCrt_TB1::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkHCrt_TB1::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_a4lm_rdAddrRdy_w.dump_state(indent + 2u);
  INST_a4lm_rdData_w.dump_state(indent + 2u);
  INST_a4lm_rdRespVal_w.dump_state(indent + 2u);
  INST_a4lm_rdResp_w.dump_state(indent + 2u);
  INST_a4lm_wrAddrRdy_w.dump_state(indent + 2u);
  INST_a4lm_wrDataRdy_w.dump_state(indent + 2u);
  INST_a4lm_wrRespVal_w.dump_state(indent + 2u);
  INST_a4lm_wrResp_w.dump_state(indent + 2u);
  INST_a4ls.dump_state(indent + 2u);
  INST_consumeCnt.dump_state(indent + 2u);
  INST_crt2axi.dump_state(indent + 2u);
  INST_cycleCount.dump_state(indent + 2u);
  INST_gpDA.dump_state(indent + 2u);
  INST_gpL2Hdr.dump_state(indent + 2u);
  INST_gpPDU.dump_state(indent + 2u);
  INST_gpPtr.dump_state(indent + 2u);
  INST_gpSA.dump_state(indent + 2u);
  INST_gqPtr.dump_state(indent + 2u);
  INST_l2ConsumeF.dump_state(indent + 2u);
  INST_l2GenF.dump_state(indent + 2u);
  INST_l2P.dump_state(indent + 2u);
  INST_l2qc_inF.dump_state(indent + 2u);
  INST_l2qc_outF.dump_state(indent + 2u);
  INST_l2qc_ptr.dump_state(indent + 2u);
  INST_l2qc_sr.dump_state(indent + 2u);
  INST_qcF.dump_state(indent + 2u);
  INST_qcl2_inF.dump_state(indent + 2u);
  INST_qcl2_outF.dump_state(indent + 2u);
  INST_qcl2_ptr.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkHCrt_TB1::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 74u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_a4lm_doAlways", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_advance_cycleCount", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_chomp_l2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_doAlways", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_feed_hcrt_req", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2_gen_header", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2_gen_payload", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2qc_unfunnel", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_mkConnectionGetPut", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_mkConnectionGetPut_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_mkConnectionGetPut_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_mkConnectionGetPut_3", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_mkConnectionGetPut_4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_mkConnectionGetPut_5", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_qcl2_funnel", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_terminate", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_a4lm_doAlways", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_advance_cycleCount", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_chomp_l2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_doAlways", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_feed_hcrt_req", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2_gen_header", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2_gen_payload", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2qc_unfunnel", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_mkConnectionGetPut", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_mkConnectionGetPut_1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_mkConnectionGetPut_2", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_mkConnectionGetPut_3", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_mkConnectionGetPut_4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_mkConnectionGetPut_5", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_qcl2_funnel", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_terminate", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h15206", 16u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h7397", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h9394", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "gpPtr_6_EQ_0___d27", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "gpPtr_6_EQ_13___d28", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "gpPtr_6_EQ_14___d55", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "gpPtr__h2001", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "gqPtr_03_EQ_11___d125", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2qc_inF_first__66_BITS_9_TO_8___d167", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2qc_inF_first____d166", 10u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2qc_ptr_63_EQ_3___d164", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "unsigned_cycleCount_04___d405", 16u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h15109", 64u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h16417", 64u);
  num = INST_a4lm_rdAddrRdy_w.dump_VCD_defs(num);
  num = INST_a4lm_rdData_w.dump_VCD_defs(num);
  num = INST_a4lm_rdRespVal_w.dump_VCD_defs(num);
  num = INST_a4lm_rdResp_w.dump_VCD_defs(num);
  num = INST_a4lm_wrAddrRdy_w.dump_VCD_defs(num);
  num = INST_a4lm_wrDataRdy_w.dump_VCD_defs(num);
  num = INST_a4lm_wrRespVal_w.dump_VCD_defs(num);
  num = INST_a4lm_wrResp_w.dump_VCD_defs(num);
  num = INST_consumeCnt.dump_VCD_defs(num);
  num = INST_cycleCount.dump_VCD_defs(num);
  num = INST_gpDA.dump_VCD_defs(num);
  num = INST_gpL2Hdr.dump_VCD_defs(num);
  num = INST_gpPDU.dump_VCD_defs(num);
  num = INST_gpPtr.dump_VCD_defs(num);
  num = INST_gpSA.dump_VCD_defs(num);
  num = INST_gqPtr.dump_VCD_defs(num);
  num = INST_l2ConsumeF.dump_VCD_defs(num);
  num = INST_l2GenF.dump_VCD_defs(num);
  num = INST_l2qc_inF.dump_VCD_defs(num);
  num = INST_l2qc_outF.dump_VCD_defs(num);
  num = INST_l2qc_ptr.dump_VCD_defs(num);
  num = INST_l2qc_sr.dump_VCD_defs(num);
  num = INST_qcF.dump_VCD_defs(num);
  num = INST_qcl2_inF.dump_VCD_defs(num);
  num = INST_qcl2_outF.dump_VCD_defs(num);
  num = INST_qcl2_ptr.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_a4ls.dump_VCD_defs(l);
    num = INST_crt2axi.dump_VCD_defs(l);
    num = INST_l2P.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkHCrt_TB1::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkHCrt_TB1 &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkHCrt_TB1::vcd_defs(tVCDDumpType dt, MOD_mkHCrt_TB1 &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 16u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 10u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 16u);
    vcd_write_x(sim_hdl, num++, 64u);
    vcd_write_x(sim_hdl, num++, 64u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_a4lm_doAlways) != DEF_CAN_FIRE_RL_a4lm_doAlways)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_a4lm_doAlways, 1u);
	backing.DEF_CAN_FIRE_RL_a4lm_doAlways = DEF_CAN_FIRE_RL_a4lm_doAlways;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_advance_cycleCount) != DEF_CAN_FIRE_RL_advance_cycleCount)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_advance_cycleCount, 1u);
	backing.DEF_CAN_FIRE_RL_advance_cycleCount = DEF_CAN_FIRE_RL_advance_cycleCount;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_chomp_l2) != DEF_CAN_FIRE_RL_chomp_l2)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_chomp_l2, 1u);
	backing.DEF_CAN_FIRE_RL_chomp_l2 = DEF_CAN_FIRE_RL_chomp_l2;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_doAlways) != DEF_CAN_FIRE_RL_doAlways)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_doAlways, 1u);
	backing.DEF_CAN_FIRE_RL_doAlways = DEF_CAN_FIRE_RL_doAlways;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_feed_hcrt_req) != DEF_CAN_FIRE_RL_feed_hcrt_req)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_feed_hcrt_req, 1u);
	backing.DEF_CAN_FIRE_RL_feed_hcrt_req = DEF_CAN_FIRE_RL_feed_hcrt_req;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2_gen_header) != DEF_CAN_FIRE_RL_l2_gen_header)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2_gen_header, 1u);
	backing.DEF_CAN_FIRE_RL_l2_gen_header = DEF_CAN_FIRE_RL_l2_gen_header;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2_gen_payload) != DEF_CAN_FIRE_RL_l2_gen_payload)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2_gen_payload, 1u);
	backing.DEF_CAN_FIRE_RL_l2_gen_payload = DEF_CAN_FIRE_RL_l2_gen_payload;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2qc_unfunnel) != DEF_CAN_FIRE_RL_l2qc_unfunnel)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2qc_unfunnel, 1u);
	backing.DEF_CAN_FIRE_RL_l2qc_unfunnel = DEF_CAN_FIRE_RL_l2qc_unfunnel;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_mkConnectionGetPut) != DEF_CAN_FIRE_RL_mkConnectionGetPut)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_mkConnectionGetPut, 1u);
	backing.DEF_CAN_FIRE_RL_mkConnectionGetPut = DEF_CAN_FIRE_RL_mkConnectionGetPut;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_1) != DEF_CAN_FIRE_RL_mkConnectionGetPut_1)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_mkConnectionGetPut_1, 1u);
	backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_1 = DEF_CAN_FIRE_RL_mkConnectionGetPut_1;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_2) != DEF_CAN_FIRE_RL_mkConnectionGetPut_2)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_mkConnectionGetPut_2, 1u);
	backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_2 = DEF_CAN_FIRE_RL_mkConnectionGetPut_2;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_3) != DEF_CAN_FIRE_RL_mkConnectionGetPut_3)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_mkConnectionGetPut_3, 1u);
	backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_3 = DEF_CAN_FIRE_RL_mkConnectionGetPut_3;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_4) != DEF_CAN_FIRE_RL_mkConnectionGetPut_4)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_mkConnectionGetPut_4, 1u);
	backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_4 = DEF_CAN_FIRE_RL_mkConnectionGetPut_4;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_5) != DEF_CAN_FIRE_RL_mkConnectionGetPut_5)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_mkConnectionGetPut_5, 1u);
	backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_5 = DEF_CAN_FIRE_RL_mkConnectionGetPut_5;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_qcl2_funnel) != DEF_CAN_FIRE_RL_qcl2_funnel)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_qcl2_funnel, 1u);
	backing.DEF_CAN_FIRE_RL_qcl2_funnel = DEF_CAN_FIRE_RL_qcl2_funnel;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_terminate) != DEF_CAN_FIRE_RL_terminate)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_terminate, 1u);
	backing.DEF_CAN_FIRE_RL_terminate = DEF_CAN_FIRE_RL_terminate;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_a4lm_doAlways) != DEF_WILL_FIRE_RL_a4lm_doAlways)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_a4lm_doAlways, 1u);
	backing.DEF_WILL_FIRE_RL_a4lm_doAlways = DEF_WILL_FIRE_RL_a4lm_doAlways;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_advance_cycleCount) != DEF_WILL_FIRE_RL_advance_cycleCount)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_advance_cycleCount, 1u);
	backing.DEF_WILL_FIRE_RL_advance_cycleCount = DEF_WILL_FIRE_RL_advance_cycleCount;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_chomp_l2) != DEF_WILL_FIRE_RL_chomp_l2)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_chomp_l2, 1u);
	backing.DEF_WILL_FIRE_RL_chomp_l2 = DEF_WILL_FIRE_RL_chomp_l2;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_doAlways) != DEF_WILL_FIRE_RL_doAlways)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_doAlways, 1u);
	backing.DEF_WILL_FIRE_RL_doAlways = DEF_WILL_FIRE_RL_doAlways;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_feed_hcrt_req) != DEF_WILL_FIRE_RL_feed_hcrt_req)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_feed_hcrt_req, 1u);
	backing.DEF_WILL_FIRE_RL_feed_hcrt_req = DEF_WILL_FIRE_RL_feed_hcrt_req;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2_gen_header) != DEF_WILL_FIRE_RL_l2_gen_header)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2_gen_header, 1u);
	backing.DEF_WILL_FIRE_RL_l2_gen_header = DEF_WILL_FIRE_RL_l2_gen_header;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2_gen_payload) != DEF_WILL_FIRE_RL_l2_gen_payload)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2_gen_payload, 1u);
	backing.DEF_WILL_FIRE_RL_l2_gen_payload = DEF_WILL_FIRE_RL_l2_gen_payload;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2qc_unfunnel) != DEF_WILL_FIRE_RL_l2qc_unfunnel)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2qc_unfunnel, 1u);
	backing.DEF_WILL_FIRE_RL_l2qc_unfunnel = DEF_WILL_FIRE_RL_l2qc_unfunnel;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_mkConnectionGetPut) != DEF_WILL_FIRE_RL_mkConnectionGetPut)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_mkConnectionGetPut, 1u);
	backing.DEF_WILL_FIRE_RL_mkConnectionGetPut = DEF_WILL_FIRE_RL_mkConnectionGetPut;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_1) != DEF_WILL_FIRE_RL_mkConnectionGetPut_1)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_mkConnectionGetPut_1, 1u);
	backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_1 = DEF_WILL_FIRE_RL_mkConnectionGetPut_1;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_2) != DEF_WILL_FIRE_RL_mkConnectionGetPut_2)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_mkConnectionGetPut_2, 1u);
	backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_2 = DEF_WILL_FIRE_RL_mkConnectionGetPut_2;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_3) != DEF_WILL_FIRE_RL_mkConnectionGetPut_3)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_mkConnectionGetPut_3, 1u);
	backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_3 = DEF_WILL_FIRE_RL_mkConnectionGetPut_3;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_4) != DEF_WILL_FIRE_RL_mkConnectionGetPut_4)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_mkConnectionGetPut_4, 1u);
	backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_4 = DEF_WILL_FIRE_RL_mkConnectionGetPut_4;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_5) != DEF_WILL_FIRE_RL_mkConnectionGetPut_5)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_mkConnectionGetPut_5, 1u);
	backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_5 = DEF_WILL_FIRE_RL_mkConnectionGetPut_5;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_qcl2_funnel) != DEF_WILL_FIRE_RL_qcl2_funnel)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_qcl2_funnel, 1u);
	backing.DEF_WILL_FIRE_RL_qcl2_funnel = DEF_WILL_FIRE_RL_qcl2_funnel;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_terminate) != DEF_WILL_FIRE_RL_terminate)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_terminate, 1u);
	backing.DEF_WILL_FIRE_RL_terminate = DEF_WILL_FIRE_RL_terminate;
      }
      ++num;
      if ((backing.DEF_b__h15206) != DEF_b__h15206)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h15206, 16u);
	backing.DEF_b__h15206 = DEF_b__h15206;
      }
      ++num;
      if ((backing.DEF_b__h7397) != DEF_b__h7397)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h7397, 4u);
	backing.DEF_b__h7397 = DEF_b__h7397;
      }
      ++num;
      if ((backing.DEF_b__h9394) != DEF_b__h9394)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h9394, 2u);
	backing.DEF_b__h9394 = DEF_b__h9394;
      }
      ++num;
      if ((backing.DEF_gpPtr_6_EQ_0___d27) != DEF_gpPtr_6_EQ_0___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_gpPtr_6_EQ_0___d27, 1u);
	backing.DEF_gpPtr_6_EQ_0___d27 = DEF_gpPtr_6_EQ_0___d27;
      }
      ++num;
      if ((backing.DEF_gpPtr_6_EQ_13___d28) != DEF_gpPtr_6_EQ_13___d28)
      {
	vcd_write_val(sim_hdl, num, DEF_gpPtr_6_EQ_13___d28, 1u);
	backing.DEF_gpPtr_6_EQ_13___d28 = DEF_gpPtr_6_EQ_13___d28;
      }
      ++num;
      if ((backing.DEF_gpPtr_6_EQ_14___d55) != DEF_gpPtr_6_EQ_14___d55)
      {
	vcd_write_val(sim_hdl, num, DEF_gpPtr_6_EQ_14___d55, 1u);
	backing.DEF_gpPtr_6_EQ_14___d55 = DEF_gpPtr_6_EQ_14___d55;
      }
      ++num;
      if ((backing.DEF_gpPtr__h2001) != DEF_gpPtr__h2001)
      {
	vcd_write_val(sim_hdl, num, DEF_gpPtr__h2001, 4u);
	backing.DEF_gpPtr__h2001 = DEF_gpPtr__h2001;
      }
      ++num;
      if ((backing.DEF_gqPtr_03_EQ_11___d125) != DEF_gqPtr_03_EQ_11___d125)
      {
	vcd_write_val(sim_hdl, num, DEF_gqPtr_03_EQ_11___d125, 1u);
	backing.DEF_gqPtr_03_EQ_11___d125 = DEF_gqPtr_03_EQ_11___d125;
      }
      ++num;
      if ((backing.DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168) != DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168)
      {
	vcd_write_val(sim_hdl, num, DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168, 1u);
	backing.DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168 = DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168;
      }
      ++num;
      if ((backing.DEF_l2qc_inF_first__66_BITS_9_TO_8___d167) != DEF_l2qc_inF_first__66_BITS_9_TO_8___d167)
      {
	vcd_write_val(sim_hdl, num, DEF_l2qc_inF_first__66_BITS_9_TO_8___d167, 2u);
	backing.DEF_l2qc_inF_first__66_BITS_9_TO_8___d167 = DEF_l2qc_inF_first__66_BITS_9_TO_8___d167;
      }
      ++num;
      if ((backing.DEF_l2qc_inF_first____d166) != DEF_l2qc_inF_first____d166)
      {
	vcd_write_val(sim_hdl, num, DEF_l2qc_inF_first____d166, 10u);
	backing.DEF_l2qc_inF_first____d166 = DEF_l2qc_inF_first____d166;
      }
      ++num;
      if ((backing.DEF_l2qc_ptr_63_EQ_3___d164) != DEF_l2qc_ptr_63_EQ_3___d164)
      {
	vcd_write_val(sim_hdl, num, DEF_l2qc_ptr_63_EQ_3___d164, 1u);
	backing.DEF_l2qc_ptr_63_EQ_3___d164 = DEF_l2qc_ptr_63_EQ_3___d164;
      }
      ++num;
      if ((backing.DEF_unsigned_cycleCount_04___d405) != DEF_unsigned_cycleCount_04___d405)
      {
	vcd_write_val(sim_hdl, num, DEF_unsigned_cycleCount_04___d405, 16u);
	backing.DEF_unsigned_cycleCount_04___d405 = DEF_unsigned_cycleCount_04___d405;
      }
      ++num;
      if ((backing.DEF_v__h15109) != DEF_v__h15109)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h15109, 64u);
	backing.DEF_v__h15109 = DEF_v__h15109;
      }
      ++num;
      if ((backing.DEF_v__h16417) != DEF_v__h16417)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h16417, 64u);
	backing.DEF_v__h16417 = DEF_v__h16417;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_a4lm_doAlways, 1u);
      backing.DEF_CAN_FIRE_RL_a4lm_doAlways = DEF_CAN_FIRE_RL_a4lm_doAlways;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_advance_cycleCount, 1u);
      backing.DEF_CAN_FIRE_RL_advance_cycleCount = DEF_CAN_FIRE_RL_advance_cycleCount;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_chomp_l2, 1u);
      backing.DEF_CAN_FIRE_RL_chomp_l2 = DEF_CAN_FIRE_RL_chomp_l2;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_doAlways, 1u);
      backing.DEF_CAN_FIRE_RL_doAlways = DEF_CAN_FIRE_RL_doAlways;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_feed_hcrt_req, 1u);
      backing.DEF_CAN_FIRE_RL_feed_hcrt_req = DEF_CAN_FIRE_RL_feed_hcrt_req;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2_gen_header, 1u);
      backing.DEF_CAN_FIRE_RL_l2_gen_header = DEF_CAN_FIRE_RL_l2_gen_header;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2_gen_payload, 1u);
      backing.DEF_CAN_FIRE_RL_l2_gen_payload = DEF_CAN_FIRE_RL_l2_gen_payload;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2qc_unfunnel, 1u);
      backing.DEF_CAN_FIRE_RL_l2qc_unfunnel = DEF_CAN_FIRE_RL_l2qc_unfunnel;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_mkConnectionGetPut, 1u);
      backing.DEF_CAN_FIRE_RL_mkConnectionGetPut = DEF_CAN_FIRE_RL_mkConnectionGetPut;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_mkConnectionGetPut_1, 1u);
      backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_1 = DEF_CAN_FIRE_RL_mkConnectionGetPut_1;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_mkConnectionGetPut_2, 1u);
      backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_2 = DEF_CAN_FIRE_RL_mkConnectionGetPut_2;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_mkConnectionGetPut_3, 1u);
      backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_3 = DEF_CAN_FIRE_RL_mkConnectionGetPut_3;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_mkConnectionGetPut_4, 1u);
      backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_4 = DEF_CAN_FIRE_RL_mkConnectionGetPut_4;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_mkConnectionGetPut_5, 1u);
      backing.DEF_CAN_FIRE_RL_mkConnectionGetPut_5 = DEF_CAN_FIRE_RL_mkConnectionGetPut_5;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_qcl2_funnel, 1u);
      backing.DEF_CAN_FIRE_RL_qcl2_funnel = DEF_CAN_FIRE_RL_qcl2_funnel;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_terminate, 1u);
      backing.DEF_CAN_FIRE_RL_terminate = DEF_CAN_FIRE_RL_terminate;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_a4lm_doAlways, 1u);
      backing.DEF_WILL_FIRE_RL_a4lm_doAlways = DEF_WILL_FIRE_RL_a4lm_doAlways;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_advance_cycleCount, 1u);
      backing.DEF_WILL_FIRE_RL_advance_cycleCount = DEF_WILL_FIRE_RL_advance_cycleCount;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_chomp_l2, 1u);
      backing.DEF_WILL_FIRE_RL_chomp_l2 = DEF_WILL_FIRE_RL_chomp_l2;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_doAlways, 1u);
      backing.DEF_WILL_FIRE_RL_doAlways = DEF_WILL_FIRE_RL_doAlways;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_feed_hcrt_req, 1u);
      backing.DEF_WILL_FIRE_RL_feed_hcrt_req = DEF_WILL_FIRE_RL_feed_hcrt_req;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2_gen_header, 1u);
      backing.DEF_WILL_FIRE_RL_l2_gen_header = DEF_WILL_FIRE_RL_l2_gen_header;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2_gen_payload, 1u);
      backing.DEF_WILL_FIRE_RL_l2_gen_payload = DEF_WILL_FIRE_RL_l2_gen_payload;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2qc_unfunnel, 1u);
      backing.DEF_WILL_FIRE_RL_l2qc_unfunnel = DEF_WILL_FIRE_RL_l2qc_unfunnel;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_mkConnectionGetPut, 1u);
      backing.DEF_WILL_FIRE_RL_mkConnectionGetPut = DEF_WILL_FIRE_RL_mkConnectionGetPut;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_mkConnectionGetPut_1, 1u);
      backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_1 = DEF_WILL_FIRE_RL_mkConnectionGetPut_1;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_mkConnectionGetPut_2, 1u);
      backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_2 = DEF_WILL_FIRE_RL_mkConnectionGetPut_2;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_mkConnectionGetPut_3, 1u);
      backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_3 = DEF_WILL_FIRE_RL_mkConnectionGetPut_3;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_mkConnectionGetPut_4, 1u);
      backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_4 = DEF_WILL_FIRE_RL_mkConnectionGetPut_4;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_mkConnectionGetPut_5, 1u);
      backing.DEF_WILL_FIRE_RL_mkConnectionGetPut_5 = DEF_WILL_FIRE_RL_mkConnectionGetPut_5;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_qcl2_funnel, 1u);
      backing.DEF_WILL_FIRE_RL_qcl2_funnel = DEF_WILL_FIRE_RL_qcl2_funnel;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_terminate, 1u);
      backing.DEF_WILL_FIRE_RL_terminate = DEF_WILL_FIRE_RL_terminate;
      vcd_write_val(sim_hdl, num++, DEF_b__h15206, 16u);
      backing.DEF_b__h15206 = DEF_b__h15206;
      vcd_write_val(sim_hdl, num++, DEF_b__h7397, 4u);
      backing.DEF_b__h7397 = DEF_b__h7397;
      vcd_write_val(sim_hdl, num++, DEF_b__h9394, 2u);
      backing.DEF_b__h9394 = DEF_b__h9394;
      vcd_write_val(sim_hdl, num++, DEF_gpPtr_6_EQ_0___d27, 1u);
      backing.DEF_gpPtr_6_EQ_0___d27 = DEF_gpPtr_6_EQ_0___d27;
      vcd_write_val(sim_hdl, num++, DEF_gpPtr_6_EQ_13___d28, 1u);
      backing.DEF_gpPtr_6_EQ_13___d28 = DEF_gpPtr_6_EQ_13___d28;
      vcd_write_val(sim_hdl, num++, DEF_gpPtr_6_EQ_14___d55, 1u);
      backing.DEF_gpPtr_6_EQ_14___d55 = DEF_gpPtr_6_EQ_14___d55;
      vcd_write_val(sim_hdl, num++, DEF_gpPtr__h2001, 4u);
      backing.DEF_gpPtr__h2001 = DEF_gpPtr__h2001;
      vcd_write_val(sim_hdl, num++, DEF_gqPtr_03_EQ_11___d125, 1u);
      backing.DEF_gqPtr_03_EQ_11___d125 = DEF_gqPtr_03_EQ_11___d125;
      vcd_write_val(sim_hdl, num++, DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168, 1u);
      backing.DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168 = DEF_l2qc_inF_first__66_BITS_9_TO_8_67_EQ_0___d168;
      vcd_write_val(sim_hdl, num++, DEF_l2qc_inF_first__66_BITS_9_TO_8___d167, 2u);
      backing.DEF_l2qc_inF_first__66_BITS_9_TO_8___d167 = DEF_l2qc_inF_first__66_BITS_9_TO_8___d167;
      vcd_write_val(sim_hdl, num++, DEF_l2qc_inF_first____d166, 10u);
      backing.DEF_l2qc_inF_first____d166 = DEF_l2qc_inF_first____d166;
      vcd_write_val(sim_hdl, num++, DEF_l2qc_ptr_63_EQ_3___d164, 1u);
      backing.DEF_l2qc_ptr_63_EQ_3___d164 = DEF_l2qc_ptr_63_EQ_3___d164;
      vcd_write_val(sim_hdl, num++, DEF_unsigned_cycleCount_04___d405, 16u);
      backing.DEF_unsigned_cycleCount_04___d405 = DEF_unsigned_cycleCount_04___d405;
      vcd_write_val(sim_hdl, num++, DEF_v__h15109, 64u);
      backing.DEF_v__h15109 = DEF_v__h15109;
      vcd_write_val(sim_hdl, num++, DEF_v__h16417, 64u);
      backing.DEF_v__h16417 = DEF_v__h16417;
    }
}

void MOD_mkHCrt_TB1::vcd_prims(tVCDDumpType dt, MOD_mkHCrt_TB1 &backing)
{
  INST_a4lm_rdAddrRdy_w.dump_VCD(dt, backing.INST_a4lm_rdAddrRdy_w);
  INST_a4lm_rdData_w.dump_VCD(dt, backing.INST_a4lm_rdData_w);
  INST_a4lm_rdRespVal_w.dump_VCD(dt, backing.INST_a4lm_rdRespVal_w);
  INST_a4lm_rdResp_w.dump_VCD(dt, backing.INST_a4lm_rdResp_w);
  INST_a4lm_wrAddrRdy_w.dump_VCD(dt, backing.INST_a4lm_wrAddrRdy_w);
  INST_a4lm_wrDataRdy_w.dump_VCD(dt, backing.INST_a4lm_wrDataRdy_w);
  INST_a4lm_wrRespVal_w.dump_VCD(dt, backing.INST_a4lm_wrRespVal_w);
  INST_a4lm_wrResp_w.dump_VCD(dt, backing.INST_a4lm_wrResp_w);
  INST_consumeCnt.dump_VCD(dt, backing.INST_consumeCnt);
  INST_cycleCount.dump_VCD(dt, backing.INST_cycleCount);
  INST_gpDA.dump_VCD(dt, backing.INST_gpDA);
  INST_gpL2Hdr.dump_VCD(dt, backing.INST_gpL2Hdr);
  INST_gpPDU.dump_VCD(dt, backing.INST_gpPDU);
  INST_gpPtr.dump_VCD(dt, backing.INST_gpPtr);
  INST_gpSA.dump_VCD(dt, backing.INST_gpSA);
  INST_gqPtr.dump_VCD(dt, backing.INST_gqPtr);
  INST_l2ConsumeF.dump_VCD(dt, backing.INST_l2ConsumeF);
  INST_l2GenF.dump_VCD(dt, backing.INST_l2GenF);
  INST_l2qc_inF.dump_VCD(dt, backing.INST_l2qc_inF);
  INST_l2qc_outF.dump_VCD(dt, backing.INST_l2qc_outF);
  INST_l2qc_ptr.dump_VCD(dt, backing.INST_l2qc_ptr);
  INST_l2qc_sr.dump_VCD(dt, backing.INST_l2qc_sr);
  INST_qcF.dump_VCD(dt, backing.INST_qcF);
  INST_qcl2_inF.dump_VCD(dt, backing.INST_qcl2_inF);
  INST_qcl2_outF.dump_VCD(dt, backing.INST_qcl2_outF);
  INST_qcl2_ptr.dump_VCD(dt, backing.INST_qcl2_ptr);
}

void MOD_mkHCrt_TB1::vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkHCrt_TB1 &backing)
{
  INST_a4ls.dump_VCD(dt, levels, backing.INST_a4ls);
  INST_crt2axi.dump_VCD(dt, levels, backing.INST_crt2axi);
  INST_l2P.dump_VCD(dt, levels, backing.INST_l2P);
}
