/*
 * Generated by Bluespec Compiler, version 2013.01.beta5 (build 30325, 2013-01-23)
 * 
 * On Thu Feb  7 15:40:03 EST 2013
 * 
 */
#include "bluesim_primitives.h"
#include "mkL2Proc.h"


/* Constructor */
MOD_mkL2Proc::MOD_mkL2Proc(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_dgRxF(simHdl, "dgRxF", this, 10u, 2u, 1u, 0u),
    INST_dgTxF(simHdl, "dgTxF", this, 10u, 2u, 1u, 0u),
    INST_egDA(simHdl, "egDA", this, 48u),
    INST_egL2Hdr(simHdl, "egL2Hdr", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_egPDU(simHdl, "egPDU", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_egPtr(simHdl, "egPtr", this, 4u, (tUInt8)0u, (tUInt8)0u),
    INST_egSA(simHdl, "egSA", this, 48u),
    INST_igDA(simHdl, "igDA", this, 48u),
    INST_igL2Hdr(simHdl, "igL2Hdr", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_igPDU(simHdl, "igPDU", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_igPtr(simHdl, "igPtr", this, 4u, (tUInt8)0u, (tUInt8)0u),
    INST_igSA(simHdl, "igSA", this, 48u),
    INST_igSAF(simHdl, "igSAF", this, 48u, 2u, 1u, 0u),
    INST_igSR(simHdl, "igSR", this, 48u),
    INST_igTyp(simHdl, "igTyp", this, 16u),
    INST_l2Egress(simHdl, "l2Egress", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_l2Egress_1(simHdl, "l2Egress_1", this, 1u, (tUInt8)0u),
    INST_l2Ingress(simHdl, "l2Ingress", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_l2Ingress_1(simHdl, "l2Ingress_1", this, 1u, (tUInt8)0u),
    INST_l2RxF(simHdl, "l2RxF", this, 10u, 2u, 1u, 0u),
    INST_l2TxF(simHdl, "l2TxF", this, 10u, 2u, 1u, 0u),
    INST_uMAddr(simHdl, "uMAddr", this, 48u, 43839021184llu, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  PORT_EN_server_request_put = false;
  PORT_EN_server_response_get = false;
  PORT_EN_client_request_get = false;
  PORT_EN_client_response_put = false;
  PORT_EN_macAddr = false;
  PORT_server_request_put = 0u;
  PORT_client_response_put = 0u;
  PORT_macAddr_u = 0llu;
  PORT_RDY_server_request_put = false;
  PORT_server_response_get = 0u;
  PORT_RDY_server_response_get = false;
  PORT_client_request_get = 0u;
  PORT_RDY_client_request_get = false;
  PORT_RDY_client_response_put = false;
  PORT_RDY_macAddr = false;
  PORT_l2Rx = false;
  PORT_RDY_l2Rx = false;
  PORT_l2Tx = false;
  PORT_RDY_l2Tx = false;
  symbol_count = 74u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkL2Proc::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h1816", SYM_DEF, &DEF_b__h1816, 4u);
  init_symbol(&symbols[1u], "b__h5667", SYM_DEF, &DEF_b__h5667, 4u);
  init_symbol(&symbols[2u],
	      "CAN_FIRE_client_request_get",
	      SYM_DEF,
	      &DEF_CAN_FIRE_client_request_get,
	      1u);
  init_symbol(&symbols[3u],
	      "CAN_FIRE_client_response_put",
	      SYM_DEF,
	      &DEF_CAN_FIRE_client_response_put,
	      1u);
  init_symbol(&symbols[4u], "CAN_FIRE_l2Rx", SYM_DEF, &DEF_CAN_FIRE_l2Rx, 1u);
  init_symbol(&symbols[5u], "CAN_FIRE_l2Tx", SYM_DEF, &DEF_CAN_FIRE_l2Tx, 1u);
  init_symbol(&symbols[6u], "CAN_FIRE_macAddr", SYM_DEF, &DEF_CAN_FIRE_macAddr, 1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_l2_egress_header",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2_egress_header,
	      1u);
  init_symbol(&symbols[8u],
	      "CAN_FIRE_RL_l2_egress_payload",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2_egress_payload,
	      1u);
  init_symbol(&symbols[9u],
	      "CAN_FIRE_RL_l2_ingress_header",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2_ingress_header,
	      1u);
  init_symbol(&symbols[10u],
	      "CAN_FIRE_RL_l2_ingress_payload",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2_ingress_payload,
	      1u);
  init_symbol(&symbols[11u],
	      "CAN_FIRE_RL_l2Egress__dreg_update",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2Egress__dreg_update,
	      1u);
  init_symbol(&symbols[12u],
	      "CAN_FIRE_RL_l2Ingress__dreg_update",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_l2Ingress__dreg_update,
	      1u);
  init_symbol(&symbols[13u],
	      "CAN_FIRE_server_request_put",
	      SYM_DEF,
	      &DEF_CAN_FIRE_server_request_put,
	      1u);
  init_symbol(&symbols[14u],
	      "CAN_FIRE_server_response_get",
	      SYM_DEF,
	      &DEF_CAN_FIRE_server_response_get,
	      1u);
  init_symbol(&symbols[15u], "client_request_get", SYM_PORT, &PORT_client_request_get, 10u);
  init_symbol(&symbols[16u], "client_response_put", SYM_PORT, &PORT_client_response_put, 10u);
  init_symbol(&symbols[17u], "dgRxF", SYM_MODULE, &INST_dgRxF);
  init_symbol(&symbols[18u], "dgTxF", SYM_MODULE, &INST_dgTxF);
  init_symbol(&symbols[19u], "EN_client_request_get", SYM_PORT, &PORT_EN_client_request_get, 1u);
  init_symbol(&symbols[20u], "EN_client_response_put", SYM_PORT, &PORT_EN_client_response_put, 1u);
  init_symbol(&symbols[21u], "EN_macAddr", SYM_PORT, &PORT_EN_macAddr, 1u);
  init_symbol(&symbols[22u], "EN_server_request_put", SYM_PORT, &PORT_EN_server_request_put, 1u);
  init_symbol(&symbols[23u], "EN_server_response_get", SYM_PORT, &PORT_EN_server_response_get, 1u);
  init_symbol(&symbols[24u], "egDA", SYM_MODULE, &INST_egDA);
  init_symbol(&symbols[25u], "egL2Hdr", SYM_MODULE, &INST_egL2Hdr);
  init_symbol(&symbols[26u], "egPDU", SYM_MODULE, &INST_egPDU);
  init_symbol(&symbols[27u], "egPtr", SYM_MODULE, &INST_egPtr);
  init_symbol(&symbols[28u], "egSA", SYM_MODULE, &INST_egSA);
  init_symbol(&symbols[29u], "igDA", SYM_MODULE, &INST_igDA);
  init_symbol(&symbols[30u], "igL2Hdr", SYM_MODULE, &INST_igL2Hdr);
  init_symbol(&symbols[31u], "igPDU", SYM_MODULE, &INST_igPDU);
  init_symbol(&symbols[32u], "igPDU__h5515", SYM_DEF, &DEF_igPDU__h5515, 1u);
  init_symbol(&symbols[33u], "igPtr", SYM_MODULE, &INST_igPtr);
  init_symbol(&symbols[34u], "igSA", SYM_MODULE, &INST_igSA);
  init_symbol(&symbols[35u], "igSAF", SYM_MODULE, &INST_igSAF);
  init_symbol(&symbols[36u], "igSR", SYM_MODULE, &INST_igSR);
  init_symbol(&symbols[37u], "igTyp", SYM_MODULE, &INST_igTyp);
  init_symbol(&symbols[38u], "l2Egress", SYM_MODULE, &INST_l2Egress);
  init_symbol(&symbols[39u], "l2Egress_1", SYM_MODULE, &INST_l2Egress_1);
  init_symbol(&symbols[40u], "l2Ingress", SYM_MODULE, &INST_l2Ingress);
  init_symbol(&symbols[41u], "l2Ingress_1", SYM_MODULE, &INST_l2Ingress_1);
  init_symbol(&symbols[42u], "l2Rx", SYM_PORT, &PORT_l2Rx, 1u);
  init_symbol(&symbols[43u], "l2RxF", SYM_MODULE, &INST_l2RxF);
  init_symbol(&symbols[44u], "l2Tx", SYM_PORT, &PORT_l2Tx, 1u);
  init_symbol(&symbols[45u], "l2TxF", SYM_MODULE, &INST_l2TxF);
  init_symbol(&symbols[46u], "macAddr_u", SYM_PORT, &PORT_macAddr_u, 48u);
  init_symbol(&symbols[47u], "RDY_client_request_get", SYM_PORT, &PORT_RDY_client_request_get, 1u);
  init_symbol(&symbols[48u], "RDY_client_response_put", SYM_PORT, &PORT_RDY_client_response_put, 1u);
  init_symbol(&symbols[49u], "RDY_l2Rx", SYM_PORT, &PORT_RDY_l2Rx, 1u);
  init_symbol(&symbols[50u], "RDY_l2Tx", SYM_PORT, &PORT_RDY_l2Tx, 1u);
  init_symbol(&symbols[51u], "RDY_macAddr", SYM_PORT, &PORT_RDY_macAddr, 1u);
  init_symbol(&symbols[52u], "RDY_server_request_put", SYM_PORT, &PORT_RDY_server_request_put, 1u);
  init_symbol(&symbols[53u], "RDY_server_response_get", SYM_PORT, &PORT_RDY_server_response_get, 1u);
  init_symbol(&symbols[54u], "RL_l2_egress_header", SYM_RULE);
  init_symbol(&symbols[55u], "RL_l2_egress_payload", SYM_RULE);
  init_symbol(&symbols[56u], "RL_l2_ingress_header", SYM_RULE);
  init_symbol(&symbols[57u], "RL_l2_ingress_payload", SYM_RULE);
  init_symbol(&symbols[58u], "RL_l2Egress__dreg_update", SYM_RULE);
  init_symbol(&symbols[59u], "RL_l2Ingress__dreg_update", SYM_RULE);
  init_symbol(&symbols[60u], "server_request_put", SYM_PORT, &PORT_server_request_put, 10u);
  init_symbol(&symbols[61u], "server_response_get", SYM_PORT, &PORT_server_response_get, 10u);
  init_symbol(&symbols[62u], "uMAddr", SYM_MODULE, &INST_uMAddr);
  init_symbol(&symbols[63u],
	      "WILL_FIRE_client_request_get",
	      SYM_DEF,
	      &DEF_WILL_FIRE_client_request_get,
	      1u);
  init_symbol(&symbols[64u],
	      "WILL_FIRE_client_response_put",
	      SYM_DEF,
	      &DEF_WILL_FIRE_client_response_put,
	      1u);
  init_symbol(&symbols[65u], "WILL_FIRE_macAddr", SYM_DEF, &DEF_WILL_FIRE_macAddr, 1u);
  init_symbol(&symbols[66u],
	      "WILL_FIRE_RL_l2_egress_header",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2_egress_header,
	      1u);
  init_symbol(&symbols[67u],
	      "WILL_FIRE_RL_l2_egress_payload",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2_egress_payload,
	      1u);
  init_symbol(&symbols[68u],
	      "WILL_FIRE_RL_l2_ingress_header",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2_ingress_header,
	      1u);
  init_symbol(&symbols[69u],
	      "WILL_FIRE_RL_l2_ingress_payload",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2_ingress_payload,
	      1u);
  init_symbol(&symbols[70u],
	      "WILL_FIRE_RL_l2Egress__dreg_update",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2Egress__dreg_update,
	      1u);
  init_symbol(&symbols[71u],
	      "WILL_FIRE_RL_l2Ingress__dreg_update",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_l2Ingress__dreg_update,
	      1u);
  init_symbol(&symbols[72u],
	      "WILL_FIRE_server_request_put",
	      SYM_DEF,
	      &DEF_WILL_FIRE_server_request_put,
	      1u);
  init_symbol(&symbols[73u],
	      "WILL_FIRE_server_response_get",
	      SYM_DEF,
	      &DEF_WILL_FIRE_server_response_get,
	      1u);
}


/* Rule actions */

void MOD_mkL2Proc::RL_l2Ingress__dreg_update()
{
  tUInt8 DEF_l2Ingress_1_whas_AND_l2Ingress_1_wget___d3;
  DEF_l2Ingress_1_whas_AND_l2Ingress_1_wget___d3 = INST_l2Ingress_1.METH_whas() && INST_l2Ingress_1.METH_wget();
  INST_l2Ingress.METH_write(DEF_l2Ingress_1_whas_AND_l2Ingress_1_wget___d3);
}

void MOD_mkL2Proc::RL_l2Egress__dreg_update()
{
  tUInt8 DEF_l2Egress_1_whas_AND_l2Egress_1_wget___d6;
  DEF_l2Egress_1_whas_AND_l2Egress_1_wget___d6 = INST_l2Egress_1.METH_whas() && INST_l2Egress_1.METH_wget();
  INST_l2Egress.METH_write(DEF_l2Egress_1_whas_AND_l2Egress_1_wget___d6);
}

void MOD_mkL2Proc::RL_l2_ingress_header()
{
  tUInt64 DEF_x__h3364;
  tUInt8 DEF_igDA_4_EQ_0xFFFFFFFFFFFF_5_OR_igDA_4_EQ_uMAddr_ETC___d41;
  tUInt8 DEF_igPtr_EQ_5___d31;
  tUInt8 DEF_igPtr_EQ_13___d20;
  tUInt32 DEF_x__h5310;
  tUInt8 DEF_IF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_9_O_ETC___d23;
  tUInt8 DEF_igSR_BITS_7_TO_0___h3210;
  tUInt64 DEF_y__h5413;
  tUInt64 DEF_x__h5412;
  tUInt64 DEF_igSR__h3209;
  DEF_igSR__h3209 = INST_igSR.METH_read();
  DEF_x__h5412 = INST_igDA.METH_read();
  DEF_y__h5413 = INST_uMAddr.METH_read();
  DEF_l2RxF_first____d16 = INST_l2RxF.METH_first();
  DEF_igSR_BITS_7_TO_0___h3210 = (tUInt8)((tUInt8)255u & DEF_igSR__h3209);
  DEF_b__h1816 = INST_igPtr.METH_read();
  DEF_l2RxF_first__6_BITS_7_TO_0___d28 = (tUInt8)((tUInt8)255u & DEF_l2RxF_first____d16);
  DEF_l2RxF_first__6_BITS_9_TO_8___d17 = (tUInt8)(DEF_l2RxF_first____d16 >> 8u);
  DEF_igPtr_EQ_13___d20 = DEF_b__h1816 == (tUInt8)13u;
  DEF_igPtr_EQ_11___d9 = DEF_b__h1816 == (tUInt8)11u;
  DEF_igPtr_EQ_5___d31 = DEF_b__h1816 == (tUInt8)5u;
  DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18 = DEF_l2RxF_first__6_BITS_9_TO_8___d17 == (tUInt8)0u;
  DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19 = !DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18;
  DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29 = DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18 || DEF_l2RxF_first__6_BITS_9_TO_8___d17 == (tUInt8)1u ? DEF_l2RxF_first__6_BITS_7_TO_0___d28 : DEF_l2RxF_first__6_BITS_7_TO_0___d28;
  DEF_IF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_9_O_ETC___d23 = DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19 || DEF_igPtr_EQ_13___d20 ? (tUInt8)0u : (tUInt8)15u & (DEF_b__h1816 + (tUInt8)1u);
  DEF_x__h5310 = 65535u & ((((tUInt32)(DEF_igSR_BITS_7_TO_0___h3210)) << 8u) | (tUInt32)(DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29));
  DEF_igDA_4_EQ_0xFFFFFFFFFFFF_5_OR_igDA_4_EQ_uMAddr_ETC___d41 = (DEF_x__h5412 == 281474976710655llu || DEF_x__h5412 == DEF_y__h5413) && (DEF_igPtr_EQ_13___d20 && DEF_x__h5310 == 61522u);
  DEF_x__h3364 = 281474976710655llu & ((((tUInt64)(1099511627775llu & DEF_igSR__h3209)) << 8u) | (tUInt64)(DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29));
  INST_l2Ingress_1.METH_wset((tUInt8)1u);
  INST_igPtr.METH_write(DEF_IF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_9_O_ETC___d23);
  INST_l2RxF.METH_deq();
  INST_igSR.METH_write(DEF_x__h3364);
  if (DEF_igPtr_EQ_5___d31)
    INST_igDA.METH_write(DEF_x__h3364);
  if (DEF_igPtr_EQ_11___d9)
    INST_igSA.METH_write(DEF_x__h3364);
  if (DEF_igPtr_EQ_11___d9)
    INST_igSAF.METH_enq(DEF_x__h3364);
  if (DEF_igPtr_EQ_13___d20)
    INST_igTyp.METH_write(DEF_x__h5310);
  INST_igPDU.METH_write(DEF_igDA_4_EQ_0xFFFFFFFFFFFF_5_OR_igDA_4_EQ_uMAddr_ETC___d41);
  if (DEF_igPtr_EQ_13___d20)
    INST_igL2Hdr.METH_write((tUInt8)0u);
}

void MOD_mkL2Proc::RL_l2_ingress_payload()
{
  tUInt32 DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d53;
  tUInt8 DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d52;
  DEF_l2RxF_first____d16 = INST_l2RxF.METH_first();
  DEF_igPDU__h5515 = INST_igPDU.METH_read();
  DEF_l2RxF_first__6_BITS_7_TO_0___d28 = (tUInt8)((tUInt8)255u & DEF_l2RxF_first____d16);
  DEF_l2RxF_first__6_BITS_9_TO_8___d17 = (tUInt8)(DEF_l2RxF_first____d16 >> 8u);
  switch (DEF_l2RxF_first__6_BITS_9_TO_8___d17) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d52 = DEF_l2RxF_first__6_BITS_9_TO_8___d17;
    break;
  default:
    DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d52 = (tUInt8)3u;
  }
  DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18 = DEF_l2RxF_first__6_BITS_9_TO_8___d17 == (tUInt8)0u;
  DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19 = !DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18;
  DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29 = DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18 || DEF_l2RxF_first__6_BITS_9_TO_8___d17 == (tUInt8)1u ? DEF_l2RxF_first__6_BITS_7_TO_0___d28 : DEF_l2RxF_first__6_BITS_7_TO_0___d28;
  DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d53 = 1023u & ((((tUInt32)(DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d52)) << 8u) | (tUInt32)(DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29));
  INST_l2Ingress_1.METH_wset((tUInt8)1u);
  INST_l2RxF.METH_deq();
  if (DEF_igPDU__h5515)
    INST_dgRxF.METH_enq(DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d53);
  INST_igL2Hdr.METH_write(DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19);
}

void MOD_mkL2Proc::RL_l2_egress_header()
{
  tUInt8 DEF_egPtr_4_PLUS_1___d101;
  tUInt8 DEF_NOT_egPtr_4_EQ_0_5_27_AND_egPtr_4_EQ_1_3_OR_eg_ETC___d131;
  tUInt8 DEF_egPtr_4_EQ_1___d63;
  tUInt8 DEF_egPtr_4_EQ_2___d64;
  tUInt8 DEF_egPtr_4_EQ_3___d66;
  tUInt8 DEF_egPtr_4_EQ_4___d68;
  tUInt8 DEF_egPtr_4_EQ_5___d70;
  tUInt8 DEF_egPtr_4_EQ_6___d72;
  tUInt32 DEF__0_CONCAT_egDA_04_BITS_47_TO_40_06___d132;
  tUInt32 DEF_IF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_ETC___d136;
  tUInt32 DEF__0_CONCAT_egSA_22_BITS_47_TO_40_24___d133;
  tUInt64 DEF_IF_egPtr_4_EQ_0_5_THEN_igSAF_first__03_ELSE_eg_ETC___d108;
  tUInt64 DEF_IF_egPtr_4_EQ_0_5_THEN_43839021184_ELSE_egSA_2_ETC___d126;
  tUInt8 DEF_egDA_BITS_47_TO_40___h7336;
  tUInt8 DEF_egSA_BITS_47_TO_40___h7688;
  tUInt64 DEF_egDA__h9882;
  tUInt64 DEF_egSA__h11023;
  tUInt8 DEF_egPtr_4_EQ_0_5_OR_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_ETC___d102;
  tUInt8 DEF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_4__ETC___d73;
  tUInt8 DEF_egPtr_4_EQ_7_4_OR_egPtr_4_EQ_8_5_6_OR_egPtr_4__ETC___d84;
  tUInt8 DEF_egPtr_4_EQ_0_5_OR_NOT_egPtr_4_EQ_1_3_09_AND_NO_ETC___d121;
  DEF_egSA__h11023 = INST_egSA.METH_read();
  DEF_egDA__h9882 = INST_egDA.METH_read();
  DEF_b__h5667 = INST_egPtr.METH_read();
  DEF_egPtr_4_EQ_7_4_OR_egPtr_4_EQ_8_5_6_OR_egPtr_4__ETC___d84 = ((((DEF_b__h5667 == (tUInt8)7u || DEF_b__h5667 == (tUInt8)8u) || DEF_b__h5667 == (tUInt8)9u) || DEF_b__h5667 == (tUInt8)10u) || DEF_b__h5667 == (tUInt8)11u) || DEF_b__h5667 == (tUInt8)12u;
  DEF_egSA_BITS_47_TO_40___h7688 = (tUInt8)(DEF_egSA__h11023 >> 40u);
  DEF_egDA_BITS_47_TO_40___h7336 = (tUInt8)(DEF_egDA__h9882 >> 40u);
  DEF_egPtr_4_EQ_0___d55 = DEF_b__h5667 == (tUInt8)0u;
  DEF_IF_egPtr_4_EQ_0_5_THEN_43839021184_ELSE_egSA_2_ETC___d126 = DEF_egPtr_4_EQ_0___d55 ? 43839021184llu : 281474976710655llu & ((((tUInt64)(1099511627775llu & DEF_egSA__h11023)) << 8u) | (tUInt64)(DEF_egSA_BITS_47_TO_40___h7688));
  DEF_IF_egPtr_4_EQ_0_5_THEN_igSAF_first__03_ELSE_eg_ETC___d108 = DEF_egPtr_4_EQ_0___d55 ? INST_igSAF.METH_first() : 281474976710655llu & ((((tUInt64)(1099511627775llu & DEF_egDA__h9882)) << 8u) | (tUInt64)(DEF_egDA_BITS_47_TO_40___h7336));
  DEF__0_CONCAT_egSA_22_BITS_47_TO_40_24___d133 = 1023u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_egSA_BITS_47_TO_40___h7688));
  DEF__0_CONCAT_egDA_04_BITS_47_TO_40_06___d132 = 1023u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_egDA_BITS_47_TO_40___h7336));
  switch (DEF_b__h5667) {
  case (tUInt8)1u:
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
    DEF_IF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_ETC___d136 = DEF__0_CONCAT_egDA_04_BITS_47_TO_40_06___d132;
    break;
  case (tUInt8)7u:
  case (tUInt8)8u:
  case (tUInt8)9u:
  case (tUInt8)10u:
  case (tUInt8)11u:
  case (tUInt8)12u:
    DEF_IF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_ETC___d136 = DEF__0_CONCAT_egSA_22_BITS_47_TO_40_24___d133;
    break;
  case (tUInt8)13u:
    DEF_IF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_ETC___d136 = 240u;
    break;
  default:
    DEF_IF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_ETC___d136 = 82u;
  }
  DEF_egPtr_4_EQ_13___d57 = DEF_b__h5667 == (tUInt8)13u;
  DEF_egPtr_4_EQ_14___d86 = DEF_b__h5667 == (tUInt8)14u;
  DEF_egPtr_4_EQ_6___d72 = DEF_b__h5667 == (tUInt8)6u;
  DEF_egPtr_4_EQ_5___d70 = DEF_b__h5667 == (tUInt8)5u;
  DEF_egPtr_4_EQ_4___d68 = DEF_b__h5667 == (tUInt8)4u;
  DEF_egPtr_4_EQ_3___d66 = DEF_b__h5667 == (tUInt8)3u;
  DEF_egPtr_4_EQ_2___d64 = DEF_b__h5667 == (tUInt8)2u;
  DEF_egPtr_4_EQ_1___d63 = DEF_b__h5667 == (tUInt8)1u;
  DEF_egPtr_4_EQ_0_5_OR_NOT_egPtr_4_EQ_1_3_09_AND_NO_ETC___d121 = DEF_egPtr_4_EQ_0___d55 || ((((((!DEF_egPtr_4_EQ_1___d63 && !DEF_egPtr_4_EQ_2___d64) && !DEF_egPtr_4_EQ_3___d66) && !DEF_egPtr_4_EQ_4___d68) && !DEF_egPtr_4_EQ_5___d70) && !DEF_egPtr_4_EQ_6___d72) && DEF_egPtr_4_EQ_7_4_OR_egPtr_4_EQ_8_5_6_OR_egPtr_4__ETC___d84);
  DEF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_4__ETC___d73 = ((((DEF_egPtr_4_EQ_1___d63 || DEF_egPtr_4_EQ_2___d64) || DEF_egPtr_4_EQ_3___d66) || DEF_egPtr_4_EQ_4___d68) || DEF_egPtr_4_EQ_5___d70) || DEF_egPtr_4_EQ_6___d72;
  DEF_egPtr_4_EQ_0_5_OR_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_ETC___d102 = DEF_egPtr_4_EQ_0___d55 || DEF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_4__ETC___d73;
  DEF_NOT_egPtr_4_EQ_0_5_27_AND_egPtr_4_EQ_1_3_OR_eg_ETC___d131 = !DEF_egPtr_4_EQ_0___d55 && (DEF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_4__ETC___d73 || (DEF_egPtr_4_EQ_7_4_OR_egPtr_4_EQ_8_5_6_OR_egPtr_4__ETC___d84 || (DEF_egPtr_4_EQ_13___d57 || DEF_egPtr_4_EQ_14___d86)));
  DEF_egPtr_4_PLUS_1___d101 = (tUInt8)15u & (DEF_b__h5667 + (tUInt8)1u);
  INST_l2Egress_1.METH_wset((tUInt8)1u);
  INST_egPtr.METH_write(DEF_egPtr_4_PLUS_1___d101);
  if (DEF_egPtr_4_EQ_0_5_OR_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_ETC___d102)
    INST_egDA.METH_write(DEF_IF_egPtr_4_EQ_0_5_THEN_igSAF_first__03_ELSE_eg_ETC___d108);
  if (DEF_egPtr_4_EQ_0_5_OR_NOT_egPtr_4_EQ_1_3_09_AND_NO_ETC___d121)
    INST_egSA.METH_write(DEF_IF_egPtr_4_EQ_0_5_THEN_43839021184_ELSE_egSA_2_ETC___d126);
  if (DEF_egPtr_4_EQ_0___d55)
    INST_igSAF.METH_deq();
  if (DEF_NOT_egPtr_4_EQ_0_5_27_AND_egPtr_4_EQ_1_3_OR_eg_ETC___d131)
    INST_l2TxF.METH_enq(DEF_IF_egPtr_4_EQ_1_3_OR_egPtr_4_EQ_2_4_5_OR_egPtr_ETC___d136);
  if (DEF_egPtr_4_EQ_14___d86)
    INST_egPDU.METH_write((tUInt8)1u);
}

void MOD_mkL2Proc::RL_l2_egress_payload()
{
  tUInt32 DEF_IF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42_OR_d_ETC___d151;
  tUInt8 DEF_NOT_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42___d152;
  tUInt8 DEF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0___d142;
  tUInt8 DEF_IF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42_OR_d_ETC___d147;
  tUInt8 DEF_dgTxF_first__40_BITS_9_TO_8___d141;
  tUInt8 DEF_dgTxF_first__40_BITS_7_TO_0___d149;
  tUInt32 DEF_dgTxF_first____d140;
  DEF_dgTxF_first____d140 = INST_dgTxF.METH_first();
  DEF_dgTxF_first__40_BITS_7_TO_0___d149 = (tUInt8)((tUInt8)255u & DEF_dgTxF_first____d140);
  DEF_dgTxF_first__40_BITS_9_TO_8___d141 = (tUInt8)(DEF_dgTxF_first____d140 >> 8u);
  switch (DEF_dgTxF_first__40_BITS_9_TO_8___d141) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42_OR_d_ETC___d147 = DEF_dgTxF_first__40_BITS_9_TO_8___d141;
    break;
  default:
    DEF_IF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42_OR_d_ETC___d147 = (tUInt8)3u;
  }
  DEF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0___d142 = DEF_dgTxF_first__40_BITS_9_TO_8___d141 == (tUInt8)0u;
  DEF_NOT_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42___d152 = !DEF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0___d142;
  DEF_IF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42_OR_d_ETC___d151 = 1023u & ((((tUInt32)(DEF_IF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42_OR_d_ETC___d147)) << 8u) | (tUInt32)(DEF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0___d142 || DEF_dgTxF_first__40_BITS_9_TO_8___d141 == (tUInt8)1u ? DEF_dgTxF_first__40_BITS_7_TO_0___d149 : DEF_dgTxF_first__40_BITS_7_TO_0___d149));
  INST_l2Egress_1.METH_wset((tUInt8)1u);
  INST_dgTxF.METH_deq();
  INST_l2TxF.METH_enq(DEF_IF_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42_OR_d_ETC___d151);
  if (DEF_NOT_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42___d152)
    INST_egPDU.METH_write((tUInt8)0u);
  if (DEF_NOT_dgTxF_first__40_BITS_9_TO_8_41_EQ_0_42___d152)
    INST_egPtr.METH_write((tUInt8)0u);
}


/* Methods */

void MOD_mkL2Proc::METH_server_request_put(tUInt32 ARG_server_request_put)
{
  tUInt32 DEF_IF_server_request_put_BITS_9_TO_8_53_EQ_0_54_O_ETC___d163;
  tUInt8 DEF_IF_server_request_put_BITS_9_TO_8_53_EQ_0_54_O_ETC___d159;
  tUInt8 DEF_server_request_put_BITS_9_TO_8___d153;
  tUInt8 DEF_server_request_put_BITS_7_TO_0___d161;
  PORT_EN_server_request_put = (tUInt8)1u;
  DEF_WILL_FIRE_server_request_put = (tUInt8)1u;
  PORT_server_request_put = ARG_server_request_put;
  DEF_server_request_put_BITS_7_TO_0___d161 = (tUInt8)((tUInt8)255u & ARG_server_request_put);
  DEF_server_request_put_BITS_9_TO_8___d153 = (tUInt8)(ARG_server_request_put >> 8u);
  switch (DEF_server_request_put_BITS_9_TO_8___d153) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_server_request_put_BITS_9_TO_8_53_EQ_0_54_O_ETC___d159 = DEF_server_request_put_BITS_9_TO_8___d153;
    break;
  default:
    DEF_IF_server_request_put_BITS_9_TO_8_53_EQ_0_54_O_ETC___d159 = (tUInt8)3u;
  }
  DEF_IF_server_request_put_BITS_9_TO_8_53_EQ_0_54_O_ETC___d163 = 1023u & ((((tUInt32)(DEF_IF_server_request_put_BITS_9_TO_8_53_EQ_0_54_O_ETC___d159)) << 8u) | (tUInt32)(DEF_server_request_put_BITS_9_TO_8___d153 == (tUInt8)0u || DEF_server_request_put_BITS_9_TO_8___d153 == (tUInt8)1u ? DEF_server_request_put_BITS_7_TO_0___d161 : DEF_server_request_put_BITS_7_TO_0___d161));
  INST_l2RxF.METH_enq(DEF_IF_server_request_put_BITS_9_TO_8_53_EQ_0_54_O_ETC___d163);
}

tUInt8 MOD_mkL2Proc::METH_RDY_server_request_put()
{
  DEF_CAN_FIRE_server_request_put = INST_l2RxF.METH_i_notFull();
  PORT_RDY_server_request_put = DEF_CAN_FIRE_server_request_put;
  return PORT_RDY_server_request_put;
}

tUInt32 MOD_mkL2Proc::METH_server_response_get()
{
  tUInt8 DEF_IF_l2TxF_first__64_BITS_9_TO_8_65_EQ_0_66_OR_l_ETC___d171;
  tUInt8 DEF_IF_l2TxF_first__64_BITS_9_TO_8_65_EQ_0_66_OR_l_ETC___d174;
  tUInt8 DEF_l2TxF_first__64_BITS_9_TO_8___d165;
  tUInt8 DEF_l2TxF_first__64_BITS_7_TO_0___d173;
  tUInt32 DEF_l2TxF_first____d164;
  PORT_EN_server_response_get = (tUInt8)1u;
  DEF_WILL_FIRE_server_response_get = (tUInt8)1u;
  DEF_l2TxF_first____d164 = INST_l2TxF.METH_first();
  DEF_l2TxF_first__64_BITS_7_TO_0___d173 = (tUInt8)((tUInt8)255u & DEF_l2TxF_first____d164);
  DEF_l2TxF_first__64_BITS_9_TO_8___d165 = (tUInt8)(DEF_l2TxF_first____d164 >> 8u);
  DEF_IF_l2TxF_first__64_BITS_9_TO_8_65_EQ_0_66_OR_l_ETC___d174 = DEF_l2TxF_first__64_BITS_9_TO_8___d165 == (tUInt8)0u || DEF_l2TxF_first__64_BITS_9_TO_8___d165 == (tUInt8)1u ? DEF_l2TxF_first__64_BITS_7_TO_0___d173 : DEF_l2TxF_first__64_BITS_7_TO_0___d173;
  switch (DEF_l2TxF_first__64_BITS_9_TO_8___d165) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_l2TxF_first__64_BITS_9_TO_8_65_EQ_0_66_OR_l_ETC___d171 = DEF_l2TxF_first__64_BITS_9_TO_8___d165;
    break;
  default:
    DEF_IF_l2TxF_first__64_BITS_9_TO_8_65_EQ_0_66_OR_l_ETC___d171 = (tUInt8)3u;
  }
  INST_l2TxF.METH_deq();
  PORT_server_response_get = 1023u & ((((tUInt32)(DEF_IF_l2TxF_first__64_BITS_9_TO_8_65_EQ_0_66_OR_l_ETC___d171)) << 8u) | (tUInt32)(DEF_IF_l2TxF_first__64_BITS_9_TO_8_65_EQ_0_66_OR_l_ETC___d174));
  return PORT_server_response_get;
}

tUInt8 MOD_mkL2Proc::METH_RDY_server_response_get()
{
  DEF_CAN_FIRE_server_response_get = INST_l2TxF.METH_i_notEmpty();
  PORT_RDY_server_response_get = DEF_CAN_FIRE_server_response_get;
  return PORT_RDY_server_response_get;
}

tUInt32 MOD_mkL2Proc::METH_client_request_get()
{
  tUInt8 DEF_IF_dgRxF_first__75_BITS_9_TO_8_76_EQ_0_77_OR_d_ETC___d182;
  tUInt8 DEF_IF_dgRxF_first__75_BITS_9_TO_8_76_EQ_0_77_OR_d_ETC___d185;
  tUInt8 DEF_dgRxF_first__75_BITS_9_TO_8___d176;
  tUInt8 DEF_dgRxF_first__75_BITS_7_TO_0___d184;
  tUInt32 DEF_dgRxF_first____d175;
  PORT_EN_client_request_get = (tUInt8)1u;
  DEF_WILL_FIRE_client_request_get = (tUInt8)1u;
  DEF_dgRxF_first____d175 = INST_dgRxF.METH_first();
  DEF_dgRxF_first__75_BITS_7_TO_0___d184 = (tUInt8)((tUInt8)255u & DEF_dgRxF_first____d175);
  DEF_dgRxF_first__75_BITS_9_TO_8___d176 = (tUInt8)(DEF_dgRxF_first____d175 >> 8u);
  DEF_IF_dgRxF_first__75_BITS_9_TO_8_76_EQ_0_77_OR_d_ETC___d185 = DEF_dgRxF_first__75_BITS_9_TO_8___d176 == (tUInt8)0u || DEF_dgRxF_first__75_BITS_9_TO_8___d176 == (tUInt8)1u ? DEF_dgRxF_first__75_BITS_7_TO_0___d184 : DEF_dgRxF_first__75_BITS_7_TO_0___d184;
  switch (DEF_dgRxF_first__75_BITS_9_TO_8___d176) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_dgRxF_first__75_BITS_9_TO_8_76_EQ_0_77_OR_d_ETC___d182 = DEF_dgRxF_first__75_BITS_9_TO_8___d176;
    break;
  default:
    DEF_IF_dgRxF_first__75_BITS_9_TO_8_76_EQ_0_77_OR_d_ETC___d182 = (tUInt8)3u;
  }
  INST_dgRxF.METH_deq();
  PORT_client_request_get = 1023u & ((((tUInt32)(DEF_IF_dgRxF_first__75_BITS_9_TO_8_76_EQ_0_77_OR_d_ETC___d182)) << 8u) | (tUInt32)(DEF_IF_dgRxF_first__75_BITS_9_TO_8_76_EQ_0_77_OR_d_ETC___d185));
  return PORT_client_request_get;
}

tUInt8 MOD_mkL2Proc::METH_RDY_client_request_get()
{
  DEF_CAN_FIRE_client_request_get = INST_dgRxF.METH_i_notEmpty();
  PORT_RDY_client_request_get = DEF_CAN_FIRE_client_request_get;
  return PORT_RDY_client_request_get;
}

void MOD_mkL2Proc::METH_client_response_put(tUInt32 ARG_client_response_put)
{
  tUInt32 DEF_IF_client_response_put_BITS_9_TO_8_86_EQ_0_87__ETC___d196;
  tUInt8 DEF_IF_client_response_put_BITS_9_TO_8_86_EQ_0_87__ETC___d192;
  tUInt8 DEF_client_response_put_BITS_9_TO_8___d186;
  tUInt8 DEF_client_response_put_BITS_7_TO_0___d194;
  PORT_EN_client_response_put = (tUInt8)1u;
  DEF_WILL_FIRE_client_response_put = (tUInt8)1u;
  PORT_client_response_put = ARG_client_response_put;
  DEF_client_response_put_BITS_7_TO_0___d194 = (tUInt8)((tUInt8)255u & ARG_client_response_put);
  DEF_client_response_put_BITS_9_TO_8___d186 = (tUInt8)(ARG_client_response_put >> 8u);
  switch (DEF_client_response_put_BITS_9_TO_8___d186) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)2u:
    DEF_IF_client_response_put_BITS_9_TO_8_86_EQ_0_87__ETC___d192 = DEF_client_response_put_BITS_9_TO_8___d186;
    break;
  default:
    DEF_IF_client_response_put_BITS_9_TO_8_86_EQ_0_87__ETC___d192 = (tUInt8)3u;
  }
  DEF_IF_client_response_put_BITS_9_TO_8_86_EQ_0_87__ETC___d196 = 1023u & ((((tUInt32)(DEF_IF_client_response_put_BITS_9_TO_8_86_EQ_0_87__ETC___d192)) << 8u) | (tUInt32)(DEF_client_response_put_BITS_9_TO_8___d186 == (tUInt8)0u || DEF_client_response_put_BITS_9_TO_8___d186 == (tUInt8)1u ? DEF_client_response_put_BITS_7_TO_0___d194 : DEF_client_response_put_BITS_7_TO_0___d194));
  INST_dgTxF.METH_enq(DEF_IF_client_response_put_BITS_9_TO_8_86_EQ_0_87__ETC___d196);
}

tUInt8 MOD_mkL2Proc::METH_RDY_client_response_put()
{
  DEF_CAN_FIRE_client_response_put = INST_dgTxF.METH_i_notFull();
  PORT_RDY_client_response_put = DEF_CAN_FIRE_client_response_put;
  return PORT_RDY_client_response_put;
}

void MOD_mkL2Proc::METH_macAddr(tUInt64 ARG_macAddr_u)
{
  PORT_EN_macAddr = (tUInt8)1u;
  DEF_WILL_FIRE_macAddr = (tUInt8)1u;
  PORT_macAddr_u = ARG_macAddr_u;
  INST_uMAddr.METH_write(ARG_macAddr_u);
}

tUInt8 MOD_mkL2Proc::METH_RDY_macAddr()
{
  DEF_CAN_FIRE_macAddr = (tUInt8)1u;
  PORT_RDY_macAddr = DEF_CAN_FIRE_macAddr;
  return PORT_RDY_macAddr;
}

tUInt8 MOD_mkL2Proc::METH_l2Rx()
{
  PORT_l2Rx = INST_l2Ingress.METH_read();
  return PORT_l2Rx;
}

tUInt8 MOD_mkL2Proc::METH_RDY_l2Rx()
{
  DEF_CAN_FIRE_l2Rx = (tUInt8)1u;
  PORT_RDY_l2Rx = DEF_CAN_FIRE_l2Rx;
  return PORT_RDY_l2Rx;
}

tUInt8 MOD_mkL2Proc::METH_l2Tx()
{
  PORT_l2Tx = INST_l2Egress.METH_read();
  return PORT_l2Tx;
}

tUInt8 MOD_mkL2Proc::METH_RDY_l2Tx()
{
  DEF_CAN_FIRE_l2Tx = (tUInt8)1u;
  PORT_RDY_l2Tx = DEF_CAN_FIRE_l2Tx;
  return PORT_RDY_l2Tx;
}


/* Reset routines */

void MOD_mkL2Proc::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_uMAddr.reset_RST(ARG_rst_in);
  INST_l2TxF.reset_RST(ARG_rst_in);
  INST_l2RxF.reset_RST(ARG_rst_in);
  INST_l2Ingress.reset_RST(ARG_rst_in);
  INST_l2Egress.reset_RST(ARG_rst_in);
  INST_igSAF.reset_RST(ARG_rst_in);
  INST_igPtr.reset_RST(ARG_rst_in);
  INST_igPDU.reset_RST(ARG_rst_in);
  INST_igL2Hdr.reset_RST(ARG_rst_in);
  INST_egPtr.reset_RST(ARG_rst_in);
  INST_egPDU.reset_RST(ARG_rst_in);
  INST_egL2Hdr.reset_RST(ARG_rst_in);
  INST_dgTxF.reset_RST(ARG_rst_in);
  INST_dgRxF.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkL2Proc::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkL2Proc::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_dgRxF.dump_state(indent + 2u);
  INST_dgTxF.dump_state(indent + 2u);
  INST_egDA.dump_state(indent + 2u);
  INST_egL2Hdr.dump_state(indent + 2u);
  INST_egPDU.dump_state(indent + 2u);
  INST_egPtr.dump_state(indent + 2u);
  INST_egSA.dump_state(indent + 2u);
  INST_igDA.dump_state(indent + 2u);
  INST_igL2Hdr.dump_state(indent + 2u);
  INST_igPDU.dump_state(indent + 2u);
  INST_igPtr.dump_state(indent + 2u);
  INST_igSA.dump_state(indent + 2u);
  INST_igSAF.dump_state(indent + 2u);
  INST_igSR.dump_state(indent + 2u);
  INST_igTyp.dump_state(indent + 2u);
  INST_l2Egress.dump_state(indent + 2u);
  INST_l2Egress_1.dump_state(indent + 2u);
  INST_l2Ingress.dump_state(indent + 2u);
  INST_l2Ingress_1.dump_state(indent + 2u);
  INST_l2RxF.dump_state(indent + 2u);
  INST_l2TxF.dump_state(indent + 2u);
  INST_uMAddr.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkL2Proc::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 79u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2Egress__dreg_update", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2Ingress__dreg_update", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2_egress_header", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2_egress_payload", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2_ingress_header", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_l2_ingress_payload", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_client_request_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_client_response_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_l2Rx", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_l2Tx", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_macAddr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_server_request_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_server_response_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2Egress__dreg_update", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2Ingress__dreg_update", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2_egress_header", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2_egress_payload", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2_ingress_header", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_l2_ingress_payload", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_client_request_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_client_response_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_macAddr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_server_request_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_server_response_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h1816", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h5667", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "egPtr_4_EQ_0___d55", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "egPtr_4_EQ_13___d57", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "egPtr_4_EQ_14___d86", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "igPDU__h5515", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "igPtr_EQ_11___d9", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2RxF_first__6_BITS_7_TO_0___d28", 8u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2RxF_first__6_BITS_9_TO_8___d17", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2RxF_first____d16", 10u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_client_request_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_client_response_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_macAddr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_server_request_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_server_response_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_client_request_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_client_response_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_l2Rx", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_l2Tx", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_macAddr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_server_request_put", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_server_response_get", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "client_request_get", 10u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "client_response_put", 10u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2Rx", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "l2Tx", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "macAddr_u", 48u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "server_request_put", 10u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "server_response_get", 10u);
  num = INST_dgRxF.dump_VCD_defs(num);
  num = INST_dgTxF.dump_VCD_defs(num);
  num = INST_egDA.dump_VCD_defs(num);
  num = INST_egL2Hdr.dump_VCD_defs(num);
  num = INST_egPDU.dump_VCD_defs(num);
  num = INST_egPtr.dump_VCD_defs(num);
  num = INST_egSA.dump_VCD_defs(num);
  num = INST_igDA.dump_VCD_defs(num);
  num = INST_igL2Hdr.dump_VCD_defs(num);
  num = INST_igPDU.dump_VCD_defs(num);
  num = INST_igPtr.dump_VCD_defs(num);
  num = INST_igSA.dump_VCD_defs(num);
  num = INST_igSAF.dump_VCD_defs(num);
  num = INST_igSR.dump_VCD_defs(num);
  num = INST_igTyp.dump_VCD_defs(num);
  num = INST_l2Egress.dump_VCD_defs(num);
  num = INST_l2Egress_1.dump_VCD_defs(num);
  num = INST_l2Ingress.dump_VCD_defs(num);
  num = INST_l2Ingress_1.dump_VCD_defs(num);
  num = INST_l2RxF.dump_VCD_defs(num);
  num = INST_l2TxF.dump_VCD_defs(num);
  num = INST_uMAddr.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkL2Proc::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkL2Proc &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkL2Proc::vcd_defs(tVCDDumpType dt, MOD_mkL2Proc &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 10u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 10u);
    vcd_write_x(sim_hdl, num++, 10u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 48u);
    vcd_write_x(sim_hdl, num++, 10u);
    vcd_write_x(sim_hdl, num++, 10u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_l2Egress__dreg_update) != DEF_CAN_FIRE_RL_l2Egress__dreg_update)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2Egress__dreg_update, 1u);
	backing.DEF_CAN_FIRE_RL_l2Egress__dreg_update = DEF_CAN_FIRE_RL_l2Egress__dreg_update;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2Ingress__dreg_update) != DEF_CAN_FIRE_RL_l2Ingress__dreg_update)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2Ingress__dreg_update, 1u);
	backing.DEF_CAN_FIRE_RL_l2Ingress__dreg_update = DEF_CAN_FIRE_RL_l2Ingress__dreg_update;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2_egress_header) != DEF_CAN_FIRE_RL_l2_egress_header)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2_egress_header, 1u);
	backing.DEF_CAN_FIRE_RL_l2_egress_header = DEF_CAN_FIRE_RL_l2_egress_header;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2_egress_payload) != DEF_CAN_FIRE_RL_l2_egress_payload)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2_egress_payload, 1u);
	backing.DEF_CAN_FIRE_RL_l2_egress_payload = DEF_CAN_FIRE_RL_l2_egress_payload;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2_ingress_header) != DEF_CAN_FIRE_RL_l2_ingress_header)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2_ingress_header, 1u);
	backing.DEF_CAN_FIRE_RL_l2_ingress_header = DEF_CAN_FIRE_RL_l2_ingress_header;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_l2_ingress_payload) != DEF_CAN_FIRE_RL_l2_ingress_payload)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_l2_ingress_payload, 1u);
	backing.DEF_CAN_FIRE_RL_l2_ingress_payload = DEF_CAN_FIRE_RL_l2_ingress_payload;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_client_request_get) != DEF_CAN_FIRE_client_request_get)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_client_request_get, 1u);
	backing.DEF_CAN_FIRE_client_request_get = DEF_CAN_FIRE_client_request_get;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_client_response_put) != DEF_CAN_FIRE_client_response_put)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_client_response_put, 1u);
	backing.DEF_CAN_FIRE_client_response_put = DEF_CAN_FIRE_client_response_put;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_l2Rx) != DEF_CAN_FIRE_l2Rx)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_l2Rx, 1u);
	backing.DEF_CAN_FIRE_l2Rx = DEF_CAN_FIRE_l2Rx;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_l2Tx) != DEF_CAN_FIRE_l2Tx)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_l2Tx, 1u);
	backing.DEF_CAN_FIRE_l2Tx = DEF_CAN_FIRE_l2Tx;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_macAddr) != DEF_CAN_FIRE_macAddr)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_macAddr, 1u);
	backing.DEF_CAN_FIRE_macAddr = DEF_CAN_FIRE_macAddr;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_server_request_put) != DEF_CAN_FIRE_server_request_put)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_server_request_put, 1u);
	backing.DEF_CAN_FIRE_server_request_put = DEF_CAN_FIRE_server_request_put;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_server_response_get) != DEF_CAN_FIRE_server_response_get)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_server_response_get, 1u);
	backing.DEF_CAN_FIRE_server_response_get = DEF_CAN_FIRE_server_response_get;
      }
      ++num;
      if ((backing.DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29) != DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29, 8u);
	backing.DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29 = DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29;
      }
      ++num;
      if ((backing.DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19) != DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19)
      {
	vcd_write_val(sim_hdl, num, DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19, 1u);
	backing.DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19 = DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2Egress__dreg_update) != DEF_WILL_FIRE_RL_l2Egress__dreg_update)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2Egress__dreg_update, 1u);
	backing.DEF_WILL_FIRE_RL_l2Egress__dreg_update = DEF_WILL_FIRE_RL_l2Egress__dreg_update;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2Ingress__dreg_update) != DEF_WILL_FIRE_RL_l2Ingress__dreg_update)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2Ingress__dreg_update, 1u);
	backing.DEF_WILL_FIRE_RL_l2Ingress__dreg_update = DEF_WILL_FIRE_RL_l2Ingress__dreg_update;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2_egress_header) != DEF_WILL_FIRE_RL_l2_egress_header)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2_egress_header, 1u);
	backing.DEF_WILL_FIRE_RL_l2_egress_header = DEF_WILL_FIRE_RL_l2_egress_header;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2_egress_payload) != DEF_WILL_FIRE_RL_l2_egress_payload)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2_egress_payload, 1u);
	backing.DEF_WILL_FIRE_RL_l2_egress_payload = DEF_WILL_FIRE_RL_l2_egress_payload;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2_ingress_header) != DEF_WILL_FIRE_RL_l2_ingress_header)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2_ingress_header, 1u);
	backing.DEF_WILL_FIRE_RL_l2_ingress_header = DEF_WILL_FIRE_RL_l2_ingress_header;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_l2_ingress_payload) != DEF_WILL_FIRE_RL_l2_ingress_payload)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_l2_ingress_payload, 1u);
	backing.DEF_WILL_FIRE_RL_l2_ingress_payload = DEF_WILL_FIRE_RL_l2_ingress_payload;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_client_request_get) != DEF_WILL_FIRE_client_request_get)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_client_request_get, 1u);
	backing.DEF_WILL_FIRE_client_request_get = DEF_WILL_FIRE_client_request_get;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_client_response_put) != DEF_WILL_FIRE_client_response_put)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_client_response_put, 1u);
	backing.DEF_WILL_FIRE_client_response_put = DEF_WILL_FIRE_client_response_put;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_macAddr) != DEF_WILL_FIRE_macAddr)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_macAddr, 1u);
	backing.DEF_WILL_FIRE_macAddr = DEF_WILL_FIRE_macAddr;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_server_request_put) != DEF_WILL_FIRE_server_request_put)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_server_request_put, 1u);
	backing.DEF_WILL_FIRE_server_request_put = DEF_WILL_FIRE_server_request_put;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_server_response_get) != DEF_WILL_FIRE_server_response_get)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_server_response_get, 1u);
	backing.DEF_WILL_FIRE_server_response_get = DEF_WILL_FIRE_server_response_get;
      }
      ++num;
      if ((backing.DEF_b__h1816) != DEF_b__h1816)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h1816, 4u);
	backing.DEF_b__h1816 = DEF_b__h1816;
      }
      ++num;
      if ((backing.DEF_b__h5667) != DEF_b__h5667)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h5667, 4u);
	backing.DEF_b__h5667 = DEF_b__h5667;
      }
      ++num;
      if ((backing.DEF_egPtr_4_EQ_0___d55) != DEF_egPtr_4_EQ_0___d55)
      {
	vcd_write_val(sim_hdl, num, DEF_egPtr_4_EQ_0___d55, 1u);
	backing.DEF_egPtr_4_EQ_0___d55 = DEF_egPtr_4_EQ_0___d55;
      }
      ++num;
      if ((backing.DEF_egPtr_4_EQ_13___d57) != DEF_egPtr_4_EQ_13___d57)
      {
	vcd_write_val(sim_hdl, num, DEF_egPtr_4_EQ_13___d57, 1u);
	backing.DEF_egPtr_4_EQ_13___d57 = DEF_egPtr_4_EQ_13___d57;
      }
      ++num;
      if ((backing.DEF_egPtr_4_EQ_14___d86) != DEF_egPtr_4_EQ_14___d86)
      {
	vcd_write_val(sim_hdl, num, DEF_egPtr_4_EQ_14___d86, 1u);
	backing.DEF_egPtr_4_EQ_14___d86 = DEF_egPtr_4_EQ_14___d86;
      }
      ++num;
      if ((backing.DEF_igPDU__h5515) != DEF_igPDU__h5515)
      {
	vcd_write_val(sim_hdl, num, DEF_igPDU__h5515, 1u);
	backing.DEF_igPDU__h5515 = DEF_igPDU__h5515;
      }
      ++num;
      if ((backing.DEF_igPtr_EQ_11___d9) != DEF_igPtr_EQ_11___d9)
      {
	vcd_write_val(sim_hdl, num, DEF_igPtr_EQ_11___d9, 1u);
	backing.DEF_igPtr_EQ_11___d9 = DEF_igPtr_EQ_11___d9;
      }
      ++num;
      if ((backing.DEF_l2RxF_first__6_BITS_7_TO_0___d28) != DEF_l2RxF_first__6_BITS_7_TO_0___d28)
      {
	vcd_write_val(sim_hdl, num, DEF_l2RxF_first__6_BITS_7_TO_0___d28, 8u);
	backing.DEF_l2RxF_first__6_BITS_7_TO_0___d28 = DEF_l2RxF_first__6_BITS_7_TO_0___d28;
      }
      ++num;
      if ((backing.DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18) != DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18)
      {
	vcd_write_val(sim_hdl, num, DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18, 1u);
	backing.DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18 = DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18;
      }
      ++num;
      if ((backing.DEF_l2RxF_first__6_BITS_9_TO_8___d17) != DEF_l2RxF_first__6_BITS_9_TO_8___d17)
      {
	vcd_write_val(sim_hdl, num, DEF_l2RxF_first__6_BITS_9_TO_8___d17, 2u);
	backing.DEF_l2RxF_first__6_BITS_9_TO_8___d17 = DEF_l2RxF_first__6_BITS_9_TO_8___d17;
      }
      ++num;
      if ((backing.DEF_l2RxF_first____d16) != DEF_l2RxF_first____d16)
      {
	vcd_write_val(sim_hdl, num, DEF_l2RxF_first____d16, 10u);
	backing.DEF_l2RxF_first____d16 = DEF_l2RxF_first____d16;
      }
      ++num;
      if ((backing.PORT_EN_client_request_get) != PORT_EN_client_request_get)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_client_request_get, 1u);
	backing.PORT_EN_client_request_get = PORT_EN_client_request_get;
      }
      ++num;
      if ((backing.PORT_EN_client_response_put) != PORT_EN_client_response_put)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_client_response_put, 1u);
	backing.PORT_EN_client_response_put = PORT_EN_client_response_put;
      }
      ++num;
      if ((backing.PORT_EN_macAddr) != PORT_EN_macAddr)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_macAddr, 1u);
	backing.PORT_EN_macAddr = PORT_EN_macAddr;
      }
      ++num;
      if ((backing.PORT_EN_server_request_put) != PORT_EN_server_request_put)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_server_request_put, 1u);
	backing.PORT_EN_server_request_put = PORT_EN_server_request_put;
      }
      ++num;
      if ((backing.PORT_EN_server_response_get) != PORT_EN_server_response_get)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_server_response_get, 1u);
	backing.PORT_EN_server_response_get = PORT_EN_server_response_get;
      }
      ++num;
      if ((backing.PORT_RDY_client_request_get) != PORT_RDY_client_request_get)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_client_request_get, 1u);
	backing.PORT_RDY_client_request_get = PORT_RDY_client_request_get;
      }
      ++num;
      if ((backing.PORT_RDY_client_response_put) != PORT_RDY_client_response_put)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_client_response_put, 1u);
	backing.PORT_RDY_client_response_put = PORT_RDY_client_response_put;
      }
      ++num;
      if ((backing.PORT_RDY_l2Rx) != PORT_RDY_l2Rx)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_l2Rx, 1u);
	backing.PORT_RDY_l2Rx = PORT_RDY_l2Rx;
      }
      ++num;
      if ((backing.PORT_RDY_l2Tx) != PORT_RDY_l2Tx)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_l2Tx, 1u);
	backing.PORT_RDY_l2Tx = PORT_RDY_l2Tx;
      }
      ++num;
      if ((backing.PORT_RDY_macAddr) != PORT_RDY_macAddr)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_macAddr, 1u);
	backing.PORT_RDY_macAddr = PORT_RDY_macAddr;
      }
      ++num;
      if ((backing.PORT_RDY_server_request_put) != PORT_RDY_server_request_put)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_server_request_put, 1u);
	backing.PORT_RDY_server_request_put = PORT_RDY_server_request_put;
      }
      ++num;
      if ((backing.PORT_RDY_server_response_get) != PORT_RDY_server_response_get)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_server_response_get, 1u);
	backing.PORT_RDY_server_response_get = PORT_RDY_server_response_get;
      }
      ++num;
      if ((backing.PORT_client_request_get) != PORT_client_request_get)
      {
	vcd_write_val(sim_hdl, num, PORT_client_request_get, 10u);
	backing.PORT_client_request_get = PORT_client_request_get;
      }
      ++num;
      if ((backing.PORT_client_response_put) != PORT_client_response_put)
      {
	vcd_write_val(sim_hdl, num, PORT_client_response_put, 10u);
	backing.PORT_client_response_put = PORT_client_response_put;
      }
      ++num;
      if ((backing.PORT_l2Rx) != PORT_l2Rx)
      {
	vcd_write_val(sim_hdl, num, PORT_l2Rx, 1u);
	backing.PORT_l2Rx = PORT_l2Rx;
      }
      ++num;
      if ((backing.PORT_l2Tx) != PORT_l2Tx)
      {
	vcd_write_val(sim_hdl, num, PORT_l2Tx, 1u);
	backing.PORT_l2Tx = PORT_l2Tx;
      }
      ++num;
      if ((backing.PORT_macAddr_u) != PORT_macAddr_u)
      {
	vcd_write_val(sim_hdl, num, PORT_macAddr_u, 48u);
	backing.PORT_macAddr_u = PORT_macAddr_u;
      }
      ++num;
      if ((backing.PORT_server_request_put) != PORT_server_request_put)
      {
	vcd_write_val(sim_hdl, num, PORT_server_request_put, 10u);
	backing.PORT_server_request_put = PORT_server_request_put;
      }
      ++num;
      if ((backing.PORT_server_response_get) != PORT_server_response_get)
      {
	vcd_write_val(sim_hdl, num, PORT_server_response_get, 10u);
	backing.PORT_server_response_get = PORT_server_response_get;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2Egress__dreg_update, 1u);
      backing.DEF_CAN_FIRE_RL_l2Egress__dreg_update = DEF_CAN_FIRE_RL_l2Egress__dreg_update;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2Ingress__dreg_update, 1u);
      backing.DEF_CAN_FIRE_RL_l2Ingress__dreg_update = DEF_CAN_FIRE_RL_l2Ingress__dreg_update;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2_egress_header, 1u);
      backing.DEF_CAN_FIRE_RL_l2_egress_header = DEF_CAN_FIRE_RL_l2_egress_header;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2_egress_payload, 1u);
      backing.DEF_CAN_FIRE_RL_l2_egress_payload = DEF_CAN_FIRE_RL_l2_egress_payload;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2_ingress_header, 1u);
      backing.DEF_CAN_FIRE_RL_l2_ingress_header = DEF_CAN_FIRE_RL_l2_ingress_header;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_l2_ingress_payload, 1u);
      backing.DEF_CAN_FIRE_RL_l2_ingress_payload = DEF_CAN_FIRE_RL_l2_ingress_payload;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_client_request_get, 1u);
      backing.DEF_CAN_FIRE_client_request_get = DEF_CAN_FIRE_client_request_get;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_client_response_put, 1u);
      backing.DEF_CAN_FIRE_client_response_put = DEF_CAN_FIRE_client_response_put;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_l2Rx, 1u);
      backing.DEF_CAN_FIRE_l2Rx = DEF_CAN_FIRE_l2Rx;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_l2Tx, 1u);
      backing.DEF_CAN_FIRE_l2Tx = DEF_CAN_FIRE_l2Tx;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_macAddr, 1u);
      backing.DEF_CAN_FIRE_macAddr = DEF_CAN_FIRE_macAddr;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_server_request_put, 1u);
      backing.DEF_CAN_FIRE_server_request_put = DEF_CAN_FIRE_server_request_put;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_server_response_get, 1u);
      backing.DEF_CAN_FIRE_server_response_get = DEF_CAN_FIRE_server_response_get;
      vcd_write_val(sim_hdl, num++, DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29, 8u);
      backing.DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29 = DEF_IF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8_OR_l2Rx_ETC___d29;
      vcd_write_val(sim_hdl, num++, DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19, 1u);
      backing.DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19 = DEF_NOT_l2RxF_first__6_BITS_9_TO_8_7_EQ_0_8___d19;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2Egress__dreg_update, 1u);
      backing.DEF_WILL_FIRE_RL_l2Egress__dreg_update = DEF_WILL_FIRE_RL_l2Egress__dreg_update;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2Ingress__dreg_update, 1u);
      backing.DEF_WILL_FIRE_RL_l2Ingress__dreg_update = DEF_WILL_FIRE_RL_l2Ingress__dreg_update;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2_egress_header, 1u);
      backing.DEF_WILL_FIRE_RL_l2_egress_header = DEF_WILL_FIRE_RL_l2_egress_header;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2_egress_payload, 1u);
      backing.DEF_WILL_FIRE_RL_l2_egress_payload = DEF_WILL_FIRE_RL_l2_egress_payload;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2_ingress_header, 1u);
      backing.DEF_WILL_FIRE_RL_l2_ingress_header = DEF_WILL_FIRE_RL_l2_ingress_header;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_l2_ingress_payload, 1u);
      backing.DEF_WILL_FIRE_RL_l2_ingress_payload = DEF_WILL_FIRE_RL_l2_ingress_payload;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_client_request_get, 1u);
      backing.DEF_WILL_FIRE_client_request_get = DEF_WILL_FIRE_client_request_get;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_client_response_put, 1u);
      backing.DEF_WILL_FIRE_client_response_put = DEF_WILL_FIRE_client_response_put;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_macAddr, 1u);
      backing.DEF_WILL_FIRE_macAddr = DEF_WILL_FIRE_macAddr;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_server_request_put, 1u);
      backing.DEF_WILL_FIRE_server_request_put = DEF_WILL_FIRE_server_request_put;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_server_response_get, 1u);
      backing.DEF_WILL_FIRE_server_response_get = DEF_WILL_FIRE_server_response_get;
      vcd_write_val(sim_hdl, num++, DEF_b__h1816, 4u);
      backing.DEF_b__h1816 = DEF_b__h1816;
      vcd_write_val(sim_hdl, num++, DEF_b__h5667, 4u);
      backing.DEF_b__h5667 = DEF_b__h5667;
      vcd_write_val(sim_hdl, num++, DEF_egPtr_4_EQ_0___d55, 1u);
      backing.DEF_egPtr_4_EQ_0___d55 = DEF_egPtr_4_EQ_0___d55;
      vcd_write_val(sim_hdl, num++, DEF_egPtr_4_EQ_13___d57, 1u);
      backing.DEF_egPtr_4_EQ_13___d57 = DEF_egPtr_4_EQ_13___d57;
      vcd_write_val(sim_hdl, num++, DEF_egPtr_4_EQ_14___d86, 1u);
      backing.DEF_egPtr_4_EQ_14___d86 = DEF_egPtr_4_EQ_14___d86;
      vcd_write_val(sim_hdl, num++, DEF_igPDU__h5515, 1u);
      backing.DEF_igPDU__h5515 = DEF_igPDU__h5515;
      vcd_write_val(sim_hdl, num++, DEF_igPtr_EQ_11___d9, 1u);
      backing.DEF_igPtr_EQ_11___d9 = DEF_igPtr_EQ_11___d9;
      vcd_write_val(sim_hdl, num++, DEF_l2RxF_first__6_BITS_7_TO_0___d28, 8u);
      backing.DEF_l2RxF_first__6_BITS_7_TO_0___d28 = DEF_l2RxF_first__6_BITS_7_TO_0___d28;
      vcd_write_val(sim_hdl, num++, DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18, 1u);
      backing.DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18 = DEF_l2RxF_first__6_BITS_9_TO_8_7_EQ_0___d18;
      vcd_write_val(sim_hdl, num++, DEF_l2RxF_first__6_BITS_9_TO_8___d17, 2u);
      backing.DEF_l2RxF_first__6_BITS_9_TO_8___d17 = DEF_l2RxF_first__6_BITS_9_TO_8___d17;
      vcd_write_val(sim_hdl, num++, DEF_l2RxF_first____d16, 10u);
      backing.DEF_l2RxF_first____d16 = DEF_l2RxF_first____d16;
      vcd_write_val(sim_hdl, num++, PORT_EN_client_request_get, 1u);
      backing.PORT_EN_client_request_get = PORT_EN_client_request_get;
      vcd_write_val(sim_hdl, num++, PORT_EN_client_response_put, 1u);
      backing.PORT_EN_client_response_put = PORT_EN_client_response_put;
      vcd_write_val(sim_hdl, num++, PORT_EN_macAddr, 1u);
      backing.PORT_EN_macAddr = PORT_EN_macAddr;
      vcd_write_val(sim_hdl, num++, PORT_EN_server_request_put, 1u);
      backing.PORT_EN_server_request_put = PORT_EN_server_request_put;
      vcd_write_val(sim_hdl, num++, PORT_EN_server_response_get, 1u);
      backing.PORT_EN_server_response_get = PORT_EN_server_response_get;
      vcd_write_val(sim_hdl, num++, PORT_RDY_client_request_get, 1u);
      backing.PORT_RDY_client_request_get = PORT_RDY_client_request_get;
      vcd_write_val(sim_hdl, num++, PORT_RDY_client_response_put, 1u);
      backing.PORT_RDY_client_response_put = PORT_RDY_client_response_put;
      vcd_write_val(sim_hdl, num++, PORT_RDY_l2Rx, 1u);
      backing.PORT_RDY_l2Rx = PORT_RDY_l2Rx;
      vcd_write_val(sim_hdl, num++, PORT_RDY_l2Tx, 1u);
      backing.PORT_RDY_l2Tx = PORT_RDY_l2Tx;
      vcd_write_val(sim_hdl, num++, PORT_RDY_macAddr, 1u);
      backing.PORT_RDY_macAddr = PORT_RDY_macAddr;
      vcd_write_val(sim_hdl, num++, PORT_RDY_server_request_put, 1u);
      backing.PORT_RDY_server_request_put = PORT_RDY_server_request_put;
      vcd_write_val(sim_hdl, num++, PORT_RDY_server_response_get, 1u);
      backing.PORT_RDY_server_response_get = PORT_RDY_server_response_get;
      vcd_write_val(sim_hdl, num++, PORT_client_request_get, 10u);
      backing.PORT_client_request_get = PORT_client_request_get;
      vcd_write_val(sim_hdl, num++, PORT_client_response_put, 10u);
      backing.PORT_client_response_put = PORT_client_response_put;
      vcd_write_val(sim_hdl, num++, PORT_l2Rx, 1u);
      backing.PORT_l2Rx = PORT_l2Rx;
      vcd_write_val(sim_hdl, num++, PORT_l2Tx, 1u);
      backing.PORT_l2Tx = PORT_l2Tx;
      vcd_write_val(sim_hdl, num++, PORT_macAddr_u, 48u);
      backing.PORT_macAddr_u = PORT_macAddr_u;
      vcd_write_val(sim_hdl, num++, PORT_server_request_put, 10u);
      backing.PORT_server_request_put = PORT_server_request_put;
      vcd_write_val(sim_hdl, num++, PORT_server_response_get, 10u);
      backing.PORT_server_response_get = PORT_server_response_get;
    }
}

void MOD_mkL2Proc::vcd_prims(tVCDDumpType dt, MOD_mkL2Proc &backing)
{
  INST_dgRxF.dump_VCD(dt, backing.INST_dgRxF);
  INST_dgTxF.dump_VCD(dt, backing.INST_dgTxF);
  INST_egDA.dump_VCD(dt, backing.INST_egDA);
  INST_egL2Hdr.dump_VCD(dt, backing.INST_egL2Hdr);
  INST_egPDU.dump_VCD(dt, backing.INST_egPDU);
  INST_egPtr.dump_VCD(dt, backing.INST_egPtr);
  INST_egSA.dump_VCD(dt, backing.INST_egSA);
  INST_igDA.dump_VCD(dt, backing.INST_igDA);
  INST_igL2Hdr.dump_VCD(dt, backing.INST_igL2Hdr);
  INST_igPDU.dump_VCD(dt, backing.INST_igPDU);
  INST_igPtr.dump_VCD(dt, backing.INST_igPtr);
  INST_igSA.dump_VCD(dt, backing.INST_igSA);
  INST_igSAF.dump_VCD(dt, backing.INST_igSAF);
  INST_igSR.dump_VCD(dt, backing.INST_igSR);
  INST_igTyp.dump_VCD(dt, backing.INST_igTyp);
  INST_l2Egress.dump_VCD(dt, backing.INST_l2Egress);
  INST_l2Egress_1.dump_VCD(dt, backing.INST_l2Egress_1);
  INST_l2Ingress.dump_VCD(dt, backing.INST_l2Ingress);
  INST_l2Ingress_1.dump_VCD(dt, backing.INST_l2Ingress_1);
  INST_l2RxF.dump_VCD(dt, backing.INST_l2RxF);
  INST_l2TxF.dump_VCD(dt, backing.INST_l2TxF);
  INST_uMAddr.dump_VCD(dt, backing.INST_uMAddr);
}
