/*
 * Generated by Bluespec Compiler, version 2013.01.beta5 (build 30325, 2013-01-23)
 * 
 * On Mon Feb 11 14:32:25 EST 2013
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkHCrt_TB1_h__
#define __model_mkHCrt_TB1_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkHCrt_TB1.h"

/* Class declaration for a model of mkHCrt_TB1 */
class MODEL_mkHCrt_TB1 : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkHCrt_TB1 *mkHCrt_TB1_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkHCrt_TB1();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
  tUInt64 skip_license_check();
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkHCrt_TB1();
}

#endif /* ifndef __model_mkHCrt_TB1_h__ */
